-- 回滚初始化脚本
DROP TABLE IF EXISTS content_play_records CASCADE;
DROP TABLE IF EXISTS contents CASCADE;
DROP TABLE IF EXISTS processed_contents CASCADE;
DROP TABLE IF EXISTS raw_contents CASCADE;
DROP TABLE IF EXISTS user_role_rel CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS user_auth CASCADE;
DROP TABLE IF EXISTS users CASCADE;
