-- 为 device_state_log 表添加存储、扬声器、UWB定位、声学校准字段
SET search_path TO public;

ALTER TABLE public.device_state_log
  ADD COLUMN IF NOT EXISTS storage_used BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS storage_total BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS speaker_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS uwb_x DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS uwb_y DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS uwb_z DOUBLE PRECISION NULL,
  ADD COLUMN IF NOT EXISTS acoustic_calibrated SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS acoustic_offset DOUBLE PRECISION NULL;
