// Code generated by goctl. Safe to edit.
// goctl 1.9.2
// @title           AI Worker 微服务 API 文档
// @version         1.0
// @description     AI 音轨分离推理服务，支持多种 AI 模型，异步处理音频分离任务

// @contact.name   AI Worker Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8004
// @BasePath  /api/v1

package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"

	_ "github.com/jacklau/audio-ai-platform/services/ai-worker/docs"

	"github.com/jacklau/audio-ai-platform/common/validate"
	"github.com/jacklau/audio-ai-platform/services/ai-worker/internal/config"
	"github.com/jacklau/audio-ai-platform/services/ai-worker/internal/handler"
	"github.com/jacklau/audio-ai-platform/services/ai-worker/internal/svc"

	httpSwagger "github.com/swaggo/http-swagger/v2"
	"github.com/zeromicro/go-zero/core/conf"
	"github.com/zeromicro/go-zero/rest"
	"github.com/zeromicro/go-zero/rest/httpx"
)

var configFile = flag.String("f", "etc/ai-worker.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)

	server := rest.MustNewServer(c.RestConf)
	defer server.Stop()

	httpx.SetValidator(validate.NewHTTPValidator())

	svcCtx, err := svc.NewServiceContext(c)
	if err != nil {
		fmt.Printf("❌ 初始化服务上下文失败：%v\n", err)
		os.Exit(1)
	}

	swaggerHandler := httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8004/swagger/doc.json"),
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("list"),
		httpSwagger.DomID("swagger-ui"),
	)

	server.AddRoutes([]rest.Route{
		{
			Method: http.MethodGet,
			Path:   "/swagger/",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				swaggerHandler.ServeHTTP(w, r)
			},
		},
		{
			Method: http.MethodGet,
			Path:   "/swagger/index.html",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				swaggerHandler.ServeHTTP(w, r)
			},
		},
		{
			Method: http.MethodGet,
			Path:   "/swagger/doc.json",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				http.ServeFile(w, r, "./docs/swagger.json")
			},
		},
		{
			Method: http.MethodGet,
			Path:   "/swagger/:path",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				swaggerHandler.ServeHTTP(w, r)
			},
		},
	})

	// 注册路由（使用 routes.go）
	// ⭐ WebSocket 路由已在 routes.go 的 publicRoutes 中注册
	handler.RegisterHandlers(server, svcCtx)

	log.Println("=========================================")
	log.Println("✅ [FIXED] WebSocket route registered in routes.go!")
	log.Println("✅ [FIXED] Path: /api/v1/audio/separate/ws")
	log.Println("=========================================")

	root := strings.TrimSpace(c.Storage.Local.Root)
	if root == "" {
		root = "./data/ai-worker-objects"
	}
	if strings.EqualFold(strings.TrimSpace(c.Storage.Driver), "local") {
		_ = os.MkdirAll(root, 0755)
		fs := http.FileServer(http.Dir(root))
		server.AddRoute(rest.Route{
			Method: http.MethodGet,
			Path:   "/static-media/",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				http.StripPrefix("/static-media/", fs).ServeHTTP(w, r)
			},
		})
	}

	fmt.Println("=========================================")
	fmt.Println("🚀 AI Worker Service 启动中...")
	fmt.Println("=========================================")

	if svcCtx.AIService != nil && svcCtx.AIService.IsReady() {
		fmt.Println("✅ AI 模型已就绪")
	} else {
		fmt.Println("⚠️  AI 模型未就绪，部分功能可能受限")
	}

	fmt.Printf("\n📡 HTTP 服务信息:\n")
	fmt.Printf("   地址：http://%s:%d\n", c.Host, c.Port)
	fmt.Printf("   API 文档：http://%s:%d/swagger/\n", c.Host, c.Port)
	fmt.Printf("   健康检查：http://%s:%d/api/v1/health\n", c.Host, c.Port)

	fmt.Println()
	fmt.Println("=========================================")
	fmt.Println("🎉 服务启动完成，等待请求...")
	fmt.Println("=========================================")
	fmt.Println()

	server.Start()
}

func healthCheckHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")

		status := "healthy"
		if svcCtx.AIService == nil || !svcCtx.AIService.IsReady() {
			status = "degraded"
		}

		w.WriteHeader(http.StatusOK)
		w.Write([]byte(fmt.Sprintf(`{
			"status": "%s",
			"service": "ai-worker",
			"version": "1.0.0",
			"timestamp": "%s"
		}`, status, fmt.Sprintf("%d", 0))))
	}
}
