// Code generated by goctl. Safe to edit.
// goctl 1.9.2
// @title           AI Worker 微服务 API 文档
// @version         1.0
// @description     AI 音轨分离推理服务，支持多种 AI 模型，异步处理音频分离任务

// @contact.name   AI Worker Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8004
// @BasePath  /api/v1

package main

import (
	"flag"
	"fmt"
	"net/http"
	"os"
	"strings"

	_ "github.com/jacklau/audio-ai-platform/services/ai-worker/docs"

	"github.com/jacklau/audio-ai-platform/common/validate"
	"github.com/jacklau/audio-ai-platform/services/ai-worker/internal/config"
	"github.com/jacklau/audio-ai-platform/services/ai-worker/internal/grpcserver"
	"github.com/jacklau/audio-ai-platform/services/ai-worker/internal/svc"

	httpSwagger "github.com/swaggo/http-swagger/v2"
	"github.com/zeromicro/go-zero/core/conf"
	"github.com/zeromicro/go-zero/rest"
	"github.com/zeromicro/go-zero/rest/httpx"
)

var configFile = flag.String("f", "etc/ai-worker.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)

	server := rest.MustNewServer(c.RestConf)
	defer server.Stop()

	httpx.SetValidator(validate.NewHTTPValidator())

	svcCtx, err := svc.NewServiceContext(c)
	if err != nil {
		fmt.Printf("❌ 初始化服务上下文失败: %v\n", err)
		os.Exit(1)
	}

	swaggerHandler := httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8004/swagger/doc.json"),
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("list"),
		httpSwagger.DomID("swagger-ui"),
	)

	server.AddRoutes([]rest.Route{
		{
			Method: http.MethodGet,
			Path:   "/swagger/",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				swaggerHandler.ServeHTTP(w, r)
			},
		},
		{
			Method: http.MethodGet,
			Path:   "/swagger/index.html",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				swaggerHandler.ServeHTTP(w, r)
			},
		},
		{
			Method: http.MethodGet,
			Path:   "/swagger/doc.json",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				http.ServeFile(w, r, "./docs/swagger.json")
			},
		},
		{
			Method: http.MethodGet,
			Path:   "/swagger/:path",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				swaggerHandler.ServeHTTP(w, r)
			},
		},
	})

	server.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/api/v1/health",
			Handler: healthCheckHandler(svcCtx),
		},
	})

	root := strings.TrimSpace(c.Storage.Local.Root)
	if root == "" {
		root = "./data/ai-worker-objects"
	}
	if strings.EqualFold(strings.TrimSpace(c.Storage.Driver), "local") {
		_ = os.MkdirAll(root, 0755)
		fs := http.FileServer(http.Dir(root))
		server.AddRoute(rest.Route{
			Method: http.MethodGet,
			Path:   "/static-media/",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				http.StripPrefix("/static-media/", fs).ServeHTTP(w, r)
			},
		})
	}

	fmt.Println("=========================================")
	fmt.Println("🚀 AI Worker Service 启动中...")
	fmt.Println("=========================================")

	if svcCtx.AIService != nil && svcCtx.AIService.IsReady() {
		fmt.Println("✅ AI 模型已就绪")
	} else {
		fmt.Println("⚠️  AI 模型未就绪，部分功能可能受限")
	}

	grpcServer, err := startGRPCServer(svcCtx, c.GRPC)
	if err != nil {
		fmt.Printf("⚠️  gRPC 服务启动失败: %v (仅使用 HTTP 模式)\n", err)
	} else {
		fmt.Printf("✅ gRPC 服务已启动: :%d\n", c.GRPC.Port)
	}

	defer func() {
		if grpcServer != nil {
			grpcServer.Stop()
		}
	}()

	fmt.Printf("\n📡 HTTP 服务信息:\n")
	fmt.Printf("   地址: http://%s:%d\n", c.Host, c.Port)
	fmt.Printf("   API文档: http://%s:%d/swagger/\n", c.Host, c.Port)
	fmt.Printf("   健康检查: http://%s:%d/api/v1/health\n", c.Host, c.Port)

	if grpcServer != nil {
		fmt.Printf("\n🔌 gRPC 服务信息:\n")
		fmt.Printf("   地址: %s:%d\n", c.Host, c.GRPC.Port)
		fmt.Printf("   接口: InferenceService (流式推理)\n")
	}

	fmt.Println("\n=========================================")
	fmt.Println("🎉 服务启动完成，等待请求...")
	fmt.Println("=========================================\n")

	server.Start()
}

func healthCheckHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")

		status := "healthy"
		if svcCtx.AIService == nil || !svcCtx.AIService.IsReady() {
			status = "degraded"
		}

		w.WriteHeader(http.StatusOK)
		w.Write([]byte(fmt.Sprintf(`{
			"status": "%s",
			"service": "ai-worker",
			"version": "1.0.0",
			"grpc_enabled": true,
			"timestamp": "%s"
		}`, status, fmt.Sprintf("%d", 0))))
	}
}

func startGRPCServer(svcCtx *svc.ServiceContext, config config.GRPCConfig) (*grpcserver.Server, error) {
	if svcCtx.AIService == nil {
		return nil, fmt.Errorf("AI service not initialized")
	}

	grpcCfg := &grpcserver.Config{
		Port:           config.Port,
		TLSCertFile:    config.TLSCertFile,
		TLSKeyFile:     config.TLSKeyFile,
		MaxRecvMsgSize: config.MaxRecvMsgSize,
		MaxSendMsgSize: config.MaxSendMsgSize,
	}

	srv, err := grpcserver.NewServer(grpcCfg, svcCtx.AIService)
	if err != nil {
		return nil, fmt.Errorf("create gRPC server failed: %w", err)
	}

	err = srv.Start()
	if err != nil {
		return nil, fmt.Errorf("start gRPC server failed: %w", err)
	}

	return srv, nil
}
