// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/jacklau/audio-ai-platform/services/content/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 内容分页列表（可选登录；按用户会员等级自动过滤）
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: contentListHandler(serverCtx),
			},
			{
				// 最新内容推荐（可选登录）
				Method:  http.MethodGet,
				Path:    "/new",
				Handler: contentNewHandler(serverCtx),
			},
			{
				// 热门推荐（可选登录）
				Method:  http.MethodGet,
				Path:    "/popular",
				Handler: contentPopularHandler(serverCtx),
			},
			{
				// 猜你喜欢（必须登录）
				Method:  http.MethodGet,
				Path:    "/for-you",
				Handler: contentForYouHandler(serverCtx),
			},
			{
				// 个性化推荐（必须登录）
				Method:  http.MethodGet,
				Path:    "/recommend",
				Handler: contentRecommendHandler(serverCtx),
			},
			{
				// 流媒体播放（必须登录，支持 Range 断点续播）
				Method:  http.MethodGet,
				Path:    "/stream/:id",
				Handler: contentStreamHandler(serverCtx),
			},
			{
				// 下载歌曲（必须登录，浏览器弹出保存对话框）
				Method:  http.MethodGet,
				Path:    "/download/:id",
				Handler: contentDownloadHandler(serverCtx),
			},
			{
				// 删除下载记录（必须登录）
				Method:  http.MethodDelete,
				Path:    "/downloads",
				Handler: contentDownloadDeleteHandler(serverCtx),
			},
			{
				// 下载历史列表（必须登录）
				Method:  http.MethodGet,
				Path:    "/downloads",
				Handler: contentDownloadListHandler(serverCtx),
			},
			{
				// 加入同步队列（必须登录）
				Method:  http.MethodPost,
				Path:    "/downloads/sync/add",
				Handler: downloadSyncAddHandler(serverCtx),
			},
			{
				// 待同步列表（必须登录）
				Method:  http.MethodGet,
				Path:    "/downloads/sync/list",
				Handler: downloadSyncListHandler(serverCtx),
			},
			{
				// 确认删除云端记录（必须登录）
				Method:  http.MethodPost,
				Path:    "/downloads/sync/confirm",
				Handler: downloadSyncConfirmHandler(serverCtx),
			},
			{
				// 取消同步（必须登录）
				Method:  http.MethodPost,
				Path:    "/downloads/sync/cancel",
				Handler: downloadSyncCancelHandler(serverCtx),
			},
			{
				// 内容详情（必须登录）
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: contentDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/content"),
	)
}
