// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/jacklau/audio-ai-platform/services/content/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 内容分页列表（可选登录；按用户会员等级自动过滤）
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: contentListHandler(serverCtx),
			},
			{
				// 最新内容推荐（可选登录）
				Method:  http.MethodGet,
				Path:    "/new",
				Handler: contentNewHandler(serverCtx),
			},
			{
				// 热门推荐（可选登录）
				Method:  http.MethodGet,
				Path:    "/popular",
				Handler: contentPopularHandler(serverCtx),
			},
			{
				// 猜你喜欢（必须登录）
				Method:  http.MethodGet,
				Path:    "/for-you",
				Handler: contentForYouHandler(serverCtx),
			},
			{
				// 个性化推荐（必须登录）
				Method:  http.MethodGet,
				Path:    "/recommend",
				Handler: contentRecommendHandler(serverCtx),
			},
			{
				// 流媒体播放（必须登录，支持 Range 断点续播）
				Method:  http.MethodGet,
				Path:    "/stream/:id",
				Handler: contentStreamHandler(serverCtx),
			},
			{
				// 下载歌曲（必须登录，返回"下载中"状态）
				Method:  http.MethodGet,
				Path:    "/download/:id",
				Handler: contentDownloadHandler(serverCtx),
			},
			{
				// 确认下载完成（必须登录，更新状态为已下载）
				Method:  http.MethodPost,
				Path:    "/download/complete",
				Handler: downloadCompleteHandler(serverCtx),
			},
			{
				// 删除下载记录（必须登录）
				Method:  http.MethodDelete,
				Path:    "/downloads",
				Handler: contentDownloadDeleteHandler(serverCtx),
			},
			{
				// 下载历史列表（必须登录）
				Method:  http.MethodGet,
				Path:    "/downloads",
				Handler: contentDownloadListHandler(serverCtx),
			},
			{
				// 加入同步队列（必须登录）
				Method:  http.MethodPost,
				Path:    "/downloads/sync/add",
				Handler: downloadSyncAddHandler(serverCtx),
			},
			{
				// 待同步列表（必须登录）
				Method:  http.MethodGet,
				Path:    "/downloads/sync/list",
				Handler: downloadSyncListHandler(serverCtx),
			},
			{
				// 确认删除云端记录（必须登录）
				Method:  http.MethodPost,
				Path:    "/downloads/sync/confirm",
				Handler: downloadSyncConfirmHandler(serverCtx),
			},
			{
				// 取消同步（必须登录）
				Method:  http.MethodPost,
				Path:    "/downloads/sync/cancel",
				Handler: downloadSyncCancelHandler(serverCtx),
			},
			{
				// 歌单相关接口（必须在 /:id 之前注册）
				Method:  http.MethodPost,
				Path:    "/playlists",
				Handler: contentPlaylistCreateHandler(serverCtx),
			},
			{
				// 更新歌单（必须登录，只有创建者才能修改）
				Method:  http.MethodPut,
				Path:    "/playlists/:id",
				Handler: contentPlaylistUpdateHandler(serverCtx),
			},
			{
				// 删除歌单（必须登录，只有创建者才能删除）
				Method:  http.MethodDelete,
				Path:    "/playlists/:id",
				Handler: contentPlaylistDeleteHandler(serverCtx),
			},
			{
				// 添加歌曲到歌单（必须登录）
				Method:  http.MethodPost,
				Path:    "/playlists/:id/songs",
				Handler: contentPlaylistAddSongHandler(serverCtx),
			},
			{
				// 订阅音频（必须登录）
				Method:  http.MethodPost,
				Path:    "/:id/subscribe",
				Handler: contentSubscribeHandler(serverCtx),
			},
			{
				// 取消订阅音频（必须登录）
				Method:  http.MethodDelete,
				Path:    "/:id/subscribe",
				Handler: contentUnsubscribeHandler(serverCtx),
			},
			{
				// 订阅列表（必须登录，查看用户订阅的音频）
				Method:  http.MethodGet,
				Path:    "/subscriptions",
				Handler: contentSubscribeListHandler(serverCtx),
			},
			{
				// 歌手详情（查看歌手信息、热门歌曲、专辑列表）
				Method:  http.MethodGet,
				Path:    "/artists/:id",
				Handler: contentArtistDetailHandler(serverCtx),
			},
			{
				// 订阅通知（必须登录，内容发布时触发通知给订阅用户）
				Method:  http.MethodPost,
				Path:    "/:id/notify",
				Handler: contentSubscribeNotifyHandler(serverCtx),
			},
			{
				// 点赞列表（必须登录，查看用户点赞的歌曲）
				Method:  http.MethodGet,
				Path:    "/likes",
				Handler: contentLikeListHandler(serverCtx),
			},
			{
				// 播放开始（必须登录）
				Method:  http.MethodPost,
				Path:    "/play/start",
				Handler: contentPlayStartHandler(serverCtx),
			},
			{
				// 播放进度（必须登录，用于断点续播）
				Method:  http.MethodPost,
				Path:    "/play/progress",
				Handler: contentPlayProgressHandler(serverCtx),
			},
			{
				// 播放完成（必须登录）
				Method:  http.MethodPost,
				Path:    "/play/complete",
				Handler: contentPlayCompleteHandler(serverCtx),
			},
			{
				// 播放记录列表（必须登录）
				Method:  http.MethodGet,
				Path:    "/play/history",
				Handler: contentPlayHistoryListHandler(serverCtx),
			},
			{
				// 搜索歌曲
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: contentSearchHandler(serverCtx),
			},
			{
				// 删除歌曲（必须登录，管理员或上传者）
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: contentDeleteHandler(serverCtx),
			},
			{
				// 内容详情（必须登录）- 放在最后，避免覆盖具体路径
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: contentDetailHandler(serverCtx),
			},
			{
				// 点赞/取消点赞（必须登录，切换点赞状态）
				Method:  http.MethodPost,
				Path:    "/:id/like",
				Handler: contentLikeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/content"),
	)
}
