// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
//
// 路由分组说明（前缀见各 AddRoutes）：
// - 公开路由：无 JWT，路径已写全（含 /api/v1/user）。
// - JWT 路由：rest.WithPrefix("/api/v1/user")，下列 Path 为相对路径。

package handler

import (
	"net/http"

	"github.com/jacklau/audio-ai-platform/services/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// ---------- 公开路由（无需登录）----------
	server.AddRoutes(
		[]rest.Route{
			{
				// 登录：账号密码或验证码等（与 LoginReq 一致）
				Method:  http.MethodPost,
				Path:    "/api/v1/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				// 注册（需先调验证码接口）
				Method:  http.MethodPost,
				Path:    "/api/v1/user/register",
				Handler: registerHandler(serverCtx),
			},
			{
				// 忘记密码：验证码校验通过后重置密码
				Method:  http.MethodPost,
				Path:    "/api/v1/user/password/reset",
				Handler: resetPasswordHandler(serverCtx),
			},
			{
				// 刷新 access_token（refresh_token）
				Method:  http.MethodPost,
				Path:    "/api/v1/user/token/refresh",
				Handler: refreshTokenHandler(serverCtx),
			},
			{
				// 发送验证码（邮箱/手机；scene 区分注册/登录/换绑等）
				Method:  http.MethodPost,
				Path:    "/api/v1/user/verify/send",
				Handler: sendVerifyCodeHandler(serverCtx),
			},
		},
	)

	// ---------- 需 JWT：前缀 /api/v1/user ----------
	server.AddRoutes(
		[]rest.Route{
			{
				// 绑定邮箱或手机号（验证码）
				Method:  http.MethodPut,
				Path:    "/bind",
				Handler: bindContactHandler(serverCtx),
			},
			{
				// 绑定设备（device_sn 等）
				Method:  http.MethodPost,
				Path:    "/device/bind",
				Handler: BindDeviceHandler(serverCtx),
			},
			{
				// 当前用户已绑定设备列表（支持查询参数筛选分页）
				Method:  http.MethodGet,
				Path:    "/device/list",
				Handler: ListBindDeviceHandler(serverCtx),
			},
			{
				// 设备详情（查询参数 sn，校验绑定关系）
				Method:  http.MethodGet,
				Path:    "/device/detail",
				Handler: GetDeviceDetailHandler(serverCtx),
			},
			{
				// 发起设备共享邀请
				Method:  http.MethodPost,
				Path:    "/device/share/create",
				Handler: createDeviceShareHandler(serverCtx),
			},
			{
				// 接受共享（支持 batch：body 内 devices/list）
				Method:  http.MethodPost,
				Path:    "/device/share/accept",
				Handler: acceptDeviceShareHandler(serverCtx),
			},
			{
				// 受邀方拒绝共享
				Method:  http.MethodPost,
				Path:    "/device/share/reject",
				Handler: rejectDeviceShareHandler(serverCtx),
			},
			{
				// 发起方撤销共享
				Method:  http.MethodPost,
				Path:    "/device/share/cancel",
				Handler: cancelDeviceShareHandler(serverCtx),
			},
			{
				// 被共享方主动退出共享
				Method:  http.MethodPost,
				Path:    "/device/share/quit",
				Handler: quitDeviceShareHandler(serverCtx),
			},
			{
				// 我收到的共享列表
				Method:  http.MethodGet,
				Path:    "/device/share/my/receive/list",
				Handler: listReceivedDeviceSharesHandler(serverCtx),
			},
			{
				// 共享详情（查询参数 share_id）
				Method:  http.MethodGet,
				Path:    "/device/share/detail",
				Handler: getDeviceShareDetailHandler(serverCtx),
			},
			{
				// 当前登录用户信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				// 更新用户资料（昵称头像等）
				Method:  http.MethodPut,
				Path:    "/info",
				Handler: UpdateUserInfoHandler(serverCtx),
			},
			{
				// 修改登录密码（验证旧密码）
				Method:  http.MethodPut,
				Path:    "/password/change",
				Handler: changePasswordHandler(serverCtx),
			},
			{
				// 换绑邮箱/手机（双验证码流程）
				Method:  http.MethodPut,
				Path:    "/rebind",
				Handler: rebindContactHandler(serverCtx),
			},
			{
				// 登出：作废当前 access token / refresh
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: LogoutHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)
}
