// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"encoding/json"
	"net/http"
	"os"
	"time"

	"github.com/jacklau/audio-ai-platform/services/user/internal/middleware/auth"
	"github.com/jacklau/audio-ai-platform/services/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers 注册 user-api 全部路由（公开接口 + JWT 保护接口）。
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// #region agent log
	// debug-mode log: confirm realname route registration (no secrets / no PII)
	func() {
		type payload struct {
			SessionId     string         `json:"sessionId"`
			RunId         string         `json:"runId"`
			HypothesisId  string         `json:"hypothesisId"`
			Location      string         `json:"location"`
			Message       string         `json:"message"`
			Data          map[string]any `json:"data,omitempty"`
			TimestampUnix int64          `json:"timestamp"`
		}
		p := payload{
			SessionId:    "046601",
			RunId:        "pre-fix",
			HypothesisId: "H2_route_registered",
			Location:     "routes.go:RegisterHandlers",
			Message:      "registering routes (realname submit expected)",
			Data: map[string]any{
				"expectedMethod": "POST",
				"expectedPath":   "/api/v1/user/realname/submit",
			},
			TimestampUnix: time.Now().UnixMilli(),
		}
		b, _ := json.Marshal(p)
		f, err := os.OpenFile("C:\\Users\\Lenovo\\Desktop\\audio-ai-platform\\debug-046601.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
		if err == nil {
			_, _ = f.Write(append(b, '\n'))
			_ = f.Close()
		}
	}()
	// #endregion

	// 公开接口（无需认证）
	server.AddRoutes(
		[]rest.Route{
			{
				// 统一登录：account 或 email/mobile + password 或 verify_code（先发 scene=login）；微信/Google 走 OAuth
				// POST /api/v1/user/login
				// 用途：用户登录，支持账号密码、邮箱/手机验证码、OAuth 等多种登录方式
				Method:  http.MethodPost,
				Path:    "/api/v1/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				// Google OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
				// GET /api/v1/user/oauth/google/callback
				// 用途：Google OAuth 授权回调，自动创建或绑定用户并返回登录凭证
				Method:  http.MethodGet,
				Path:    "/api/v1/user/oauth/google/callback",
				Handler: OAuthGoogleCallbackHandler(serverCtx),
			},
			{
				// 微信 OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
				// GET /api/v1/user/oauth/wechat/callback
				// 用途：微信 OAuth 授权回调，自动创建或绑定用户并返回登录凭证
				Method:  http.MethodGet,
				Path:    "/api/v1/user/oauth/wechat/callback",
				Handler: OAuthWechatCallbackHandler(serverCtx),
			},
			{
				// 忘记旧密码：邮箱/手机号发送验证码后，验证验证码重置密码（新密码需输入两次且一致，且不能与旧密码一致）
				// POST /api/v1/user/password/reset
				// 用途：忘记密码时，通过邮箱/手机验证码重置密码
				Method:  http.MethodPost,
				Path:    "/api/v1/user/password/reset",
				Handler: ResetPasswordHandler(serverCtx),
			},
			{
				// 用户注册（需先发验证码；按邮箱/手机判断是否已注册；密码加盐存储）
				// POST /api/v1/user/register
				// 用途：新用户注册，支持邮箱或手机号注册
				Method:  http.MethodPost,
				Path:    "/api/v1/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				// 刷新 Token：使用 refresh_token 换取新的 access_token（无需重新登录）
				// POST /api/v1/user/token/refresh
				// 用途：使用刷新令牌获取新的访问令牌，延长登录有效期
				Method:  http.MethodPost,
				Path:    "/api/v1/user/token/refresh",
				Handler: RefreshTokenHandler(serverCtx),
			},
			{
				// 发送验证码（邮箱或手机二选一，1 分钟有效，1 分钟最多 3 条，超过提示 3 分钟后重试）
				// POST /api/v1/user/verify/send
				// 用途：发送验证码到邮箱或手机，用于注册、登录、找回密码等场景
				Method:  http.MethodPost,
				Path:    "/api/v1/user/verify/send",
				Handler: SendVerifyCodeHandler(serverCtx),
			},
			{
				// 跳转微信 OAuth 授权页（带 state）
				// GET /api/v1/user/oauth/wechat
				// 用途：跳转到微信 OAuth 授权页面
				Method:  http.MethodGet,
				Path:    "/api/v1/user/oauth/wechat",
				Handler: OAuthWechatStartHandler(serverCtx),
			},
			{
				// 跳转 Google OAuth 授权页（带 state）
				// GET /api/v1/user/oauth/google
				// 用途：跳转到 Google OAuth 授权页面
				Method:  http.MethodGet,
				Path:    "/api/v1/user/oauth/google",
				Handler: OAuthGoogleStartHandler(serverCtx),
			},
			{
				// 会员支付渠道回调（无 JWT；验签见 config.Payment.MockCallbackSecret）
				// POST /api/v1/user/member/pay/callback
				// 用途：会员订单支付回调接口，处理支付结果通知
				Method:  http.MethodPost,
				Path:    "/api/v1/user/member/pay/callback",
				Handler: MemberPayCallbackHandler(serverCtx),
			},
		},
	)

	// JWT 保护的接口（需要登录）
	jwtProtected := []rest.Route{
		{
			// 后台：会员列表（仅 super_admin/admin）
			// GET /api/v1/user/admin/members
			// 用途：后台管理员查询会员列表，仅超级管理员和管理员角色可访问
			Method:  http.MethodGet,
			Path:    "/admin/members",
			Handler: AdminMemberListHandler(serverCtx),
		},
		{
			// 绑定邮箱/手机号（已登录，邮箱或手机号二选一 + 验证码；验证码校验成功后进行绑定）
			// PUT /api/v1/user/bind
			// 用途：为当前登录用户绑定邮箱或手机号
			Method:  http.MethodPut,
			Path:    "/bind",
			Handler: BindContactHandler(serverCtx),
		},
		{
			// 查询当前登录用户的会员权益
			// GET /api/v1/user/member/benefits
			// 用途：查询当前用户的会员权益列表
			Method:  http.MethodGet,
			Path:    "/member/benefits",
			Handler: GetUserMemberBenefitsHandler(serverCtx),
		},
		{
			// 查询当前登录用户的会员信息
			// GET /api/v1/user/member/info
			// 用途：查询当前用户的会员等级、有效期等信息
			Method:  http.MethodGet,
			Path:    "/member/info",
			Handler: GetUserMemberInfoHandler(serverCtx),
		},
		{
			// 用户权益校验
			// POST /api/v1/user/benefit/check
			// 用途：校验用户是否拥有某项权益
			Method:  http.MethodPost,
			Path:    "/benefit/check",
			Handler: CheckUserBenefitHandler(serverCtx),
		},
		{
			// 创建家庭组（仅管理员/超级管理员）
			// POST /api/v1/user/family/create
			// 用途：创建新的家庭组，创建者自动成为管理员
			Method:  http.MethodPost,
			Path:    "/family/create",
			Handler: CreateFamilyHandler(serverCtx),
		},
		{
			// 查询当前家庭组信息
			// GET /api/v1/user/family/current
			// 用途：查询当前用户所属的家庭组详情
			Method:  http.MethodGet,
			Path:    "/family/current",
			Handler: GetCurrentFamilyHandler(serverCtx),
		},
		{
			// 邀请家庭成员（需验证被邀请人信息）
			// POST /api/v1/user/family/member/invite
			// 用途：邀请其他用户加入家庭组
			Method:  http.MethodPost,
			Path:    "/family/member/invite",
			Handler: InviteFamilyMemberHandler(serverCtx),
		},
		{
			// 接受家庭成员邀请
			// POST /api/v1/user/family/member/accept
			// 用途：接受加入家庭组的邀请
			Method:  http.MethodPost,
			Path:    "/family/member/accept",
			Handler: AcceptFamilyMemberHandler(serverCtx),
		},
		{
			// 移除家庭成员（仅管理员可操作）
			// POST /api/v1/user/family/member/remove
			// 用途：从家庭组中移除成员
			Method:  http.MethodPost,
			Path:    "/family/member/remove",
			Handler: RemoveFamilyMemberHandler(serverCtx),
		},
		{
			// 更新家庭成员角色（仅管理员可操作）
			// POST /api/v1/user/family/member/role/update
			// 用途：修改家庭成员的角色（管理员/普通成员）
			Method:  http.MethodPost,
			Path:    "/family/member/role/update",
			Handler: UpdateFamilyMemberRoleHandler(serverCtx),
		},
		{
			// 查询家庭成员列表
			// GET /api/v1/user/family/member/list
			// 用途：查询当前家庭组的所有成员信息
			Method:  http.MethodGet,
			Path:    "/family/member/list",
			Handler: ListFamilyMembersHandler(serverCtx),
		},
		{
			// 创建设备共享（将设备共享给其他用户）
			// POST /api/v1/user/device/share/create
			// 用途：创建设备共享，将设备权限分享给其他用户
			Method:  http.MethodPost,
			Path:    "/device/share/create",
			Handler: CreateDeviceShareHandler(serverCtx),
		},
		{
			// 接受设备共享
			// POST /api/v1/user/device/share/accept
			// 用途：接受其他用户共享的设备
			Method:  http.MethodPost,
			Path:    "/device/share/accept",
			Handler: AcceptDeviceShareHandler(serverCtx),
		},
		{
			// 撤销设备共享（仅共享者可操作）
			// POST /api/v1/user/device/share/revoke
			// 用途：撤销已共享的设备权限
			Method:  http.MethodPost,
			Path:    "/device/share/revoke",
			Handler: RevokeDeviceShareHandler(serverCtx),
		},
		{
			// 退出设备共享（被共享者主动退出）
			// POST /api/v1/user/device/share/quit
			// 用途：退出已接受共享的设备
			Method:  http.MethodPost,
			Path:    "/device/share/quit",
			Handler: QuitDeviceShareHandler(serverCtx),
		},
		{
			// 查询我发出的设备共享列表
			// GET /api/v1/user/device/share/sent
			// 用途：查询当前用户发出的所有设备共享记录
			Method:  http.MethodGet,
			Path:    "/device/share/sent",
			Handler: ListSentDeviceSharesHandler(serverCtx),
		},
		{
			// 查询我收到的设备共享列表
			// GET /api/v1/user/device/share/received
			// 用途：查询当前用户收到的所有设备共享记录
			Method:  http.MethodGet,
			Path:    "/device/share/received",
			Handler: ListReceivedDeviceSharesHandler(serverCtx),
		},
		{
			// 查询设备共享详情
			// GET /api/v1/user/device/share/detail
			// 用途：查询指定设备共享的详细信息
			Method:  http.MethodGet,
			Path:    "/device/share/detail",
			Handler: GetDeviceShareDetailHandler(serverCtx),
		},
		{
			// 更新用户资料（Header JWT；body 仅传要修改的字段）
			// PUT /api/v1/user/info
			// 用途：更新当前用户的基本信息（昵称、头像等）
			Method:  http.MethodPut,
			Path:    "/info",
			Handler: UpdateUserInfoHandler(serverCtx),
		},
		{
			// 修改密码：验证旧密码后修改（新密码需输入两次且一致，且不能与旧密码一致）
			// PUT /api/v1/user/password/change
			// 用途：修改当前用户的登录密码
			Method:  http.MethodPut,
			Path:    "/password/change",
			Handler: ChangePasswordHandler(serverCtx),
		},
		{
			// 换绑邮箱/手机号（已登录：旧账号验证码通过 + 新账号验证码通过后完成换绑）
			// PUT /api/v1/user/rebind
			// 用途：更换已绑定的邮箱或手机号
			Method:  http.MethodPut,
			Path:    "/rebind",
			Handler: RebindContactHandler(serverCtx),
		},
		{
			// 实名换绑：姓名 + 身份证 + 新号验证码（scene=bind），限流与冷却同普通换绑
			// PUT /api/v1/user/rebind/realname
			// 用途：实名认证用户更换绑定的邮箱或手机号，需验证身份信息
			Method:  http.MethodPut,
			Path:    "/rebind/realname",
			Handler: RealnameRebindHandler(serverCtx),
		},
		{
			// 提交实名认证信息
			// POST /api/v1/user/realname/submit
			// 用途：提交实名认证申请，等待后台审核
			Method:  http.MethodPost,
			Path:    "/realname/submit",
			Handler: SubmitRealNameHandler(serverCtx),
		},
		{
			// 查询实名认证状态
			// GET /api/v1/user/realname/status
			// 用途：查询当前用户的实名认证状态（未认证/审核中/已通过/已拒绝）
			Method:  http.MethodGet,
			Path:    "/realname/status",
			Handler: GetRealNameStatusHandler(serverCtx),
		},
		{
			// 查询实名认证审核详情
			// GET /api/v1/user/realname/audit
			// 用途：查询实名认证的审核详情，包括拒绝原因等
			Method:  http.MethodGet,
			Path:    "/realname/audit",
			Handler: GetRealNameAuditInfoHandler(serverCtx),
		},
		{
			// 申请注销账号
			// POST /api/v1/user/cancellation/apply
			// 用途：申请注销当前账号，进入冷静期
			Method:  http.MethodPost,
			Path:    "/cancellation/apply",
			Handler: ApplyAccountCancellationHandler(serverCtx),
		},
		{
			// 撤销注销申请
			// POST /api/v1/user/cancellation/withdraw
			// 用途：在冷静期内撤销注销申请，恢复账号
			Method:  http.MethodPost,
			Path:    "/cancellation/withdraw",
			Handler: WithdrawAccountCancellationHandler(serverCtx),
		},
		{
			// 查询账号注销状态
			// GET /api/v1/user/cancellation/status
			// 用途：查询账号注销申请的状态
			Method:  http.MethodGet,
			Path:    "/cancellation/status",
			Handler: GetAccountCancellationStatusHandler(serverCtx),
		},
		{
			// 获取注销确认页面信息
			// GET /api/v1/user/cancellation/confirm
			// 用途：获取账号注销确认页面的提示信息
			Method:  http.MethodGet,
			Path:    "/cancellation/confirm",
			Handler: GetAccountCancellationConfirmHandler(serverCtx),
		},
		{
			// 用户登出
			// POST /api/v1/user/logout
			// 用途：用户登出，将 token 加入黑名单
			Method:  http.MethodPost,
			Path:    "/logout",
			Handler: LogoutHandler(serverCtx),
		},
		{
			// 当前登录会话列表
			// GET /api/v1/user/login/sessions
			// 用途：查询当前用户的所有登录会话信息
			Method:  http.MethodGet,
			Path:    "/login/sessions",
			Handler: listLoginSessionsHandler(serverCtx),
		},
		{
			// 吊销指定登录会话（强制下线）
			// POST /api/v1/user/login/sessions/kick
			// 用途：强制吊销指定登录会话，使该会话立即失效
			Method:  http.MethodPost,
			Path:    "/login/sessions/kick",
			Handler: kickLoginSessionHandler(serverCtx),
		},
		{
			// 获取内容下载地址（后台悄悄请求，用户无感知）
			// POST /api/v1/user/content/download-url
			// 用途：获取私有格式内容的下载地址，用于前端异步下载
			Method:  http.MethodPost,
			Path:    "/content/download-url",
			Handler: getDownloadURLHandler(serverCtx),
		},
		{
			// 内容流式下载（边下边播+异步保存本地）
			// GET /api/v1/user/content/download/stream
			// 用途：流式传输私有格式内容，同时保存到本地
			Method:  http.MethodGet,
			Path:    "/content/download/stream",
			Handler: contentDownloadHandler(serverCtx),
		},
		{
			// 查询用户下载记录列表
			// GET /api/v1/user/download/records
			// 用途：查询当前用户的下载记录列表，支持分页、状态筛选、关键词搜索
			Method:  http.MethodGet,
			Path:    "/download/records",
			Handler: listDownloadRecordsHandler(serverCtx),
		},
		{
			// 创建下载记录
			// POST /api/v1/user/download/create
			// 用途：用户点击下载时创建下载记录，返回下载地址和断点位置
			Method:  http.MethodPost,
			Path:    "/download/create",
			Handler: createDownloadRecordHandler(serverCtx),
		},
		{
			// 更新下载进度
			// POST /api/v1/user/download/progress
			// 用途：前端定时上报下载进度到云端
			Method:  http.MethodPost,
			Path:    "/download/progress",
			Handler: updateDownloadProgressHandler(serverCtx),
		},
		{
			// 完成下载
			// POST /api/v1/user/download/complete
			// 用途：前端通知后端下载完成，更新状态为已完成
			Method:  http.MethodPost,
			Path:    "/download/complete",
			Handler: completeDownloadHandler(serverCtx),
		},
		{
			// 继续下载（断点续传）
			// POST /api/v1/user/download/resume
			// 用途：中断后继续下载，返回断点位置
			Method:  http.MethodPost,
			Path:    "/download/resume",
			Handler: resumeDownloadHandler(serverCtx),
		},
		{
			// 删除下载记录（单条删除）
			// DELETE /api/v1/user/download/delete
			// 用途：用户主动删除单条下载记录，同时前端删除本地文件
			Method:  http.MethodDelete,
			Path:    "/download/delete",
			Handler: deleteDownloadRecordHandler(serverCtx),
		},
		{
			// 批量同步删除下载记录
			// POST /api/v1/user/download/sync-delete
			// 用途：App 清理本地缓存后，同步删除云端对应的下载记录
			Method:  http.MethodPost,
			Path:    "/download/sync-delete",
			Handler: syncDeleteDownloadRecordsHandler(serverCtx),
		},
		{
			// 解绑 OAuth 账号
			// DELETE /api/v1/user/oauth/:platform
			// 用途：解绑第三方 OAuth 账号（微信/Google 等）
			Method:  http.MethodDelete,
			Path:    "/oauth/:platform",
			Handler: OAuthUnbindHandler(serverCtx),
		},
	}
	server.AddRoutes(
		rest.WithMiddleware(
			auth.Middleware(serverCtx.Config.Auth.AccessSecret, serverCtx.Config.Login.JWTBlacklistDisabled),
			jwtProtected...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)

	// 会员下单/支付：使用完整路径注册（与 login 等公开全路径一致），避免部分环境下 WithPrefix 拼接与客户端路径不一致导致 404。
	server.AddRoutes(
		rest.WithMiddleware(
			auth.Middleware(serverCtx.Config.Auth.AccessSecret, serverCtx.Config.Login.JWTBlacklistDisabled),
			rest.Route{
				// 创建会员订单
				// POST /api/v1/user/member/create_order
				// 用途：创建会员购买订单
				Method:  http.MethodPost,
				Path:    "/api/v1/user/member/create_order",
				Handler: CreateMemberOrderHandler(serverCtx),
			},
			rest.Route{
				// 会员订单支付
				// POST /api/v1/user/member/pay
				// 用途：发起会员订单支付
				Method:  http.MethodPost,
				Path:    "/api/v1/user/member/pay",
				Handler: PayMemberOrderHandler(serverCtx),
			},
			rest.Route{
				// 模拟支付（开发/测试环境使用）
				// POST /api/v1/user/member/mock_pay
				// 用途：模拟支付接口，用于开发测试环境
				Method:  http.MethodPost,
				Path:    "/api/v1/user/member/mock_pay",
				Handler: MockPayMemberOrderHandler(serverCtx),
			},
			rest.Route{
				// 查询会员自动续费状态
				// GET /api/v1/user/member/auto_renew
				// 用途：查询会员是否开启自动续费
				Method:  http.MethodGet,
				Path:    "/api/v1/user/member/auto_renew",
				Handler: GetMemberAutoRenewHandler(serverCtx),
			},
			rest.Route{
				// 设置会员自动续费状态
				// POST /api/v1/user/member/auto_renew
				// 用途：开启或关闭会员自动续费功能
				Method:  http.MethodPost,
				Path:    "/api/v1/user/member/auto_renew",
				Handler: SetMemberAutoRenewHandler(serverCtx),
			},
			rest.Route{
				// 会员取消订阅（解约自动续费）
				// POST /api/v1/user/member/unsubscribe
				// 用途：取消会员订阅，关闭自动续费
				Method:  http.MethodPost,
				Path:    "/api/v1/user/member/unsubscribe",
				Handler: UnsubscribeMemberHandler(serverCtx),
			},
			rest.Route{
				// 撤销会员取消订阅申请
				// POST /api/v1/user/member/unsubscribe/revoke
				// 用途：撤销已提交的会员取消订阅申请，恢复自动续费
				Method:  http.MethodPost,
				Path:    "/api/v1/user/member/unsubscribe/revoke",
				Handler: RevokeMemberUnsubscribeHandler(serverCtx),
			},
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix(""),
	)
}
