// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/jacklau/audio-ai-platform/services/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 统一登录：account 或 email/mobile + password（密码登录）或 verify_code（验证码登录/静默注册，先发 verify/send scene=login）；微信/Google 走 OAuth
				Method:  http.MethodPost,
				Path:    "/api/v1/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				// Google OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
				Method:  http.MethodGet,
				Path:    "/api/v1/user/oauth/google/callback",
				Handler: oauthGoogleCallbackHandler(serverCtx),
			},
			{
				// 微信 OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
				Method:  http.MethodGet,
				Path:    "/api/v1/user/oauth/wechat/callback",
				Handler: oauthWechatCallbackHandler(serverCtx),
			},
			{
				// 忘记旧密码：邮箱/手机号发送验证码后，验证验证码重置密码（新密码需输入两次且一致，且不能与旧密码一致）
				Method:  http.MethodPost,
				Path:    "/api/v1/user/password/reset",
				Handler: resetPasswordHandler(serverCtx),
			},
			{
				// 用户注册（需先发验证码；按邮箱/手机判断是否已注册；密码加盐存储）
				Method:  http.MethodPost,
				Path:    "/api/v1/user/register",
				Handler: registerHandler(serverCtx),
			},
			{
				// 刷新 Token：使用 refresh_token 换取新的 access_token（无需重新登录）
				Method:  http.MethodPost,
				Path:    "/api/v1/user/token/refresh",
				Handler: refreshTokenHandler(serverCtx),
			},
			{
				// 发送验证码（邮箱或手机号二选一，1分钟有效，1分钟最多3条，超过提示3分钟后重试）
				Method:  http.MethodPost,
				Path:    "/api/v1/user/verify/send",
				Handler: sendVerifyCodeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 绑定邮箱/手机号（已登录，邮箱或手机号二选一 + 验证码；验证码校验成功后进行绑定）
				Method:  http.MethodPut,
				Path:    "/bind",
				Handler: bindContactHandler(serverCtx),
			},
			{
				// 绑定设备（用户通过蓝牙或扫描二维码获取设备SN，输入备注信息进行绑定）
				Method:  http.MethodPost,
				Path:    "/device/bind",
				Handler: BindDeviceHandler(serverCtx),
			},
			{
				// 查询当前用户绑定的设备列表（仅返回 SN 和备注名称）
				Method:  http.MethodGet,
				Path:    "/device/list",
				Handler: ListBindDeviceHandler(serverCtx),
			},
			{
				// 查询设备详情（返回设备全字段，需校验用户权限）
				Method:  http.MethodGet,
				Path:    "/device/detail",
				Handler: GetDeviceDetailHandler(serverCtx),
			},
			{
				// 解绑设备（用户解除自己账号下某台设备的绑定关系）
				Method:  http.MethodPost,
				Path:    "/device/unbind",
				Handler: UnbindDeviceHandler(serverCtx),
			},
			{
				// 发起设备共享
				Method:  http.MethodPost,
				Path:    "/device/share/create",
				Handler: createDeviceShareHandler(serverCtx),
			},
			{
				// 接受设备共享邀请
				Method:  http.MethodPost,
				Path:    "/device/share/accept",
				Handler: acceptDeviceShareHandler(serverCtx),
			},
			{
				// 拒绝设备共享邀请
				Method:  http.MethodPost,
				Path:    "/device/share/reject",
				Handler: rejectDeviceShareHandler(serverCtx),
			},
			{
				// 撤销设备共享（仅共享者可操作）
				Method:  http.MethodPost,
				Path:    "/device/share/cancel",
				Handler: cancelDeviceShareHandler(serverCtx),
			},
			{
				// 退出设备共享（被共享者主动退出）
				Method:  http.MethodPost,
				Path:    "/device/share/quit",
				Handler: quitDeviceShareHandler(serverCtx),
			},
			{
				// 查询我发出的设备共享列表
				Method:  http.MethodGet,
				Path:    "/device/share/my/send/list",
				Handler: listSentDeviceSharesHandler(serverCtx),
			},
			{
				// 查询我收到的设备共享列表
				Method:  http.MethodGet,
				Path:    "/device/share/my/receive/list",
				Handler: listReceivedDeviceSharesHandler(serverCtx),
			},
			{
				// 查询共享详情
				Method:  http.MethodGet,
				Path:    "/device/share/detail",
				Handler: getDeviceShareDetailHandler(serverCtx),
			},
			{
				// 查询当前用户信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				// 修改用户基本信息（支持头像上传）
				Method:  http.MethodPut,
				Path:    "/info",
				Handler: UpdateUserInfoHandler(serverCtx),
			},
			{
				// 修改密码：验证旧密码后修改（新密码需输入两次且一致，且不能与旧密码一致）
				Method:  http.MethodPut,
				Path:    "/password/change",
				Handler: changePasswordHandler(serverCtx),
			},
			{
				// 换绑邮箱/手机号（已登录：旧账号验证码通过 + 新账号验证码通过后完成换绑）
				Method:  http.MethodPut,
				Path:    "/rebind",
				Handler: rebindContactHandler(serverCtx),
			},
			{
				// 退出登录（将当前token加入黑名单，同时清理refresh_token）
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: LogoutHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)
}
