// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApplyAccountCancellationReq struct {
	Password     string `json:"password,optional"`
	Reason       string `json:"reason,optional"`
	AgreementAck bool   `json:"agreement_ack"`
}

type ApplyAccountCancellationResp struct {
	CoolingEndAt int64 `json:"cooling_end_at"`
}

type BindContactReq struct {
	Email         string `json:"email,optional"`
	Mobile        string `json:"mobile,optional"`
	VerifyCode    string `json:"verify_code,optional"`
	OldMobile     string `json:"old_mobile,optional"`
	OldEmail      string `json:"old_email,optional"`
	OldVerifyCode string `json:"old_verify_code,optional"`
	NewMobile     string `json:"new_mobile,optional"`
	NewEmail      string `json:"new_email,optional"`
	NewVerifyCode string `json:"new_verify_code,optional"`
}

type ChangePasswordReq struct {
	OldPassword        string `json:"old_password"`
	NewPassword        string `json:"new_password"`
	NewPasswordConfirm string `json:"new_password_confirm"`
}

type ChangePasswordResp struct {
	Message string `json:"message"`
}

type BindDeviceReq struct {
	Sn         string `json:"sn"`
	DeviceName string `json:"device_name"`
}

type BindDeviceResp struct {
	UserId     int64  `json:"user_id"`
	DeviceSn   string `json:"device_sn"`
	DeviceName string `json:"device_name"`
	BindTime   string `json:"bind_time"`
}

type DeviceDetailReq struct {
	Sn string `form:"sn"`
}

type DeviceDetailResp struct {
	Sn              string `json:"sn"`
	DeviceType      string `json:"device_type"`
	OnlineStatus    int16  `json:"online_status"`
	FirmwareVersion string `json:"firmware_version"`
	HardwareVersion string `json:"hardware_version"`
	Manufacturer    string `json:"manufacturer"`
	CreateTime      string `json:"create_time"`
	UpdateTime      string `json:"update_time"`
}

type DeviceListItem struct {
	Sn         string `json:"sn"`
	DeviceName string `json:"device_name"`
}

type DeviceListResp struct {
	List []DeviceListItem `json:"list"`
}

type UnbindDeviceReq struct {
	Sn string `json:"sn"`
}

type UnbindDeviceResp struct {
	UserId     int64  `json:"user_id"`
	DeviceSn   string `json:"device_sn"`
	UnbindTime string `json:"unbind_time"`
}

type DeviceShareCreateReq struct {
	Sn         string `json:"sn"`
	ShareTo    string `json:"share_to"`
	ExpireDays int    `json:"expire_days"`
}

// DeviceShareAcceptDeviceRef 批量同意共享时的单条引用（与「收到的共享列表」字段对齐，至少填 share_id 或 sn 之一）。
type DeviceShareAcceptDeviceRef struct {
	ShareId int64  `json:"share_id,omitempty"`
	Sn      string `json:"sn,omitempty"`
}

type DeviceShareAcceptReq struct {
	ShareId int64                        `json:"share_id,omitempty"`
	Sn      string                       `json:"sn,omitempty"`
	Devices []DeviceShareAcceptDeviceRef `json:"devices,omitempty"`
	List    []DeviceShareAcceptDeviceRef `json:"list,omitempty"` // 与 devices 等价，兼容前端命名
}

// DeviceShareAcceptBatchResp 批量同意的结果：成功的条目 + 失败条目（逐条独立事务，互不影响）。
type DeviceShareAcceptBatchResp struct {
	Accepted []DeviceShareItem           `json:"accepted"`
	Failed   []DeviceShareAcceptFailItem `json:"failed,omitempty"`
}

type DeviceShareAcceptFailItem struct {
	ShareId int64  `json:"share_id,omitempty"`
	Sn      string `json:"sn,omitempty"`
	Code    int    `json:"code"`
	Msg     string `json:"msg"`
}

type DeviceShareRejectReq struct {
	ShareId int64  `json:"share_id,omitempty"`
	Sn      string `json:"sn,omitempty"`
}

type DeviceShareCancelReq struct {
	ShareId int64  `json:"share_id"`
	Sn      string `json:"sn"`
}

type DeviceShareItem struct {
	ShareId    int64  `json:"share_id"`
	Sn         string `json:"sn"`
	ShareTo    string `json:"share_to"`
	ExpireDays int    `json:"expire_days"`
	Status     int16  `json:"status"`
	CreatedAt  string `json:"create_time"`
	EndAt      string `json:"expire_time"`
}

type DeviceShareListResp struct {
	List []DeviceShareItem `json:"list"`
}

type DeviceShareDetailReq struct {
	ShareId int64 `form:"share_id"`
}

type DeviceShareQuitReq struct {
	ShareId int64  `json:"share_id,omitempty"`
	Sn      string `json:"sn,omitempty"`
}

type DeviceShareRevokeReq struct {
	ShareId int64 `json:"share_id"`
}

type FamilyCreateReq struct {
	Name string `json:"name,optional"`
}

type FamilyInfoResp struct {
	FamilyId    int64  `json:"family_id"`
	Name        string `json:"name"`
	OwnerUserId int64  `json:"owner_user_id"`
	CurrentRole string `json:"current_role"`
	MemberCount int    `json:"member_count"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type FamilyMemberAcceptReq struct {
	InviteCode string `json:"invite_code"`
}

type FamilyMemberInviteReq struct {
	TargetUserId  int64  `json:"target_user_id,optional"`
	TargetAccount string `json:"target_account,optional"`
	Role          string `json:"role,optional"`
	Remark        string `json:"remark,optional"`
	ExpireAt      int64  `json:"expire_at,optional"`
}

type FamilyMemberInviteResp struct {
	FamilyId      int64  `json:"family_id"`
	InviteCode    string `json:"invite_code"`
	TargetUserId  int64  `json:"target_user_id,optional"`
	TargetAccount string `json:"target_account"`
	Role          string `json:"role"`
	Status        string `json:"status"`
	ExpireAt      int64  `json:"expire_at,optional"`
}

type FamilyMemberItem struct {
	UserId    int64  `json:"user_id"`
	Nickname  string `json:"nickname"`
	Email     string `json:"email,optional"`
	Mobile    string `json:"mobile,optional"`
	Role      string `json:"role"`
	Status    int32  `json:"status"`
	JoinedAt  int64  `json:"joined_at"`
	InvitedBy int64  `json:"invited_by"`
}

type FamilyMemberListResp struct {
	Family FamilyInfoResp     `json:"family"`
	List   []FamilyMemberItem `json:"list"`
}

type FamilyMemberRemoveReq struct {
	UserId int64 `json:"user_id"`
}

type FamilyMemberRoleUpdateReq struct {
	UserId int64  `json:"user_id"`
	Role   string `json:"role"`
}

type GetAccountCancellationConfirmResp struct {
	Title        string   `json:"title"`
	Consequences []string `json:"consequences"`
}

type GetAccountCancellationStatusResp struct {
	Phase        string `json:"phase"`
	CoolingEndAt int64  `json:"cooling_end_at,optional"`
}

type ListUserDevicesReq struct {
	DeviceName  string `form:"device_name,optional"`
	DeviceSn    string `form:"device_sn,optional"`
	DeviceModel string `form:"device_model,optional"`
	Page        int    `form:"page,optional"`
	PageSize    int    `form:"page_size,optional"`
}

type ListUserDevicesResp struct {
	Total int              `json:"total"`
	List  []UserDeviceItem `json:"list"`
}

type LoginReq struct {
	Email    string `json:"email,optional"`
	Mobile   string `json:"mobile,optional"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserId       int64  `json:"user_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type LogoutResp struct {
	Message string `json:"message"`
}

type OAuthCallbackReq struct {
	Code  string `form:"code"`
	State string `form:"state,optional"`
}

type OAuthLoginResp struct {
	UserId       int64  `json:"user_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type RealNameAuditInfoResp struct {
	AuthRecordId     int64  `json:"auth_record_id"`
	AuthStatus       int32  `json:"auth_status"`
	RealNameMasked   string `json:"real_name_masked"`
	IdNumberLast4    string `json:"id_number_last4"`
	CertType         int32  `json:"cert_type"`
	IdCardFrontRef   string `json:"id_card_front_ref,optional"`
	IdCardBackRef    string `json:"id_card_back_ref,optional"`
	FaceDataRef      string `json:"face_data_ref,optional"`
	FailReason       string `json:"fail_reason,optional"`
	ReviewerNote     string `json:"reviewer_note,optional"`
	ThirdPartyFlowNo string `json:"third_party_flow_no,optional"`
	CreatedAt        int64  `json:"created_at"`
	ReviewedAt       int64  `json:"reviewed_at,optional"`
}

type RealNameStatusResp struct {
	RealNameStatus int32  `json:"real_name_status"`
	CertType       int32  `json:"cert_type"`
	SubStatus      string `json:"sub_status,optional"`
	Message        string `json:"message"`
	FailReason     string `json:"fail_reason,optional"`
	UpdatedAt      int64  `json:"updated_at"`
}

type RealNameSubmitReq struct {
	CertType          int16  `json:"cert_type"`
	RealName          string `json:"real_name"`
	IdNumber          string `json:"id_number"`
	IdPhotoBase64     string `json:"id_photo_base64,optional"`
	IdCardFrontBase64 string `json:"id_card_front_base64,optional"`
	IdCardBackBase64  string `json:"id_card_back_base64,optional"`
	FaceImageBase64   string `json:"face_image_base64,optional"`
	VerifyCode        string `json:"verify_code,optional"`
}

type RealNameSubmitResp struct {
	RealNameStatus int32  `json:"real_name_status"`
	Message        string `json:"message"`
	RejectReason   string `json:"reject_reason,optional"`
	AuthRecordId   int64  `json:"auth_record_id"`
}

type RealnameRebindReq struct {
	NewEmail      string `json:"new_email,optional"`
	NewMobile     string `json:"new_mobile,optional"`
	NewVerifyCode string `json:"new_verify_code"`
	Password      string `json:"password,optional"`
	RealName      string `json:"real_name"`
	IdNumber      string `json:"id_number"`
}

type RebindContactReq struct {
	OldEmail      string `json:"old_email,optional"`
	OldMobile     string `json:"old_mobile,optional"`
	OldVerifyCode string `json:"old_verify_code"`
	NewEmail      string `json:"new_email,optional"`
	NewMobile     string `json:"new_mobile,optional"`
}

type RebindContactResp struct {
	Message string `json:"message"`
}

type ResetPasswordResp struct {
	Message string `json:"message"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type RegisterReq struct {
	Email      string `json:"email,optional"`
	Mobile     string `json:"mobile,optional"`
	Password   string `json:"password"`
	VerifyCode string `json:"verify_code"`
	Nickname   string `json:"nickname,optional"`
	Avatar     string `json:"avatar,optional"`
}

type RegisterResp struct {
	UserId int64 `json:"user_id"`
}

type UserInfoResp struct {
	UserInfo UserInfo `json:"user_info"`
}

type ResetPasswordReq struct {
	Email              string `json:"email,optional"`
	Mobile             string `json:"mobile,optional"`
	VerifyCode         string `json:"verify_code"`
	NewPassword        string `json:"new_password"`
	NewPasswordConfirm string `json:"new_password_confirm"`
}

type SendVerifyCodeReq struct {
	Email  string `json:"email,optional"`
	Mobile string `json:"mobile,optional"`
	Scene  string `json:"scene,optional"`
}

type SendVerifyCodeResp struct {
	ExpireSeconds int `json:"expire_seconds"`
}

type UnbindUserDeviceResp struct {
	DeviceSn string `json:"device_sn"`
	UserId   int64  `json:"user_id"`
	Status   int64  `json:"status"`
}

type UpdateUserInfoReq struct {
	Username             string `json:"username,optional"`
	Nickname             string `json:"nickname,optional"`
	Avatar               string `json:"avatar,optional"`
	Birthday             string `json:"birthday,optional"`
	Gender               int    `json:"gender,optional"`
	RealName             string `json:"real_name,optional"`
	Constellation        string `json:"constellation,optional"`
	Age                  int    `json:"age,optional"`
	Signature            string `json:"signature,optional"`
	Bio                  string `json:"bio,optional"`
	BirthdayVisibility   int    `json:"birthday_visibility,optional"`
	GenderVisibility     int    `json:"gender_visibility,optional"`
	ProfileComplete      int    `json:"profile_complete,optional"`
	ProfileCompleteScore int    `json:"profile_complete_score,optional"`
	Hobbies              string `json:"hobbies,optional"`
	Location             string `json:"location,optional"`
	Language             string `json:"language,optional"`
	Timezone             string `json:"timezone,optional"`
}

type UserDeviceItem struct {
	DeviceSn        string `json:"device_sn"`
	DeviceName      string `json:"device_name"`
	DeviceModel     string `json:"device_model"`
	SystemVersion   string `json:"system_version"`
	BindTime        string `json:"bind_time"`
	AccessMode      string `json:"access_mode,optional"`
	Role            string `json:"role,optional"`
	PermissionLevel string `json:"permission_level,optional"`
	Permission      string `json:"permission,optional"`
	OwnerUserId     int64  `json:"owner_user_id,optional"`
	ShareId         int64  `json:"share_id,optional"`
	FamilyId        int64  `json:"family_id,optional"`
}

type UserInfo struct {
	UserId               int64  `json:"user_id"`
	Email                string `json:"email"`
	Mobile               string `json:"mobile"`
	Nickname             string `json:"nickname"`
	Avatar               string `json:"avatar"`
	Status               int32  `json:"status"`
	RealNameStatus       int32  `json:"real_name_status"`
	RealNameCertType     int32  `json:"real_name_cert_type,optional"`
	RealNameAt           int64  `json:"real_name_at,optional"`
	Constellation        string `json:"constellation,optional"`
	Age                  int    `json:"age,optional"`
	Signature            string `json:"signature,optional"`
	Bio                  string `json:"bio,optional"`
	BirthdayVisibility   int    `json:"birthday_visibility,optional"`
	GenderVisibility     int    `json:"gender_visibility,optional"`
	ProfileComplete      int    `json:"profile_complete,optional"`
	ProfileCompleteScore int    `json:"profile_complete_score,optional"`
	Hobbies              string `json:"hobbies,optional"`
	Location             string `json:"location,optional"`
}

type WithdrawAccountCancellationResp struct {
	Message           string `json:"message"`
	UserId            int64  `json:"user_id"`
	Status            string `json:"status"`
	WithdrawnAt       int64  `json:"withdrawn_at"`
	CoolingEndCleared bool   `json:"cooling_end_cleared"`
}

// ==================== 设备更新相关类型定义 ====================

// UpdateDeviceReq 对应：PUT /api/v1/user/device/update | /api/v1/user/device/upd（更新设备信息请求）
type UpdateDeviceReq struct {
	Sn         string `json:"sn"`                    // 设备序列号（必填）
	DeviceName string `json:"device_name,optional"`  // 设备别名/备注名（如"卧室音箱"，最多50字符）
	Location   string `json:"location,optional"`     // 设备位置（如"卧室"、"客厅"，最多100字符）
	GroupName  string `json:"group_name,optional"`   // 设备分组（如"家庭音响组"，最多100字符）
	Scene      string `json:"scene,optional"`        // 常用场景（如"晨间唤醒"、"睡前音乐"，最多200字符）
}

// UpdateDeviceResp 对应：PUT /api/v1/user/device/update | /api/v1/user/device/upd（更新设备信息响应）
type UpdateDeviceResp struct {
	Sn         string `json:"sn"`          // 设备序列号
	DeviceName string `json:"device_name"` // 更新后的设备别名/备注名
	Location   string `json:"location"`    // 更新后的位置
	GroupName  string `json:"group_name"`  // 更新后的分组
	Scene      string `json:"scene"`       // 更新后的场景
	UpdatedAt  string `json:"updated_at"`  // 更新时间
	Message    string `json:"message,omitempty"`
}
