// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
//
// validate 标签为手工维护：goctl 重新生成后请合并回对应字段。

package types

type BindContactReq struct {
	Email      string `json:"email,optional" validate:"omitempty,email,excluded_with=Mobile,required_without=Mobile"`
	Mobile     string `json:"mobile,optional" validate:"omitempty,mobile,excluded_with=Email,required_without=Email"`
	VerifyCode string `json:"verify_code" validate:"omitempty,len=6,numeric"`
	// 换绑场景字段：仅用于识别误调 /bind 的请求体（首次绑定应使用 mobile/email + verify_code）。
	OldMobile     string `json:"old_mobile,optional"`
	OldEmail      string `json:"old_email,optional"`
	OldVerifyCode string `json:"old_verify_code,optional"`
	NewMobile     string `json:"new_mobile,optional"`
	NewEmail      string `json:"new_email,optional"`
	NewVerifyCode string `json:"new_verify_code,optional"`
}

type ChangePasswordReq struct {
	OldPassword        string `json:"old_password" validate:"required"`
	NewPassword        string `json:"new_password" validate:"required,password,eqfield=NewPasswordConfirm"`
	NewPasswordConfirm string `json:"new_password_confirm" validate:"required"`
}

// LoginReq 统一登录：优先填 account（邮箱或手机）；兼容旧字段 email/mobile。
// 凭证二选一：password（密码登录）或 verify_code（验证码登录，须先发 scene=login 验证码；新用户静默注册无密码）。
type LoginReq struct {
	Account    string `json:"account,optional"`
	Email      string `json:"email,optional"`
	Mobile     string `json:"mobile,optional"`
	Password   string `json:"password,optional"`
	VerifyCode string `json:"verify_code,optional"`
	Platform   string `json:"platform,optional" validate:"omitempty,oneof=web ios android"`
	InviteCode string `json:"invite_code,optional" validate:"omitempty,max=32"`
	DeviceID   string `json:"device_id,optional" validate:"omitempty,max=128"`
}

type LoginResp struct {
	UserId       int64  `json:"user_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

// LogoutResp 登出结果占位。
type LogoutResp struct {
	Message string `json:"message"`
}

// LoginSessionItem 登录会话列表项（session_id 为服务端派生 ID，非原始 refresh_token）。
type LoginSessionItem struct {
	SessionId  string `json:"session_id"`
	DeviceId   string `json:"device_id,optional"`
	DeviceName string `json:"device_name,optional"`
	Platform   string `json:"platform,optional"`
	Ip         string `json:"ip,optional"`
	UserAgent  string `json:"user_agent,optional"`
	CreatedAt  int64  `json:"created_at"`
	LastSeenAt int64  `json:"last_seen_at"`
	Current    bool   `json:"current"`
}

// ListLoginSessionsResp GET 登录会话列表。
type ListLoginSessionsResp struct {
	List []LoginSessionItem `json:"list"`
}

// KickLoginSessionReq 吊销指定会话（body 传 session_id，与列表返回一致）。
type KickLoginSessionReq struct {
	SessionId string `json:"session_id" validate:"required"`
}

// KickLoginSessionResp 吊销结果。
type KickLoginSessionResp struct {
	Ok bool `json:"ok"`
}

type OAuthCallbackReq struct {
	Code  string `form:"code" validate:"required"`
	State string `form:"state,optional" validate:"omitempty,max=512"`
}

type OAuthLoginResp struct {
	UserId       int64  `json:"user_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type RealnameRebindReq struct {
	NewEmail      string `json:"new_email,optional" validate:"omitempty,email,excluded_with=NewMobile,required_without=NewMobile"`
	NewMobile     string `json:"new_mobile,optional" validate:"omitempty,mobile,excluded_with=NewEmail,required_without=NewEmail"`
	NewVerifyCode string `json:"new_verify_code" validate:"required,len=6,numeric"`
	Password      string `json:"password,optional"`
	RealName      string `json:"real_name" validate:"required,min=2,max=50"`
	IdNumber      string `json:"id_number" validate:"required,idcard"`
}

type RebindContactReq struct {
	OldEmail      string `json:"old_email,optional" validate:"omitempty,email,excluded_with=OldMobile,required_without=OldMobile"`
	OldMobile     string `json:"old_mobile,optional" validate:"omitempty,mobile,excluded_with=OldEmail,required_without=OldEmail"`
	OldVerifyCode string `json:"old_verify_code" validate:"required,len=6,numeric"`
	NewEmail      string `json:"new_email,optional" validate:"omitempty,email,excluded_with=NewMobile,required_without=NewMobile"`
	NewMobile     string `json:"new_mobile,optional" validate:"omitempty,mobile,excluded_with=NewEmail,required_without=NewEmail"`
	NewVerifyCode string `json:"new_verify_code" validate:"required,len=6,numeric"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token" validate:"required"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type RegisterReq struct {
	Email      string `json:"email,optional" validate:"omitempty,email,excluded_with=Mobile,required_without=Mobile"`
	Mobile     string `json:"mobile,optional" validate:"omitempty,mobile,excluded_with=Email,required_without=Email"`
	Password   string `json:"password" validate:"required,password"`
	VerifyCode string `json:"verify_code" validate:"required,len=6,numeric"`
	Nickname   string `json:"nickname,optional" validate:"omitempty,max=100"`
	Avatar     string `json:"avatar,optional" validate:"omitempty,max=500"`
}

type RegisterResp struct {
	UserId int64 `json:"user_id"`
}

type ResetPasswordReq struct {
	Email              string `json:"email,optional" validate:"omitempty,email,excluded_with=Mobile,required_without=Mobile"`
	Mobile             string `json:"mobile,optional" validate:"omitempty,mobile,excluded_with=Email,required_without=Email"`
	VerifyCode         string `json:"verify_code" validate:"required,len=6,numeric"`
	NewPassword        string `json:"new_password" validate:"required,password,eqfield=NewPasswordConfirm"`
	NewPasswordConfirm string `json:"new_password_confirm" validate:"required"`
}

type SendVerifyCodeReq struct {
	Email  string `json:"email,optional" validate:"omitempty,email,excluded_with=Mobile,required_without=Mobile"`
	Mobile string `json:"mobile,optional" validate:"omitempty,mobile,excluded_with=Email,required_without=Email"`
	Scene  string `json:"scene,optional" validate:"omitempty,oneof=register reset bind login"`
}

type SendVerifyCodeResp struct {
	ExpireSeconds int `json:"expire_seconds"`
}

type UpdateUserInfoReq struct {
	Nickname string `json:"nickname,optional" validate:"omitempty,max=100"`
	Avatar   string `json:"avatar,optional" validate:"omitempty,max=500"`
	// 资料扩展（可选；与 migrations/025 对齐）
	// Birthday 用于推导 Age/Constellation（yyyy-MM-dd）。存库字段 users.birthday DATE。
	Birthday string `json:"birthday,optional" validate:"omitempty"`
	// Gender 用于存库（0=未知 1=男 2=女），users.gender SMALLINT。
	Gender               *int16 `json:"gender,optional" validate:"omitempty,min=0,max=2"`
	Constellation        string `json:"constellation,optional" validate:"omitempty,max=10"`
	Age                  *int16 `json:"age,optional" validate:"omitempty,min=0,max=150"`
	Signature            string `json:"signature,optional" validate:"omitempty,max=255"`
	Bio                  string `json:"bio,optional" validate:"omitempty,max=1000"`
	BirthdayVisibility   *int16 `json:"birthday_visibility,optional" validate:"omitempty,min=0,max=2"`
	GenderVisibility     *int16 `json:"gender_visibility,optional" validate:"omitempty,min=0,max=2"`
	ProfileComplete      *int16 `json:"profile_complete,optional" validate:"omitempty,oneof=0 1"`
	ProfileCompleteScore *int16 `json:"profile_complete_score,optional" validate:"omitempty,min=0,max=100"`
	Hobbies              string `json:"hobbies,optional" validate:"omitempty,max=255"`
	Location             string `json:"location,optional" validate:"omitempty,max=100"`
}

type UserInfo struct {
	UserId           int64  `json:"user_id"`
	Email            string `json:"email"`
	Mobile           string `json:"mobile"`
	Nickname         string `json:"nickname"`
	Avatar           string `json:"avatar"`
	Status           int32  `json:"status"`
	RealNameStatus   int32  `json:"real_name_status"`
	RealNameCertType int32  `json:"real_name_cert_type,optional"`
	RealNameAt       int64  `json:"real_name_at,optional"` // 通过时间 Unix 秒，0 表示无
	// 资料扩展（可选展示）
	Constellation        string `json:"constellation,omitempty"`
	Age                  int32  `json:"age,omitempty"`
	Signature            string `json:"signature,omitempty"`
	Bio                  string `json:"bio,omitempty"`
	BirthdayVisibility   int32  `json:"birthday_visibility,omitempty"`
	GenderVisibility     int32  `json:"gender_visibility,omitempty"`
	ProfileComplete      int32  `json:"profile_complete"`
	ProfileCompleteScore int32  `json:"profile_complete_score"`
	Hobbies              string `json:"hobbies,omitempty"`
	Location             string `json:"location,omitempty"`
}

// RealNameSubmitReq 提交实名（个人身份证 / 企业统一社会信用代码）。
type RealNameSubmitReq struct {
	CertType          int16  `json:"cert_type" validate:"required,min=1,max=2"`
	RealName          string `json:"real_name" validate:"required,min=2,max=50"`
	IdNumber          string `json:"id_number" validate:"required"`
	IdPhotoBase64     string `json:"id_photo_base64,optional"`      // 兼容旧版，等同人像面
	IdCardFrontBase64 string `json:"id_card_front_base64,optional"` // 人像面；可与 IdPhotoBase64 二选一
	IdCardBackBase64  string `json:"id_card_back_base64,optional"`  // 国徽面（个人必填）
	FaceImageBase64   string `json:"face_image_base64,optional"`    // 人脸/活体（个人默认必填，见配置 SkipFaceForPersonal）
	VerifyCode        string `json:"verify_code,optional"`
}

type RealNameSubmitResp struct {
	RealNameStatus int32  `json:"real_name_status"`
	Message        string `json:"message"`
	RejectReason   string `json:"reject_reason,optional"` // 三方/系统核验失败时返回原因
	AuthRecordId   int64  `json:"auth_record_id"`
}

type RealNameStatusResp struct {
	RealNameStatus int32  `json:"real_name_status"`
	CertType       int32  `json:"cert_type"`
	SubStatus      string `json:"sub_status,optional"`
	Message        string `json:"message"`
	FailReason     string `json:"fail_reason,optional"`
	UpdatedAt      int64  `json:"updated_at"`
	// 脱敏信息
	RealNameMasked string `json:"real_name_masked,optional"`
	IdNumberMasked string `json:"id_number_masked,optional"`
	SubmittedAt    int64  `json:"submitted_at,optional"`
	AuditedAt      int64  `json:"audited_at,optional"`
}

type RealNameAuditInfoResp struct {
	AuthRecordId     int64  `json:"auth_record_id"`
	AuthStatus       int32  `json:"auth_status"`
	RealNameMasked   string `json:"real_name_masked"`
	IdNumberLast4    string `json:"id_number_last4"`
	CertType         int32  `json:"cert_type"`
	IdCardFrontRef   string `json:"id_card_front_ref,optional"`
	IdCardBackRef    string `json:"id_card_back_ref,optional"`
	FaceDataRef      string `json:"face_data_ref,optional"`
	FailReason       string `json:"fail_reason,optional"`
	ReviewerNote     string `json:"reviewer_note,optional"` // 人工驳回原因
	ThirdPartyFlowNo string `json:"third_party_flow_no,optional"`
	CreatedAt        int64  `json:"created_at"`
	ReviewedAt       int64  `json:"reviewed_at,optional"`
}

type ApplyAccountCancellationReq struct {
	Password     string `json:"password,optional"`
	Reason       string `json:"reason,optional"`
	AgreementAck bool   `json:"agreement_ack"`
}

type ApplyAccountCancellationResp struct {
	CoolingEndAt int64 `json:"cooling_end_at"`
}

type WithdrawAccountCancellationResp struct {
	Message           string `json:"message"`
	UserId            int64  `json:"user_id"`
	Status            string `json:"status"`              // withdrawn：已成功撤销冷静期申请
	WithdrawnAt       int64  `json:"withdrawn_at"`        // 服务端完成撤销事务的 Unix 秒
	CoolingEndCleared bool   `json:"cooling_end_cleared"` // users.cancellation_cooling_until 已清空
}

type GetAccountCancellationStatusResp struct {
	Phase        string `json:"phase"`
	CoolingEndAt int64  `json:"cooling_end_at,optional"`
}

type GetAccountCancellationConfirmResp struct {
	Title        string   `json:"title"`
	Consequences []string `json:"consequences"`
}

// MemberBenefit 会员权益信息（供 App 展示与前端权限控制）。
type MemberBenefit struct {
	BenefitCode string `json:"benefit_code"`
	BenefitName string `json:"benefit_name"`
	Description string `json:"description,optional"`
}

// CheckUserBenefitReq 用户权益校验请求。
type CheckUserBenefitReq struct {
	Mode        string  `json:"mode,optional"`         // 校验模式：membership（会员权益）或 quota（额度）
	BenefitCode string  `json:"benefit_code,optional"` // 权益标识（如 content_vip、high_quality）
	FeatureKey  string  `json:"feature_key,optional"`  // 功能 key（额度模式必填）
	Delta       float64 `json:"delta,optional"`        // 消耗/增加额度
}

// CheckUserBenefitResp 用户权益校验响应。
type CheckUserBenefitResp struct {
	UserId             int64   `json:"user_id"`
	Mode               string  `json:"mode,omitempty"`
	BenefitCode        string  `json:"benefit_code,omitempty"`
	FeatureKey         string  `json:"feature_key,omitempty"`
	HasPermission      bool    `json:"has_permission"`
	Reason             string  `json:"reason"`
	LevelCode          string  `json:"level_code,omitempty"`
	ExpireAt           int64   `json:"expire_at,omitempty"`
	IsPermanent        bool    `json:"is_permanent,omitempty"`
	SubscriptionActive bool    `json:"subscription_active,omitempty"`
	Remaining          float64 `json:"remaining,omitempty"`
}

// CheckUserBenefitBatchReq 批量用户权益校验请求。
type CheckUserBenefitBatchReq struct {
	Items []CheckUserBenefitReq `json:"items" validate:"required,dive"`
}

// CheckUserBenefitBatchResp 批量用户权益校验响应。
type CheckUserBenefitBatchResp struct {
	Results []CheckUserBenefitResp `json:"results"`
}

// UserMemberBenefitsResp 当前登录用户会员权益响应（仅本人）。
type UserMemberBenefitsResp struct {
	UserId             int64           `json:"user_id"`
	LevelCode          string          `json:"level_code"`
	LevelName          string          `json:"level_name"`
	LevelSort          int32           `json:"level_sort"`
	ExpireAt           int64           `json:"expire_at,optional"`
	IsPermanent        bool            `json:"is_permanent"`
	RecordExpireAt     int64           `json:"record_expire_at,optional"`
	SubscriptionActive bool            `json:"subscription_active"`
	IsExpired          bool            `json:"is_expired"` // 档案到期日已过期且非永久
	RegisterType       string          `json:"register_type,optional"`
	MemberSince        int64           `json:"member_since,optional"`
	Benefits           []MemberBenefit `json:"benefits"`
}

// CreateMemberOrderReq 会员预下单。
// PackageCode：member_package 上架 SKU（如 vip_monthly），非 member_level 的 level_code。
// PayType：1 微信、2 支付宝、3 余额；合法范围 1–3。
type CreateMemberOrderReq struct {
	PackageCode string `json:"package_code" validate:"required"` // 须命中 member_package 且 status=1
	PayType     int64  `json:"pay_type" validate:"required"`     // 1–3
}

// CreateMemberOrderResp 预下单结果。
type CreateMemberOrderResp struct {
	OrderNo            string         `json:"order_no"`
	AmountCent         int64          `json:"amount_cent"`
	AmountYuan         string         `json:"amount_yuan"`
	OriginalAmountCent int64          `json:"original_amount_cent"`
	DiscountCent       int64          `json:"discount_cent"`
	BizScene           string         `json:"biz_scene"`
	PackageName        string         `json:"package_name"`
	PackageCode        string         `json:"package_code"`
	DurationDays       int64          `json:"duration_days"`
	PreviewExpireAt    int64          `json:"preview_expire_at"`
	PayType            int64          `json:"pay_type"`
	PayParams          map[string]any `json:"pay_params"`
}

// PayMemberOrderReq 发起支付（微信/支付宝预下单或余额扣款）。
type PayMemberOrderReq struct {
	OrderNo   string            `json:"order_no" validate:"required"`
	PayParams *PayMemberPayArgs `json:"pay_params,optional"`
}

// PayMemberPayArgs 支付调起参数（开发阶段可启用 mock 直接履约）。
type PayMemberPayArgs struct {
	Mock bool `json:"mock,optional"`
}

// PayMemberOrderResp 调起支付参数或余额支付结果。
type PayMemberOrderResp struct {
	OrderNo   string         `json:"order_no"`
	PayType   int64          `json:"pay_type"`
	PayParams map[string]any `json:"pay_params"`
}

// MockPayMemberOrderReq 模拟支付请求（开发/测试环境使用）。
type MockPayMemberOrderReq struct {
	OrderNo string `json:"order_no" validate:"required"`
}

// MockPayMemberOrderResp 模拟支付响应。
type MockPayMemberOrderResp struct {
	OrderNo    string      `json:"order_no"`
	Success    bool        `json:"success"`
	Message    string      `json:"message"`
	PayType    int64       `json:"pay_type"`
	AmountCent int64       `json:"amount_cent"`
	MemberInfo *MemberInfo `json:"member_info,optional"`
}

// GetUserMemberBenefitsReq 获取用户会员权益请求。
type GetUserMemberBenefitsReq struct {
}

// GetUserMemberBenefitsResp 获取用户会员权益响应。
type GetUserMemberBenefitsResp struct {
	MemberLevel          int64            `json:"member_level"`
	LevelName            string           `json:"level_name"`
	Status               int64            `json:"status"`
	IsValid              bool             `json:"is_valid"`
	SubscriptionPhase    string           `json:"subscription_phase"` // none | active | cancel_pending | expired
	CancelPending        bool             `json:"cancel_pending"`
	AutoRenew            bool             `json:"auto_renew"`
	AutoRenewPackageCode string           `json:"auto_renew_package_code,optional"`
	AutoRenewPayType     int64            `json:"auto_renew_pay_type,optional"`
	AutoRenewUpdatedAt   int64            `json:"auto_renew_updated_at,optional"`
	BenefitList          []*MemberBenefit `json:"benefit_list"`
}

// GetUserMemberInfoReq 获取用户会员信息请求。
type GetUserMemberInfoReq struct {
}

// GetUserMemberInfoResp 获取用户会员信息响应。
type GetUserMemberInfoResp struct {
	UserID               int64    `json:"user_id"`
	MemberLevel          int64    `json:"member_level"`
	LevelName            string   `json:"level_name"`
	Status               int64    `json:"status"`
	ExpireTime           int64    `json:"expire_time"`
	IsExpire             bool     `json:"is_expire"`
	SubscriptionPhase    string   `json:"subscription_phase"`
	CancelPending        bool     `json:"cancel_pending"`
	AutoRenew            bool     `json:"auto_renew"`
	AutoRenewPackageCode string   `json:"auto_renew_package_code,optional"`
	AutoRenewPayType     int64    `json:"auto_renew_pay_type,optional"`
	AutoRenewUpdatedAt   int64    `json:"auto_renew_updated_at,optional"`
	BenefitList          []string `json:"benefit_list"`
	CreateTime           int64    `json:"create_time"`
	RemainingDays        int64    `json:"remaining_days"`
}

// MemberAutoRenewInfoResp 当前自动续费意向（占位，非真实代扣）。
type MemberAutoRenewInfoResp struct {
	AutoRenew            bool   `json:"auto_renew"`
	AutoRenewPackageCode string `json:"auto_renew_package_code,optional"`
	AutoRenewPayType     int64  `json:"auto_renew_pay_type,optional"`
	AutoRenewUpdatedAt   int64  `json:"auto_renew_updated_at,optional"`
}

// SetMemberAutoRenewReq 开启/关闭自动续费意向。
type SetMemberAutoRenewReq struct {
	Enabled     bool   `json:"enabled"`
	PackageCode string `json:"package_code,optional"`
	PayType     int64  `json:"pay_type,optional"`
}

// MemberUnsubscribeReq 主动退订（当前周期内仍有效，到期后终止）。
type MemberUnsubscribeReq struct {
	ReasonCode string `json:"reason_code" validate:"required"`
	Feedback   string `json:"feedback,optional"`
}

// MemberUnsubscribeResp 退订受理结果。
type MemberUnsubscribeResp struct {
	Success bool `json:"success"`
}

// MemberUnsubscribeRevokeReq 撤销退订标记（不自动恢复自动续费）。
type MemberUnsubscribeRevokeReq struct {
}

// MemberInfo 会员信息。
type MemberInfo struct {
	LevelCode   string `json:"level_code"`
	LevelName   string `json:"level_name"`
	ExpireAt    int64  `json:"expire_at"`
	IsPermanent bool   `json:"is_permanent"`
	Status      int64  `json:"status"`
}

// MemberPayCallbackReq 支付渠道回调（JSON 验签）。
// 支持微信/支付宝/模拟支付的异步回调通知。
type MemberPayCallbackReq struct {
	OrderNo    string `json:"order_no"`             // 平台订单号
	TradeNo    string `json:"trade_no"`             // 第三方支付平台交易号
	Sign       string `json:"sign"`                 // 回调签名
	AmountCent int64  `json:"amount_cent,optional"` // 支付金额（分），可选
	PayTime    int64  `json:"pay_time,optional"`    // 支付时间戳，可选
	PayChannel string `json:"pay_channel,optional"` // 支付渠道（wechat/alipay/mock），可选
	RawNotify  string `json:"raw_notify,optional"`  // 原始回调数据（用于审计），可选
}

// GetDownloadURLReq 获取内容下载地址请求。
type GetDownloadURLReq struct {
	ContentID int64 `json:"content_id" validate:"required"`
}

// GetDownloadURLResp 获取内容下载地址响应。
type GetDownloadURLResp struct {
	DownloadURL string `json:"download_url"`
	FileName    string `json:"file_name"`
	ContentType string `json:"content_type"`
}

// DownloadRecordItem 下载记录项。
type DownloadRecordItem struct {
	ID             int64  `json:"id"`
	ContentID      int64  `json:"content_id"`
	FileID         int64  `json:"file_id"`
	FileName       string `json:"file_name"`
	FileSize       int64  `json:"file_size"`
	DownloadedSize int64  `json:"downloaded_size"`
	Status         string `json:"status"`
	Progress       int    `json:"progress"`
	LocalPath      string `json:"local_path"`
	CreateTime     string `json:"create_time"`
	UpdateTime     string `json:"update_time"`
}

// ListDownloadRecordsReq 查询下载记录列表请求。
type ListDownloadRecordsReq struct {
	Status   string `form:"status,optional"`
	Keyword  string `form:"keyword,optional"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
}

// ListDownloadRecordsResp 查询下载记录列表响应。
type ListDownloadRecordsResp struct {
	List     []*DownloadRecordItem `json:"list"`
	Total    int64                 `json:"total"`
	Page     int                   `json:"page"`
	PageSize int                   `json:"page_size"`
}

// CreateDownloadRecordReq 创建下载记录请求。
type CreateDownloadRecordReq struct {
	ContentID int64  `json:"content_id" validate:"required"`
	FileName  string `json:"file_name" validate:"required"`
	FileSize  int64  `json:"file_size" validate:"required"`
}

// CreateDownloadRecordResp 创建下载记录响应。
type CreateDownloadRecordResp struct {
	RecordID    int64  `json:"record_id"`
	DownloadURL string `json:"download_url"`
	RangeStart  int64  `json:"range_start"`
}

// UpdateDownloadProgressReq 更新下载进度请求。
type UpdateDownloadProgressReq struct {
	RecordID       int64 `json:"record_id" validate:"required"`
	DownloadedSize int64 `json:"downloaded_size" validate:"required"`
}

// UpdateDownloadProgressResp 更新下载进度响应。
type UpdateDownloadProgressResp struct {
	Success bool `json:"success"`
}

// CompleteDownloadReq 完成下载请求。
type CompleteDownloadReq struct {
	RecordID  int64  `json:"record_id" validate:"required"`
	LocalPath string `json:"local_path" validate:"required"`
}

// CompleteDownloadResp 完成下载响应。
type CompleteDownloadResp struct {
	Success bool `json:"success"`
}

// ResumeDownloadReq 继续下载请求（断点续传）。
type ResumeDownloadReq struct {
	RecordID int64 `json:"record_id" validate:"required"`
}

// ResumeDownloadResp 继续下载响应。
type ResumeDownloadResp struct {
	DownloadURL    string `json:"download_url"`
	RangeStart     int64  `json:"range_start"`
	FileName       string `json:"file_name"`
	FileSize       int64  `json:"file_size"`
	DownloadedSize int64  `json:"downloaded_size"`
}

// DeleteDownloadRecordReq 删除下载记录请求（单条删除）。
type DeleteDownloadRecordReq struct {
	RecordID int64 `json:"record_id" validate:"required"`
}

// DeleteDownloadRecordResp 删除下载记录响应。
type DeleteDownloadRecordResp struct {
	Success bool `json:"success"`
}

// SyncDeleteDownloadRecordsReq 批量同步删除下载记录请求。
type SyncDeleteDownloadRecordsReq struct {
	FileIDs []int64 `json:"file_ids" validate:"required"`
}

// SyncDeleteDownloadRecordsResp 批量同步删除下载记录响应。
type SyncDeleteDownloadRecordsResp struct {
	DeletedCount int64 `json:"deleted_count"`
}

type FamilyCreateReq struct {
	Name string `json:"name,optional" validate:"omitempty,max=64"`
}

type FamilyInfoResp struct {
	FamilyId    int64  `json:"family_id"`
	Name        string `json:"name"`
	OwnerUserId int64  `json:"owner_user_id"`
	CurrentRole string `json:"current_role"`
	MemberCount int    `json:"member_count"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type FamilyMemberInviteReq struct {
	TargetUserId  int64  `json:"target_user_id,optional"`
	TargetAccount string `json:"target_account,optional" validate:"omitempty,max=128"`
	Role          string `json:"role,optional" validate:"omitempty,oneof=super_admin member"`
	Remark        string `json:"remark,optional" validate:"omitempty,max=255"`
	ExpireAt      int64  `json:"expire_at,optional"`
}

type FamilyMemberInviteResp struct {
	FamilyId      int64  `json:"family_id"`
	InviteCode    string `json:"invite_code"`
	TargetUserId  int64  `json:"target_user_id,optional"`
	TargetAccount string `json:"target_account"`
	Role          string `json:"role"`
	Status        string `json:"status"`
	ExpireAt      int64  `json:"expire_at,optional"`
}

type FamilyMemberAcceptReq struct {
	InviteCode string `json:"invite_code" validate:"required,max=64"`
}

type FamilyMemberRemoveReq struct {
	UserId int64 `json:"user_id" validate:"required,min=1"`
}

type FamilyMemberRoleUpdateReq struct {
	UserId int64  `json:"user_id" validate:"required,min=1"`
	Role   string `json:"role" validate:"required,oneof=super_admin member"`
}

type FamilyMemberItem struct {
	UserId    int64  `json:"user_id"`
	Nickname  string `json:"nickname"`
	Email     string `json:"email,omitempty"`
	Mobile    string `json:"mobile,omitempty"`
	Role      string `json:"role"`
	Status    int16  `json:"status"`
	JoinedAt  int64  `json:"joined_at"`
	InvitedBy int64  `json:"invited_by"`
}

type FamilyMemberListResp struct {
	Family FamilyInfoResp     `json:"family"`
	List   []FamilyMemberItem `json:"list"`
}

type DeviceShareCreateReq struct {
	DeviceSn        string `json:"device_sn" validate:"required,max=64"`
	TargetUserId    int64  `json:"target_user_id,optional"`
	TargetAccount   string `json:"target_account,optional" validate:"omitempty,max=128"`
	ShareType       string `json:"share_type,optional" validate:"omitempty,oneof=permanent temporary time_window"`
	PermissionLevel string `json:"permission_level,optional" validate:"omitempty,oneof=full_control partial_control view_only"`
	Permission      string `json:"permission,optional"`
	StartAt         int64  `json:"start_at,optional"`
	EndAt           int64  `json:"end_at,optional"`
	Remark          string `json:"remark,optional" validate:"omitempty,max=255"`
}

type DeviceShareAcceptReq struct {
	InviteCode string `json:"invite_code" validate:"required,max=64"`
}

type DeviceShareRevokeReq struct {
	ShareId int64 `json:"share_id" validate:"required,min=1"`
}

type DeviceShareQuitReq struct {
	ShareId int64 `json:"share_id" validate:"required,min=1"`
}

type DeviceShareDetailReq struct {
	ShareId int64 `form:"share_id" validate:"required,min=1"`
}

type DeviceShareItem struct {
	ShareId         int64  `json:"share_id"`
	FamilyId        int64  `json:"family_id"`
	DeviceId        int64  `json:"device_id"`
	DeviceSn        string `json:"device_sn"`
	DeviceName      string `json:"device_name"`
	OwnerUserId     int64  `json:"owner_user_id"`
	OwnerNickname   string `json:"owner_nickname,omitempty"`
	SharedUserId    int64  `json:"shared_user_id"`
	SharedNickname  string `json:"shared_user_nickname,omitempty"`
	TargetAccount   string `json:"target_account,omitempty"`
	InviteCode      string `json:"invite_code,omitempty"`
	ShareType       string `json:"share_type"`
	PermissionLevel string `json:"permission_level"`
	Permission      string `json:"permission,omitempty"`
	Status          string `json:"status"`
	FamilyName      string `json:"family_name,omitempty"`
	StartAt         int64  `json:"start_at,optional"`
	EndAt           int64  `json:"end_at,optional"`
	CreatedAt       int64  `json:"created_at"`
	ConfirmedAt     int64  `json:"confirmed_at,optional"`
}

type DeviceShareListResp struct {
	List []DeviceShareItem `json:"list"`
}

// AdminMemberListReq GET /api/v1/user/admin/members 查询参数（均可选，AND 组合）
type AdminMemberListReq struct {
	Page         int    `form:"page,optional"`
	PageSize     int    `form:"page_size,optional"`
	UserID       int64  `form:"user_id,optional"`
	Nickname     string `form:"nickname,optional"`
	Mobile       string `form:"mobile,optional"`
	LevelCode    string `form:"level_code,optional"`
	MemberStatus int    `form:"member_status,optional"` // 0=不传 1=有效 2=已过期 3=未开通
	OpenedFrom   string `form:"opened_from,optional"`   // YYYY-MM-DD
	OpenedTo     string `form:"opened_to,optional"`
	ExpireFrom   string `form:"expire_from,optional"`
	ExpireTo     string `form:"expire_to,optional"`
}

// AdminMemberItem 后台会员列表行
type AdminMemberItem struct {
	UserID           int64  `json:"user_id"`
	Nickname         string `json:"nickname"`
	Mobile           string `json:"mobile"`
	LevelCode        string `json:"level_code"`
	LevelName        string `json:"level_name"`
	OpenedAt         string `json:"opened_at"`          // 开通时间 yyyy-MM-dd HH:mm:ss，无则 —
	ExpireAt         string `json:"expire_at"`          // 过期时间，永久/未开通用文案
	MemberStatus     int16  `json:"member_status"`      // 1 有效 2 过期 3 未开通
	MemberStatusText string `json:"member_status_text"` // 有效 / 已过期 / 未开通
}

// AdminMemberListResp 分页结果
type AdminMemberListResp struct {
	Total int64             `json:"total"`
	List  []AdminMemberItem `json:"list"`
}
