// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApplyAccountCancellationReq struct {
	Password     string `json:"password,optional"`
	Reason       string `json:"reason,optional"`
	AgreementAck bool   `json:"agreement_ack"`
}

type ApplyAccountCancellationResp struct {
	CoolingEndAt int64 `json:"cooling_end_at"`
}

type BindContactReq struct {
	Email         string `json:"email,optional"`
	Mobile        string `json:"mobile,optional"`
	VerifyCode    string `json:"verify_code,optional"`
	OldMobile     string `json:"old_mobile,optional"`
	OldEmail      string `json:"old_email,optional"`
	OldVerifyCode string `json:"old_verify_code,optional"`
	NewMobile     string `json:"new_mobile,optional"`
	NewEmail      string `json:"new_email,optional"`
	NewVerifyCode string `json:"new_verify_code,optional"`
}

type BindUserDeviceReq struct {
	DeviceSn      string `json:"device_sn"`
	DeviceName    string `json:"device_name,optional"`
	DeviceModel   string `json:"device_model,optional"`
	SystemVersion string `json:"system_version,optional"`
}

type BindUserDeviceResp struct {
	UserId     int64  `json:"user_id"`
	DeviceSn   string `json:"device_sn"`
	DeviceName string `json:"device_name"`
	BindTime   string `json:"bind_time"`
}

type ChangePasswordReq struct {
	OldPassword        string `json:"old_password"`
	NewPassword        string `json:"new_password"`
	NewPasswordConfirm string `json:"new_password_confirm"`
}

type CreateMemberOrderReq struct {
	PackageCode string `json:"package_code"` // 须与 public.member_package.package_code 一致且 status=1 上架
	PayType     int64  `json:"pay_type"`     // 1微信 2支付宝 3余额（须 1–3，见 create_member_order_logic 校验）
}

type CreateMemberOrderResp struct {
	OrderNo            string `json:"order_no"`
	AmountCent         int64  `json:"amount_cent"`
	AmountYuan         string `json:"amount_yuan"`
	OriginalAmountCent int64  `json:"original_amount_cent"`
	DiscountCent       int64  `json:"discount_cent"`
	BizScene           string `json:"biz_scene"`
	PackageName        string `json:"package_name"`
	PackageCode        string `json:"package_code"`
	DurationDays       int64  `json:"duration_days"`
	PreviewExpireAt    int64  `json:"preview_expire_at"`
	PayType            int64  `json:"pay_type"`
}

type DeviceShareAcceptReq struct {
	Sn string `json:"sn"`
}

type DeviceShareCreateReq struct {
	DeviceSn        string `json:"device_sn"`
	TargetUserId    int64  `json:"target_user_id,optional"`
	TargetAccount   string `json:"target_account,optional"`
	ShareType       string `json:"share_type,optional"`
	PermissionLevel string `json:"permission_level,optional"`
	Permission      string `json:"permission,optional"`
	StartAt         int64  `json:"start_at,optional"`
	EndAt           int64  `json:"end_at,optional"`
	Remark          string `json:"remark,optional"`
}

type DeviceShareDetailReq struct {
	ShareId int64 `form:"share_id"`
}

type DeviceShareItem struct {
	ShareId         int64  `json:"share_id"`
	FamilyId        int64  `json:"family_id"`
	DeviceId        int64  `json:"device_id"`
	DeviceSn        string `json:"device_sn"`
	DeviceName      string `json:"device_name"`
	OwnerUserId     int64  `json:"owner_user_id"`
	OwnerNickname   string `json:"owner_nickname,optional"`
	SharedUserId    int64  `json:"shared_user_id"`
	SharedNickname  string `json:"shared_user_nickname,optional"`
	TargetAccount   string `json:"target_account,optional"`
	InviteCode      string `json:"invite_code,optional"`
	ShareType       string `json:"share_type"`
	PermissionLevel string `json:"permission_level"`
	Permission      string `json:"permission,optional"`
	Status          string `json:"status"`
	FamilyName      string `json:"family_name,optional"`
	StartAt         int64  `json:"start_at,optional"`
	EndAt           int64  `json:"end_at,optional"`
	CreatedAt       int64  `json:"created_at"`
	ConfirmedAt     int64  `json:"confirmed_at,optional"`
}

type DeviceShareListResp struct {
	List []DeviceShareItem `json:"list"`
}

type DeviceShareQuitReq struct {
	Sn string `json:"sn"`
}

type DeviceShareRejectReq struct {
	Sn string `json:"sn"`
}

type DeviceShareRevokeReq struct {
	Sn string `json:"sn"`
}

type FamilyCreateReq struct {
	Name string `json:"name,optional"`
}

type FamilyInfoResp struct {
	FamilyId    int64  `json:"family_id"`
	Name        string `json:"name"`
	OwnerUserId int64  `json:"owner_user_id"`
	CurrentRole string `json:"current_role"`
	MemberCount int    `json:"member_count"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type FamilyMemberAcceptReq struct {
	InviteCode string `json:"invite_code"`
}

type FamilyMemberInviteReq struct {
	TargetUserId  int64  `json:"target_user_id,optional"`
	TargetAccount string `json:"target_account,optional"`
	Role          string `json:"role,optional"`
	Remark        string `json:"remark,optional"`
	ExpireAt      int64  `json:"expire_at,optional"`
}

type FamilyMemberInviteResp struct {
	FamilyId      int64  `json:"family_id"`
	InviteCode    string `json:"invite_code"`
	TargetUserId  int64  `json:"target_user_id,optional"`
	TargetAccount string `json:"target_account"`
	Role          string `json:"role"`
	Status        string `json:"status"`
	ExpireAt      int64  `json:"expire_at,optional"`
}

type FamilyMemberItem struct {
	UserId    int64  `json:"user_id"`
	Nickname  string `json:"nickname"`
	Email     string `json:"email,optional"`
	Mobile    string `json:"mobile,optional"`
	Role      string `json:"role"`
	Status    int32  `json:"status"`
	JoinedAt  int64  `json:"joined_at"`
	InvitedBy int64  `json:"invited_by"`
}

type FamilyMemberListResp struct {
	Family FamilyInfoResp     `json:"family"`
	List   []FamilyMemberItem `json:"list"`
}

type FamilyMemberRemoveReq struct {
	UserId int64 `json:"user_id"`
}

type FamilyMemberRoleUpdateReq struct {
	UserId int64  `json:"user_id"`
	Role   string `json:"role"`
}

type GetAccountCancellationConfirmResp struct {
	Title        string   `json:"title"`
	Consequences []string `json:"consequences"`
}

type GetAccountCancellationStatusResp struct {
	Phase        string `json:"phase"`
	CoolingEndAt int64  `json:"cooling_end_at,optional"`
}

type ListUserDevicesReq struct {
	DeviceName  string `form:"device_name,optional"`
	DeviceSn    string `form:"device_sn,optional"`
	DeviceModel string `form:"device_model,optional"`
	Page        int    `form:"page,optional"`
	PageSize    int    `form:"page_size,optional"`
}

type ListUserDevicesResp struct {
	Total int              `json:"total"`
	List  []UserDeviceItem `json:"list"`
}

type LoginReq struct {
	Email    string `json:"email,optional"`
	Mobile   string `json:"mobile,optional"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserId       int64  `json:"user_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type MemberAutoRenewInfoResp struct {
	AutoRenew            bool   `json:"auto_renew"`
	AutoRenewPackageCode string `json:"auto_renew_package_code,optional"`
	AutoRenewPayType     int64  `json:"auto_renew_pay_type,optional"`
	AutoRenewUpdatedAt   int64  `json:"auto_renew_updated_at,optional"`
}

type MemberBenefit struct {
	BenefitCode string `json:"benefit_code"`
	BenefitName string `json:"benefit_name"`
	Description string `json:"description,optional"`
}

type MemberPayCallbackReq struct {
	OrderNo string `json:"order_no"`
	TradeNo string `json:"trade_no"`
	Sign    string `json:"sign"`
}

type MemberUnsubscribeReq struct {
	ReasonCode string `json:"reason_code"` // price|features|low_usage|switch_platform|service|other
	Feedback   string `json:"feedback,optional"`
}

type MemberUnsubscribeResp struct {
	Success bool `json:"success"`
}

type MemberUnsubscribeRevokeReq struct {
}

type OAuthCallbackReq struct {
	Code  string `form:"code"`
	State string `form:"state,optional"`
}

type OAuthLoginResp struct {
	UserId       int64  `json:"user_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type PayMemberOrderReq struct {
	OrderNo string `json:"order_no"`
}

type PayMemberOrderResp struct {
	OrderNo string `json:"order_no"`
	PayType int64  `json:"pay_type"`
}

type RealNameAuditInfoResp struct {
	AuthRecordId     int64  `json:"auth_record_id"`
	AuthStatus       int32  `json:"auth_status"`
	RealNameMasked   string `json:"real_name_masked"`
	IdNumberLast4    string `json:"id_number_last4"`
	CertType         int32  `json:"cert_type"`
	IdCardFrontRef   string `json:"id_card_front_ref,optional"`
	IdCardBackRef    string `json:"id_card_back_ref,optional"`
	FaceDataRef      string `json:"face_data_ref,optional"`
	FailReason       string `json:"fail_reason,optional"`
	ReviewerNote     string `json:"reviewer_note,optional"`
	ThirdPartyFlowNo string `json:"third_party_flow_no,optional"`
	CreatedAt        int64  `json:"created_at"`
	ReviewedAt       int64  `json:"reviewed_at,optional"`
}

type RealNameStatusResp struct {
	RealNameStatus int32  `json:"real_name_status"`
	CertType       int32  `json:"cert_type"`
	SubStatus      string `json:"sub_status,optional"`
	Message        string `json:"message"`
	FailReason     string `json:"fail_reason,optional"`
	UpdatedAt      int64  `json:"updated_at"`
}

type RealNameSubmitReq struct {
	CertType          int16  `json:"cert_type"`
	RealName          string `json:"real_name"`
	IdNumber          string `json:"id_number"`
	IdPhotoBase64     string `json:"id_photo_base64,optional"`
	IdCardFrontBase64 string `json:"id_card_front_base64,optional"`
	IdCardBackBase64  string `json:"id_card_back_base64,optional"`
	FaceImageBase64   string `json:"face_image_base64,optional"`
	VerifyCode        string `json:"verify_code,optional"`
}

type RealNameSubmitResp struct {
	RealNameStatus int32  `json:"real_name_status"`
	Message        string `json:"message"`
	RejectReason   string `json:"reject_reason,optional"`
	AuthRecordId   int64  `json:"auth_record_id"`
}

type RealnameRebindReq struct {
	NewEmail      string `json:"new_email,optional"`
	NewMobile     string `json:"new_mobile,optional"`
	NewVerifyCode string `json:"new_verify_code"`
	Password      string `json:"password,optional"`
	RealName      string `json:"real_name"`
	IdNumber      string `json:"id_number"`
}

type RebindContactReq struct {
	OldEmail      string `json:"old_email,optional"`
	OldMobile     string `json:"old_mobile,optional"`
	OldVerifyCode string `json:"old_verify_code"`
	NewEmail      string `json:"new_email,optional"`
	NewMobile     string `json:"new_mobile,optional"`
	NewVerifyCode string `json:"new_verify_code"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type RegisterReq struct {
	Email      string `json:"email,optional"`
	Mobile     string `json:"mobile,optional"`
	Password   string `json:"password"`
	VerifyCode string `json:"verify_code"`
	Nickname   string `json:"nickname,optional"`
	Avatar     string `json:"avatar,optional"`
}

type RegisterResp struct {
	UserId int64 `json:"user_id"`
}

type ResetPasswordReq struct {
	Email              string `json:"email,optional"`
	Mobile             string `json:"mobile,optional"`
	VerifyCode         string `json:"verify_code"`
	NewPassword        string `json:"new_password"`
	NewPasswordConfirm string `json:"new_password_confirm"`
}

type SendVerifyCodeReq struct {
	Email  string `json:"email,optional"`
	Mobile string `json:"mobile,optional"`
	Scene  string `json:"scene,optional"`
}

type SendVerifyCodeResp struct {
	ExpireSeconds int `json:"expire_seconds"`
}

type SetMemberAutoRenewReq struct {
	Enabled     bool   `json:"enabled"`
	PackageCode string `json:"package_code,optional"`
	PayType     int64  `json:"pay_type,optional"`
}

type UnbindUserDeviceReq struct {
	DeviceSn string `json:"device_sn"`
}

type UnbindUserDeviceResp struct {
	DeviceSn string `json:"device_sn"`
	UserId   int64  `json:"user_id"`
	Status   int64  `json:"status"`
}

type UpdateUserInfoReq struct {
	Nickname             string `json:"nickname,optional"`
	Avatar               string `json:"avatar,optional"`
	Birthday             string `json:"birthday,optional"`
	Gender               int    `json:"gender,optional"`
	Constellation        string `json:"constellation,optional"`
	Age                  int    `json:"age,optional"`
	Signature            string `json:"signature,optional"`
	Bio                  string `json:"bio,optional"`
	BirthdayVisibility   int    `json:"birthday_visibility,optional"`
	GenderVisibility     int    `json:"gender_visibility,optional"`
	ProfileComplete      int    `json:"profile_complete,optional"`
	ProfileCompleteScore int    `json:"profile_complete_score,optional"`
	Hobbies              string `json:"hobbies,optional"`
	Location             string `json:"location,optional"`
}

type UserDeviceItem struct {
	DeviceSn        string `json:"device_sn"`
	DeviceName      string `json:"device_name"`
	DeviceModel     string `json:"device_model"`
	SystemVersion   string `json:"system_version"`
	BindTime        string `json:"bind_time"`
	AccessMode      string `json:"access_mode,optional"`
	Role            string `json:"role,optional"`
	PermissionLevel string `json:"permission_level,optional"`
	Permission      string `json:"permission,optional"`
	OwnerUserId     int64  `json:"owner_user_id,optional"`
	ShareId         int64  `json:"share_id,optional"`
	FamilyId        int64  `json:"family_id,optional"`
}

type UserInfo struct {
	UserId               int64  `json:"user_id"`
	Email                string `json:"email"`
	Mobile               string `json:"mobile"`
	Nickname             string `json:"nickname"`
	Avatar               string `json:"avatar"`
	Status               int32  `json:"status"`
	RealNameStatus       int32  `json:"real_name_status"`
	RealNameCertType     int32  `json:"real_name_cert_type,optional"`
	RealNameAt           int64  `json:"real_name_at,optional"`
	Constellation        string `json:"constellation,optional"`
	Age                  int    `json:"age,optional"`
	Signature            string `json:"signature,optional"`
	Bio                  string `json:"bio,optional"`
	BirthdayVisibility   int    `json:"birthday_visibility,optional"`
	GenderVisibility     int    `json:"gender_visibility,optional"`
	ProfileComplete      int    `json:"profile_complete,optional"`
	ProfileCompleteScore int    `json:"profile_complete_score,optional"`
	Hobbies              string `json:"hobbies,optional"`
	Location             string `json:"location,optional"`
}

type UserMemberBenefitsResp struct {
	UserId             int64           `json:"user_id"`
	LevelCode          string          `json:"level_code"`         // 当前生效等级（过期或无档会回落 ordinary）
	LevelName          string          `json:"level_name"`         // member_level.level_name
	LevelSort          int32           `json:"level_sort"`         // member_level.sort，越小越靠前，可作「几档」展示
	ExpireAt           int64           `json:"expire_at,optional"` // 当前生效权益的到期 Unix 秒；永久/普通无截止为 0
	IsPermanent        bool            `json:"is_permanent"`
	RecordExpireAt     int64           `json:"record_expire_at,optional"` // user_member 档案中的到期日（可能已过期）；无行为 0
	SubscriptionActive bool            `json:"subscription_active"`       // 库内会员行有效且未过期或为永久
	RegisterType       string          `json:"register_type,optional"`    // user_member.register_type：pay/gift/admin 等
	MemberSince        int64           `json:"member_since,optional"`     // user_member.created_at Unix 秒；无行为 0
	IsExpired          bool            `json:"is_expired"`                // 档案到期已过期且非永久
	Benefits           []MemberBenefit `json:"benefits"`
}

type WithdrawAccountCancellationResp struct {
	Message           string `json:"message"`
	UserId            int64  `json:"user_id"`
	Status            string `json:"status"`
	WithdrawnAt       int64  `json:"withdrawn_at"`
	CoolingEndCleared bool   `json:"cooling_end_cleared"`
}
