/* tslint:disable */
/* eslint-disable */
/**
 * 用户服务 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ApplyAccountCancellation200Response {
    'cooling_end_at'?: number;
}
export interface ApplyAccountCancellationRequest {
    'agreement_ack': boolean;
    'password'?: string;
    'reason'?: string;
}
export interface BindContact200Response {
    'avatar'?: string;
    'email'?: string;
    'mobile'?: string;
    'nickname'?: string;
    'real_name_at'?: number;
    'real_name_cert_type'?: number;
    'real_name_status'?: number;
    'status'?: number;
    'user_id'?: number;
}
export interface BindContactRequest {
    'email'?: string;
    'mobile'?: string;
    'verify_code': string;
}
export interface ChangePasswordRequest {
    'new_password': string;
    'new_password_confirm': string;
    'old_password': string;
}
export interface GetAccountCancellationConfirm200Response {
    'consequences'?: Array<string>;
    'title'?: string;
}
export interface GetAccountCancellationStatus200Response {
    'cooling_end_at'?: number;
    'phase'?: string;
}
export interface GetRealNameAuditInfo200Response {
    'auth_record_id'?: number;
    'auth_status'?: number;
    'cert_type'?: number;
    'created_at'?: number;
    'face_data_ref'?: string;
    'fail_reason'?: string;
    'id_card_back_ref'?: string;
    'id_card_front_ref'?: string;
    'id_number_last4'?: string;
    'real_name_masked'?: string;
    'reviewed_at'?: number;
    'reviewer_note'?: string;
    'third_party_flow_no'?: string;
}
export interface GetRealNameStatus200Response {
    'cert_type'?: number;
    'fail_reason'?: string;
    'message'?: string;
    'real_name_status'?: number;
    'sub_status'?: string;
    'updated_at'?: number;
}
export interface Login200Response {
    'access_token'?: string;
    'expires_in'?: number;
    'refresh_token'?: string;
    'user_id'?: number;
}
export interface LoginRequest {
    'email'?: string;
    'mobile'?: string;
    'password': string;
}
export interface RealnameRebindRequest {
    'id_number': string;
    'new_email'?: string;
    'new_mobile'?: string;
    'new_verify_code': string;
    'password'?: string;
    'real_name': string;
}
export interface RebindContactRequest {
    'new_email'?: string;
    'new_mobile'?: string;
    'new_verify_code': string;
    'old_email'?: string;
    'old_mobile'?: string;
    'old_verify_code': string;
}
export interface RefreshToken200Response {
    'access_token'?: string;
    'expires_in'?: number;
    'refresh_token'?: string;
}
export interface RefreshTokenRequest {
    'refresh_token': string;
}
export interface Register200Response {
    'user_id'?: number;
}
export interface RegisterRequest {
    'email'?: string;
    'mobile'?: string;
    'nickname'?: string;
    'password': string;
    'verify_code': string;
}
export interface ResetPasswordRequest {
    'email'?: string;
    'mobile'?: string;
    'new_password': string;
    'new_password_confirm': string;
    'verify_code': string;
}
export interface SendVerifyCode200Response {
    'expire_seconds'?: number;
}
export interface SendVerifyCodeRequest {
    'email'?: string;
    'mobile'?: string;
    'scene'?: string;
}
export interface SubmitRealName200Response {
    'auth_record_id'?: number;
    'message'?: string;
    'real_name_status'?: number;
    'reject_reason'?: string;
}
export interface SubmitRealNameRequest {
    'cert_type': number;
    'face_image_base64'?: string;
    'id_card_back_base64'?: string;
    'id_card_front_base64'?: string;
    'id_number': string;
    'id_photo_base64'?: string;
    'real_name': string;
    'verify_code'?: string;
}
export interface UpdateUserInfoRequest {
    'avatar'?: string;
    'nickname'?: string;
    'user_id': number;
}
export interface WithdrawAccountCancellation200Response {
    'cooling_end_cleared'?: boolean;
    'message'?: string;
    'status'?: string;
    'user_id'?: number;
    'withdrawn_at'?: number;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 申请注销账号（校验后进入冷静期，并吊销 refresh token）
         * @param {ApplyAccountCancellationRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        applyAccountCancellation: async (body: ApplyAccountCancellationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('applyAccountCancellation', 'body', body)
            const localVarPath = `/api/v1/user/cancellation/apply`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 绑定邮箱/手机号（已登录，邮箱或手机号二选一 + 验证码；验证码校验成功后进行绑定）
         * @param {BindContactRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bindContact: async (body: BindContactRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('bindContact', 'body', body)
            const localVarPath = `/api/v1/user/bind`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 修改密码：验证旧密码后修改（新密码需输入两次且一致，且不能与旧密码一致）
         * @param {ChangePasswordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword: async (body: ChangePasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('changePassword', 'body', body)
            const localVarPath = `/api/v1/user/password/change`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 注销二次确认页说明文案
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccountCancellationConfirm: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/user/cancellation/confirm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 查询注销状态：normal / cooling_off / cancelled
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccountCancellationStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/user/cancellation/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取最近一次实名提交的脱敏审核信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRealNameAuditInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/user/realname/audit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 查询实名认证总状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRealNameStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/user/realname/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 统一登录：account 或 email/mobile + password（密码登录）或 verify_code（验证码登录/静默注册，先发 verify/send scene=login）；微信/Google 走 OAuth
         * @param {LoginRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (body: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('login', 'body', body)
            const localVarPath = `/api/v1/user/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Google OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
         * @param {string} code 
         * @param {string} [state] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oauthGoogleCallback: async (code: string, state?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('oauthGoogleCallback', 'code', code)
            const localVarPath = `/api/v1/user/oauth/google/callback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 微信 OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
         * @param {string} code 
         * @param {string} [state] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oauthWechatCallback: async (code: string, state?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('oauthWechatCallback', 'code', code)
            const localVarPath = `/api/v1/user/oauth/wechat/callback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 实名换绑：旧邮箱/手机不可收码时，凭姓名+身份证号+新号验证码（scene=bind）换绑；须已通过个人身份证实名
         * @param {RealnameRebindRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        realnameRebind: async (body: RealnameRebindRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('realnameRebind', 'body', body)
            const localVarPath = `/api/v1/user/rebind/realname`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 换绑邮箱/手机号（已登录：旧账号验证码通过 + 新账号验证码通过后完成换绑）
         * @param {RebindContactRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rebindContact: async (body: RebindContactRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('rebindContact', 'body', body)
            const localVarPath = `/api/v1/user/rebind`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 刷新 Token：使用 refresh_token 换取新的 access_token（无需重新登录）
         * @param {RefreshTokenRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshToken: async (body: RefreshTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('refreshToken', 'body', body)
            const localVarPath = `/api/v1/user/token/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 用户注册（需先发验证码；按邮箱/手机判断是否已注册；密码加盐存储）
         * @param {RegisterRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register: async (body: RegisterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('register', 'body', body)
            const localVarPath = `/api/v1/user/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 忘记旧密码：邮箱/手机号发送验证码后，验证验证码重置密码（新密码需输入两次且一致，且不能与旧密码一致）
         * @param {ResetPasswordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetPassword: async (body: ResetPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('resetPassword', 'body', body)
            const localVarPath = `/api/v1/user/password/reset`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 发送验证码（邮箱或手机二选一，1分钟有效，1分钟最多3条，超过提示3分钟后重试）
         * @param {SendVerifyCodeRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendVerifyCode: async (body: SendVerifyCodeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('sendVerifyCode', 'body', body)
            const localVarPath = `/api/v1/user/verify/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 提交实名认证（Mock/三方核验 + 可选人工审核）
         * @param {SubmitRealNameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitRealName: async (body: SubmitRealNameRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('submitRealName', 'body', body)
            const localVarPath = `/api/v1/user/realname/submit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新用户基本信息（传 user_id + nickname/avatar；Header 携带 token；仅可修改本人）
         * @param {UpdateUserInfoRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserInfo: async (body: UpdateUserInfoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('updateUserInfo', 'body', body)
            const localVarPath = `/api/v1/user/info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 撤销注销申请（仅冷静期内）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        withdrawAccountCancellation: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/user/cancellation/withdraw`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 申请注销账号（校验后进入冷静期，并吊销 refresh token）
         * @param {ApplyAccountCancellationRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async applyAccountCancellation(body: ApplyAccountCancellationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApplyAccountCancellation200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.applyAccountCancellation(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.applyAccountCancellation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 绑定邮箱/手机号（已登录，邮箱或手机号二选一 + 验证码；验证码校验成功后进行绑定）
         * @param {BindContactRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bindContact(body: BindContactRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BindContact200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bindContact(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.bindContact']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 修改密码：验证旧密码后修改（新密码需输入两次且一致，且不能与旧密码一致）
         * @param {ChangePasswordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword(body: ChangePasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BindContact200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.changePassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 注销二次确认页说明文案
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAccountCancellationConfirm(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAccountCancellationConfirm200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAccountCancellationConfirm(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAccountCancellationConfirm']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 查询注销状态：normal / cooling_off / cancelled
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAccountCancellationStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAccountCancellationStatus200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAccountCancellationStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAccountCancellationStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取最近一次实名提交的脱敏审核信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRealNameAuditInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRealNameAuditInfo200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRealNameAuditInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getRealNameAuditInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 查询实名认证总状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRealNameStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRealNameStatus200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRealNameStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getRealNameStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 统一登录：account 或 email/mobile + password（密码登录）或 verify_code（验证码登录/静默注册，先发 verify/send scene=login）；微信/Google 走 OAuth
         * @param {LoginRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(body: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Login200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Google OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
         * @param {string} code 
         * @param {string} [state] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oauthGoogleCallback(code: string, state?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Login200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.oauthGoogleCallback(code, state, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.oauthGoogleCallback']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 微信 OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
         * @param {string} code 
         * @param {string} [state] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oauthWechatCallback(code: string, state?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Login200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.oauthWechatCallback(code, state, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.oauthWechatCallback']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 实名换绑：旧邮箱/手机不可收码时，凭姓名+身份证号+新号验证码（scene=bind）换绑；须已通过个人身份证实名
         * @param {RealnameRebindRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async realnameRebind(body: RealnameRebindRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BindContact200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.realnameRebind(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.realnameRebind']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 换绑邮箱/手机号（已登录：旧账号验证码通过 + 新账号验证码通过后完成换绑）
         * @param {RebindContactRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rebindContact(body: RebindContactRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BindContact200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rebindContact(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.rebindContact']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 刷新 Token：使用 refresh_token 换取新的 access_token（无需重新登录）
         * @param {RefreshTokenRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refreshToken(body: RefreshTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RefreshToken200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refreshToken(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.refreshToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 用户注册（需先发验证码；按邮箱/手机判断是否已注册；密码加盐存储）
         * @param {RegisterRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async register(body: RegisterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Register200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.register(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.register']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 忘记旧密码：邮箱/手机号发送验证码后，验证验证码重置密码（新密码需输入两次且一致，且不能与旧密码一致）
         * @param {ResetPasswordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resetPassword(body: ResetPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BindContact200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resetPassword(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.resetPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 发送验证码（邮箱或手机二选一，1分钟有效，1分钟最多3条，超过提示3分钟后重试）
         * @param {SendVerifyCodeRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendVerifyCode(body: SendVerifyCodeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SendVerifyCode200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendVerifyCode(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.sendVerifyCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 提交实名认证（Mock/三方核验 + 可选人工审核）
         * @param {SubmitRealNameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitRealName(body: SubmitRealNameRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubmitRealName200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitRealName(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.submitRealName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 更新用户基本信息（传 user_id + nickname/avatar；Header 携带 token；仅可修改本人）
         * @param {UpdateUserInfoRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUserInfo(body: UpdateUserInfoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BindContact200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserInfo(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateUserInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 撤销注销申请（仅冷静期内）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async withdrawAccountCancellation(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WithdrawAccountCancellation200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.withdrawAccountCancellation(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.withdrawAccountCancellation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary 申请注销账号（校验后进入冷静期，并吊销 refresh token）
         * @param {ApplyAccountCancellationRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        applyAccountCancellation(body: ApplyAccountCancellationRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApplyAccountCancellation200Response> {
            return localVarFp.applyAccountCancellation(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 绑定邮箱/手机号（已登录，邮箱或手机号二选一 + 验证码；验证码校验成功后进行绑定）
         * @param {BindContactRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bindContact(body: BindContactRequest, options?: RawAxiosRequestConfig): AxiosPromise<BindContact200Response> {
            return localVarFp.bindContact(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 修改密码：验证旧密码后修改（新密码需输入两次且一致，且不能与旧密码一致）
         * @param {ChangePasswordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(body: ChangePasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<BindContact200Response> {
            return localVarFp.changePassword(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 注销二次确认页说明文案
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccountCancellationConfirm(options?: RawAxiosRequestConfig): AxiosPromise<GetAccountCancellationConfirm200Response> {
            return localVarFp.getAccountCancellationConfirm(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 查询注销状态：normal / cooling_off / cancelled
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccountCancellationStatus(options?: RawAxiosRequestConfig): AxiosPromise<GetAccountCancellationStatus200Response> {
            return localVarFp.getAccountCancellationStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取最近一次实名提交的脱敏审核信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRealNameAuditInfo(options?: RawAxiosRequestConfig): AxiosPromise<GetRealNameAuditInfo200Response> {
            return localVarFp.getRealNameAuditInfo(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 查询实名认证总状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRealNameStatus(options?: RawAxiosRequestConfig): AxiosPromise<GetRealNameStatus200Response> {
            return localVarFp.getRealNameStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 统一登录：account 或 email/mobile + password（密码登录）或 verify_code（验证码登录/静默注册，先发 verify/send scene=login）；微信/Google 走 OAuth
         * @param {LoginRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(body: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<Login200Response> {
            return localVarFp.login(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Google OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
         * @param {string} code 
         * @param {string} [state] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oauthGoogleCallback(code: string, state?: string, options?: RawAxiosRequestConfig): AxiosPromise<Login200Response> {
            return localVarFp.oauthGoogleCallback(code, state, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 微信 OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
         * @param {string} code 
         * @param {string} [state] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oauthWechatCallback(code: string, state?: string, options?: RawAxiosRequestConfig): AxiosPromise<Login200Response> {
            return localVarFp.oauthWechatCallback(code, state, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 实名换绑：旧邮箱/手机不可收码时，凭姓名+身份证号+新号验证码（scene=bind）换绑；须已通过个人身份证实名
         * @param {RealnameRebindRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        realnameRebind(body: RealnameRebindRequest, options?: RawAxiosRequestConfig): AxiosPromise<BindContact200Response> {
            return localVarFp.realnameRebind(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 换绑邮箱/手机号（已登录：旧账号验证码通过 + 新账号验证码通过后完成换绑）
         * @param {RebindContactRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rebindContact(body: RebindContactRequest, options?: RawAxiosRequestConfig): AxiosPromise<BindContact200Response> {
            return localVarFp.rebindContact(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 刷新 Token：使用 refresh_token 换取新的 access_token（无需重新登录）
         * @param {RefreshTokenRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refreshToken(body: RefreshTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<RefreshToken200Response> {
            return localVarFp.refreshToken(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 用户注册（需先发验证码；按邮箱/手机判断是否已注册；密码加盐存储）
         * @param {RegisterRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register(body: RegisterRequest, options?: RawAxiosRequestConfig): AxiosPromise<Register200Response> {
            return localVarFp.register(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 忘记旧密码：邮箱/手机号发送验证码后，验证验证码重置密码（新密码需输入两次且一致，且不能与旧密码一致）
         * @param {ResetPasswordRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetPassword(body: ResetPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<BindContact200Response> {
            return localVarFp.resetPassword(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 发送验证码（邮箱或手机二选一，1分钟有效，1分钟最多3条，超过提示3分钟后重试）
         * @param {SendVerifyCodeRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendVerifyCode(body: SendVerifyCodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<SendVerifyCode200Response> {
            return localVarFp.sendVerifyCode(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 提交实名认证（Mock/三方核验 + 可选人工审核）
         * @param {SubmitRealNameRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitRealName(body: SubmitRealNameRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubmitRealName200Response> {
            return localVarFp.submitRealName(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新用户基本信息（传 user_id + nickname/avatar；Header 携带 token；仅可修改本人）
         * @param {UpdateUserInfoRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserInfo(body: UpdateUserInfoRequest, options?: RawAxiosRequestConfig): AxiosPromise<BindContact200Response> {
            return localVarFp.updateUserInfo(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 撤销注销申请（仅冷静期内）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        withdrawAccountCancellation(options?: RawAxiosRequestConfig): AxiosPromise<WithdrawAccountCancellation200Response> {
            return localVarFp.withdrawAccountCancellation(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary 申请注销账号（校验后进入冷静期，并吊销 refresh token）
     * @param {ApplyAccountCancellationRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public applyAccountCancellation(body: ApplyAccountCancellationRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).applyAccountCancellation(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 绑定邮箱/手机号（已登录，邮箱或手机号二选一 + 验证码；验证码校验成功后进行绑定）
     * @param {BindContactRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public bindContact(body: BindContactRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).bindContact(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 修改密码：验证旧密码后修改（新密码需输入两次且一致，且不能与旧密码一致）
     * @param {ChangePasswordRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public changePassword(body: ChangePasswordRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).changePassword(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 注销二次确认页说明文案
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAccountCancellationConfirm(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAccountCancellationConfirm(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 查询注销状态：normal / cooling_off / cancelled
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAccountCancellationStatus(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAccountCancellationStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取最近一次实名提交的脱敏审核信息
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRealNameAuditInfo(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getRealNameAuditInfo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 查询实名认证总状态
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRealNameStatus(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getRealNameStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 统一登录：account 或 email/mobile + password（密码登录）或 verify_code（验证码登录/静默注册，先发 verify/send scene=login）；微信/Google 走 OAuth
     * @param {LoginRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(body: LoginRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).login(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Google OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
     * @param {string} code 
     * @param {string} [state] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public oauthGoogleCallback(code: string, state?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).oauthGoogleCallback(code, state, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 微信 OAuth 直接登录（授权后回调，自动创建/绑定用户并返回 token，无需单独注册）
     * @param {string} code 
     * @param {string} [state] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public oauthWechatCallback(code: string, state?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).oauthWechatCallback(code, state, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 实名换绑：旧邮箱/手机不可收码时，凭姓名+身份证号+新号验证码（scene=bind）换绑；须已通过个人身份证实名
     * @param {RealnameRebindRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public realnameRebind(body: RealnameRebindRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).realnameRebind(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 换绑邮箱/手机号（已登录：旧账号验证码通过 + 新账号验证码通过后完成换绑）
     * @param {RebindContactRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public rebindContact(body: RebindContactRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).rebindContact(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 刷新 Token：使用 refresh_token 换取新的 access_token（无需重新登录）
     * @param {RefreshTokenRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public refreshToken(body: RefreshTokenRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).refreshToken(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 用户注册（需先发验证码；按邮箱/手机判断是否已注册；密码加盐存储）
     * @param {RegisterRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public register(body: RegisterRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).register(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 忘记旧密码：邮箱/手机号发送验证码后，验证验证码重置密码（新密码需输入两次且一致，且不能与旧密码一致）
     * @param {ResetPasswordRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public resetPassword(body: ResetPasswordRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).resetPassword(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 发送验证码（邮箱或手机二选一，1分钟有效，1分钟最多3条，超过提示3分钟后重试）
     * @param {SendVerifyCodeRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendVerifyCode(body: SendVerifyCodeRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).sendVerifyCode(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 提交实名认证（Mock/三方核验 + 可选人工审核）
     * @param {SubmitRealNameRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public submitRealName(body: SubmitRealNameRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).submitRealName(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新用户基本信息（传 user_id + nickname/avatar；Header 携带 token；仅可修改本人）
     * @param {UpdateUserInfoRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateUserInfo(body: UpdateUserInfoRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateUserInfo(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 撤销注销申请（仅冷静期内）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public withdrawAccountCancellation(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).withdrawAccountCancellation(options).then((request) => request(this.axios, this.basePath));
    }
}



