// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// ContentListItem 内容列表单条数据
type ContentListItem struct {
	ID           int64  `json:"id"`
	Title        string `json:"title"`
	CoverURL     string `json:"cover_url"`
	Artist       string `json:"artist"`
	Duration     int    `json:"duration"`
	VipLevel     int16  `json:"vip_level"`
	IsVipContent bool   `json:"is_vip_content"`
	CanPlay      bool   `json:"can_play"`
	PublishedAt  string `json:"published_at"`
	Format       string `json:"format,omitempty"`
	Sort         int    `json:"sort,omitempty"`
}

// ContentListReq 内容列表请求
type ContentListReq struct {
	Page       int32  `form:"page"`
	PageSize   int32  `form:"page_size"`
	CategoryID int64  `form:"category_id"`
	TagIDs     string `form:"tag_ids"`
	Keyword    string `form:"keyword"`
	Sort       int32  `form:"sort"`
	IsVip      int32  `form:"is_vip"`
}

// ContentListResp 内容列表响应
type ContentListResp struct {
	Total    int64             `json:"total"`
	List     []ContentListItem `json:"list"`
	Page     int               `json:"page"`
	PageSize int               `json:"page_size"`
	HasMore  bool              `json:"has_more"`
}

// ContentDetailResp 内容详情响应
type ContentDetailResp struct {
	ID              int64  `json:"id"`
	Title           string `json:"title"`
	CoverURL        string `json:"cover_url"`
	AudioURL        string `json:"audio_url"`
	Artist          string `json:"artist"`
	Duration        int    `json:"duration"`
	VipLevel        int16  `json:"vip_level"`
	IsVipContent    bool   `json:"is_vip_content"`
	CanPlay         bool   `json:"can_play"`
	CanPlayFull     bool   `json:"can_play_full"`
	PreviewSeconds  int    `json:"preview_seconds,omitempty"`
	Format          string `json:"format,omitempty"`
	SizeBytes       int64  `json:"size_bytes,omitempty"`
	Bitrate         int    `json:"bitrate,omitempty"`
	SpatialParams   string `json:"spatial_params,omitempty"`
	CategoryID      int64  `json:"category_id,omitempty"`
	PlayCount       int64  `json:"play_count"`
	LikeCount       int64  `json:"like_count"`
	IsLiked         bool   `json:"is_liked"`
	PublishedAt     string `json:"published_at"`
	AudioValidFrom  string `json:"audio_valid_from,omitempty"`
	AudioValidUntil string `json:"audio_valid_until,omitempty"`
}

// RecommendItem 推荐内容单条数据
type RecommendItem struct {
	ID           int64  `json:"id"`
	Title        string `json:"title"`
	CoverURL     string `json:"cover_url"`
	Artist       string `json:"artist"`
	Duration     int    `json:"duration"`
	VipLevel     int16  `json:"vip_level"`
	IsVipContent bool   `json:"is_vip_content"`
	CanPlay      bool   `json:"can_play"`
	CanPlayFull  bool   `json:"can_play_full"`
	Score        int    `json:"score"`
	Reason       string `json:"reason"`
}

// RecommendReq 推荐请求
type RecommendReq struct {
	Limit int32  `form:"limit"`
	Type  string `form:"type"`
}

// RecommendResp 推荐响应
type RecommendResp struct {
	Total  int64            `json:"total"`
	List   []RecommendItem  `json:"list"`
	Reason map[string]int64 `json:"reason,omitempty"`
}

// PopularItem 热门内容单条数据
type PopularItem struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	CoverURL    string `json:"cover_url"`
	Artist      string `json:"artist"`
	Duration    int    `json:"duration"`
	VipLevel    int16  `json:"vip_level"`
	IsVip       bool   `json:"is_vip"`
	CanPlay     bool   `json:"can_play"`
	HotScore    int    `json:"hot_score"`
	PlayCount   int64  `json:"play_count"`
	LikeCount   int64  `json:"like_count"`
	IsNew       bool   `json:"is_new"`
	Rank        int    `json:"rank"`
	PublishedAt string `json:"published_at"`
}

// PopularReq 热门推荐请求
type PopularReq struct {
	Limit    int32  `form:"limit"`
	Period   string `form:"period"`
	Category int64  `form:"category"`
}

// PopularResp 热门推荐响应
type PopularResp struct {
	Total     int64         `json:"total"`
	List      []PopularItem `json:"list"`
	Period    string        `json:"period"`
	UpdatedAt string        `json:"updated_at"`
}

// NewContentItem 最新内容单条数据
type NewContentItem struct {
	ID                   int64  `json:"id"`
	Title                string `json:"title"`
	CoverURL             string `json:"cover_url"`
	Artist               string `json:"artist"`
	Duration             int    `json:"duration"`
	VipLevel             int16  `json:"vip_level"`
	IsVip                bool   `json:"is_vip"`
	CanPlay              bool   `json:"can_play"`
	IsNew                bool   `json:"is_new"`
	NewBadge             string `json:"new_badge,omitempty"`
	Reason               string `json:"reason"`
	DaysAgo              int    `json:"days_ago"`
	PublishedAt          string `json:"published_at"`
	IsSubscriptionArtist bool   `json:"is_subscription_artist"`
	IsSubscriptionSeries bool   `json:"is_subscription_series"`
}

// NewContentReq 最新内容推荐请求
type NewContentReq struct {
	Limit    int32 `form:"limit"`
	Days     int32 `form:"days"`
	Category int64 `form:"category"`
}

// NewContentResp 最新内容推荐响应
type NewContentResp struct {
	Total               int64            `json:"total"`
	List                []NewContentItem `json:"list"`
	Days                int              `json:"days"`
	HasSubscriptionNew  bool             `json:"has_subscription_new"`
	SubscriptionArtists []string         `json:"subscription_artists,omitempty"`
	UpdatedAt           string           `json:"updated_at"`
}

// ForYouItem 猜你喜欢单条数据
type ForYouItem struct {
	ID       int64    `json:"id"`
	Title    string   `json:"title"`
	CoverURL string   `json:"cover_url"`
	Artist   string   `json:"artist"`
	Duration int      `json:"duration"`
	VipLevel int16    `json:"vip_level"`
	IsVip    bool     `json:"is_vip"`
	CanPlay  bool     `json:"can_play"`
	Score    float64  `json:"score"`
	Reason   string   `json:"reason"`
	Tags     []string `json:"tags,omitempty"`
	Source   string   `json:"source"`
}

// ForYouReq 猜你喜欢请求
type ForYouReq struct {
	Limit      int32  `form:"limit"`
	ExcludeIDs string `form:"exclude_ids"`
}

// ForYouResp 猜你喜欢响应
type ForYouResp struct {
	Total     int64        `json:"total"`
	List      []ForYouItem `json:"list"`
	UserTags  []string     `json:"user_tags,omitempty"`
	UpdatedAt string       `json:"updated_at"`
}

// DownloadReq 下载请求
type DownloadReq struct {
	ContentID int64 `form:"content_id"`
}

// DownloadResp 下载响应
type DownloadResp struct {
	ID             int64  `json:"id"`
	DownloadURL    string `json:"download_url"`
	FileName       string `json:"file_name"`
	FileSize       int64  `json:"file_size"`
	ContentType    string `json:"content_type"`
	DownloadTime   string `json:"download_time"`
	IsFirst        bool   `json:"is_first"`
	ExpiresAt      string `json:"expires_at,omitempty"`
	TotalDownloads int64  `json:"total_downloads"`
}

// DownloadListReq 下载列表请求
type DownloadListReq struct {
	Page     int32 `form:"page"`
	PageSize int32 `form:"page_size"`
	Size     int32 `form:"size"`
}

// DownloadItem 下载项（用于列表）
type DownloadItem struct {
	RecordID     int64  `json:"record_id"`
	ContentID    int64  `json:"content_id"`
	ContentName  string `json:"content_name"`
	Title        string `json:"title"`
	CoverURL     string `json:"cover_url"`
	Artist       string `json:"artist"`
	Duration     int    `json:"duration"`
	DownloadAt   string `json:"download_at"`
	DownloadTime string `json:"download_time"`
	FileSize     string `json:"file_size"`
	Status       string `json:"status"`
	IsOffline    bool   `json:"is_offline"`
}

// DownloadListItem 下载列表单条
type DownloadListItem = DownloadItem

// DownloadListResp 下载列表响应
type DownloadListResp struct {
	Total      int64              `json:"total"`
	List       []DownloadListItem `json:"list"`
	Page       int32              `json:"page"`
	PageSize   int32              `json:"page_size"`
	TotalPages int32              `json:"total_pages"`
}

// DownloadDeleteReq 删除下载记录请求
type DownloadDeleteReq struct {
	IDs       []int64 `json:"ids"`
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadSyncAddReq 加入同步队列请求
type DownloadSyncAddReq struct {
	ContentID int64 `json:"content_id"`
}

// DownloadSyncAddResp 加入同步队列响应
type DownloadSyncAddResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// DownloadSyncReq 同步请求
type DownloadSyncReq struct {
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadSyncListReq 同步列表请求
type DownloadSyncListReq struct{}

// DownloadSyncItem 待同步项
type DownloadSyncItem struct {
	RecordID      int64  `json:"record_id"`
	ContentID     int64  `json:"content_id"`
	Title         string `json:"title"`
	ContentName   string `json:"content_name"`
	CoverURL      string `json:"cover_url"`
	Status        string `json:"status"`
	SyncStatus    int16  `json:"sync_status"`
	SyncStatusText string `json:"sync_status_text"`
	DownloadTime  string `json:"download_time"`
	CreatedAt     string `json:"created_at"`
}

// DownloadSyncListResp 同步列表响应
type DownloadSyncListResp struct {
	Total int64              `json:"total"`
	List  []DownloadSyncItem `json:"list"`
}

// DownloadSyncConfirmReq 确认删除云端记录请求
type DownloadSyncConfirmReq struct {
	IDs       []int64 `json:"ids"`
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadSyncConfirmResp 确认删除云端记录响应
type DownloadSyncConfirmResp struct {
	Success      bool   `json:"success"`
	Message      string `json:"message"`
	DeletedCount int64  `json:"deleted_count"`
	FailedCount  int64  `json:"failed_count"`
}

// DownloadSyncCancelReq 取消同步请求
type DownloadSyncCancelReq struct {
	IDs       []int64 `json:"ids"`
	RecordIDs []int64 `json:"record_ids,omitempty"`
}
