// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// ContentListItem 内容列表单条数据
type ContentListItem struct {
	ID           int64  `json:"id"`
	Title        string `json:"title"`
	CoverURL     string `json:"cover_url"`
	Artist       string `json:"artist"`
	Duration     int    `json:"duration"`
	VipLevel     int16  `json:"vip_level"`
	IsVipContent bool   `json:"is_vip_content"`
	CanPlay      bool   `json:"can_play"`
	PublishedAt  string `json:"published_at"`
	Format       string `json:"format,omitempty"`
	Sort         int    `json:"sort,omitempty"`
}

// ContentListReq 内容列表请求
type ContentListReq struct {
	Page       int32  `form:"page"`
	PageSize   int32  `form:"page_size"`
	CategoryID int64  `form:"category_id"`
	TagIDs     string `form:"tag_ids"`
	Keyword    string `form:"keyword"`
	Sort       int32  `form:"sort"`
	IsVip      int32  `form:"is_vip"`
}

// ContentListResp 内容列表响应
type ContentListResp struct {
	Total    int64             `json:"total"`
	List     []ContentListItem `json:"list"`
	Page     int               `json:"page"`
	PageSize int               `json:"page_size"`
	HasMore  bool              `json:"has_more"`
}

// ContentDetailResp 内容详情响应
type ContentDetailResp struct {
	ID              int64  `json:"id"`
	Title           string `json:"title"`
	CoverURL        string `json:"cover_url"`
	AudioURL        string `json:"audio_url"`
	Artist          string `json:"artist"`
	Duration        int    `json:"duration"`
	VipLevel        int16  `json:"vip_level"`
	IsVipContent    bool   `json:"is_vip_content"`
	CanPlay         bool   `json:"can_play"`
	CanPlayFull     bool   `json:"can_play_full"`
	PreviewSeconds  int    `json:"preview_seconds,omitempty"`
	Format          string `json:"format,omitempty"`
	SizeBytes       int64  `json:"size_bytes,omitempty"`
	Bitrate         int    `json:"bitrate,omitempty"`
	SpatialParams   string `json:"spatial_params,omitempty"`
	CategoryID      int64  `json:"category_id,omitempty"`
	PlayCount       int64  `json:"play_count"`
	LikeCount       int64  `json:"like_count"`
	IsLiked         bool   `json:"is_liked"`
	PublishedAt     string `json:"published_at"`
	AudioValidFrom  string `json:"audio_valid_from,omitempty"`
	AudioValidUntil string `json:"audio_valid_until,omitempty"`
}

// RecommendItem 推荐内容单条数据
type RecommendItem struct {
	ID           int64  `json:"id"`
	Title        string `json:"title"`
	CoverURL     string `json:"cover_url"`
	Artist       string `json:"artist"`
	Duration     int    `json:"duration"`
	VipLevel     int16  `json:"vip_level"`
	IsVipContent bool   `json:"is_vip_content"`
	CanPlay      bool   `json:"can_play"`
	CanPlayFull  bool   `json:"can_play_full"`
	Score        int    `json:"score"`
	Reason       string `json:"reason"`
}

// RecommendReq 推荐请求
type RecommendReq struct {
	Limit int32  `form:"limit"`
	Type  string `form:"type"`
}

// RecommendResp 推荐响应
type RecommendResp struct {
	Total  int64            `json:"total"`
	List   []RecommendItem  `json:"list"`
	Reason map[string]int64 `json:"reason,omitempty"`
}

// PopularItem 热门内容单条数据
type PopularItem struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	CoverURL    string `json:"cover_url"`
	Artist      string `json:"artist"`
	Duration    int    `json:"duration"`
	VipLevel    int16  `json:"vip_level"`
	IsVip       bool   `json:"is_vip"`
	CanPlay     bool   `json:"can_play"`
	HotScore    int    `json:"hot_score"`
	PlayCount   int64  `json:"play_count"`
	LikeCount   int64  `json:"like_count"`
	IsNew       bool   `json:"is_new"`
	Rank        int    `json:"rank"`
	PublishedAt string `json:"published_at"`
}

// PopularReq 热门推荐请求
type PopularReq struct {
	Limit    int32  `form:"limit"`
	Period   string `form:"period"`
	Category int64  `form:"category"`
}

// PopularResp 热门推荐响应
type PopularResp struct {
	Total     int64         `json:"total"`
	List      []PopularItem `json:"list"`
	Period    string        `json:"period"`
	UpdatedAt string        `json:"updated_at"`
}

// NewContentItem 最新内容单条数据
type NewContentItem struct {
	ID                   int64  `json:"id"`
	Title                string `json:"title"`
	CoverURL             string `json:"cover_url"`
	Artist               string `json:"artist"`
	Duration             int    `json:"duration"`
	VipLevel             int16  `json:"vip_level"`
	IsVip                bool   `json:"is_vip"`
	CanPlay              bool   `json:"can_play"`
	IsNew                bool   `json:"is_new"`
	NewBadge             string `json:"new_badge,omitempty"`
	Reason               string `json:"reason"`
	DaysAgo              int    `json:"days_ago"`
	PublishedAt          string `json:"published_at"`
	IsSubscriptionArtist bool   `json:"is_subscription_artist"`
	IsSubscriptionSeries bool   `json:"is_subscription_series"`
}

// NewContentReq 最新内容推荐请求
type NewContentReq struct {
	Limit    int32 `form:"limit"`
	Days     int32 `form:"days"`
	Category int64 `form:"category"`
}

// NewContentResp 最新内容推荐响应
type NewContentResp struct {
	Total               int64            `json:"total"`
	List                []NewContentItem `json:"list"`
	Days                int              `json:"days"`
	HasSubscriptionNew  bool             `json:"has_subscription_new"`
	SubscriptionArtists []string         `json:"subscription_artists,omitempty"`
	UpdatedAt           string           `json:"updated_at"`
}

// ForYouItem 猜你喜欢单条数据
type ForYouItem struct {
	ID       int64    `json:"id"`
	Title    string   `json:"title"`
	CoverURL string   `json:"cover_url"`
	Artist   string   `json:"artist"`
	Duration int      `json:"duration"`
	VipLevel int16    `json:"vip_level"`
	IsVip    bool     `json:"is_vip"`
	CanPlay  bool     `json:"can_play"`
	Score    float64  `json:"score"`
	Reason   string   `json:"reason"`
	Tags     []string `json:"tags,omitempty"`
	Source   string   `json:"source"`
}

// ForYouReq 猜你喜欢请求
type ForYouReq struct {
	Limit      int32  `form:"limit"`
	ExcludeIDs string `form:"exclude_ids"`
}

// ForYouResp 猜你喜欢响应
type ForYouResp struct {
	Total     int64        `json:"total"`
	List      []ForYouItem `json:"list"`
	UserTags  []string     `json:"user_tags,omitempty"`
	UpdatedAt string       `json:"updated_at"`
}

// DownloadReq 下载请求
type DownloadReq struct {
	ContentID int64 `form:"content_id"`
}

// DownloadResp 下载响应
type DownloadResp struct {
	ID             int64  `json:"id"`
	DownloadURL    string `json:"download_url"`
	FileName       string `json:"file_name"`
	FileSize       int64  `json:"file_size"`
	ContentType    string `json:"content_type"`
	DownloadTime   string `json:"download_time"`
	IsFirst        bool   `json:"is_first"`
	ExpiresAt      string `json:"expires_at,omitempty"`
	TotalDownloads int64  `json:"total_downloads"`
}

// DownloadListReq 下载列表请求
type DownloadListReq struct {
	Page     int32 `form:"page"`
	PageSize int32 `form:"page_size"`
	Size     int32 `form:"size"`
}

// DownloadItem 下载项（用于列表）
type DownloadItem struct {
	RecordID     int64  `json:"record_id"`
	ContentID    int64  `json:"content_id"`
	ContentName  string `json:"content_name"`
	Title        string `json:"title"`
	CoverURL     string `json:"cover_url"`
	Artist       string `json:"artist"`
	Duration     int    `json:"duration"`
	DownloadAt   string `json:"download_at"`
	DownloadTime string `json:"download_time"`
	FileSize     string `json:"file_size"`
	Status       string `json:"status"`
	IsOffline    bool   `json:"is_offline"`
}

// DownloadListItem 下载列表单条
type DownloadListItem = DownloadItem

// DownloadListResp 下载列表响应
type DownloadListResp struct {
	Total      int64              `json:"total"`
	List       []DownloadListItem `json:"list"`
	Page       int32              `json:"page"`
	PageSize   int32              `json:"page_size"`
	TotalPages int32              `json:"total_pages"`
}

// DownloadDeleteReq 删除下载记录请求
type DownloadDeleteReq struct {
	IDs       []int64 `json:"ids"`
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadSyncAddReq 加入同步队列请求
type DownloadSyncAddReq struct {
	ContentID int64 `json:"content_id"`
}

// DownloadSyncAddResp 加入同步队列响应
type DownloadSyncAddResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// DownloadSyncReq 同步请求
type DownloadSyncReq struct {
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadSyncListReq 同步列表请求
type DownloadSyncListReq struct{}

// DownloadSyncItem 待同步项
type DownloadSyncItem struct {
	RecordID       int64  `json:"record_id"`
	ContentID      int64  `json:"content_id"`
	Title          string `json:"title"`
	ContentName    string `json:"content_name"`
	CoverURL       string `json:"cover_url"`
	Status         string `json:"status"`
	SyncStatus     int16  `json:"sync_status"`
	SyncStatusText string `json:"sync_status_text"`
	DownloadTime   string `json:"download_time"`
	CreatedAt      string `json:"created_at"`
}

// DownloadSyncListResp 同步列表响应
type DownloadSyncListResp struct {
	Total int64              `json:"total"`
	List  []DownloadSyncItem `json:"list"`
}

// DownloadSyncConfirmReq 确认删除云端记录请求
type DownloadSyncConfirmReq struct {
	IDs       []int64 `json:"ids"`
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadSyncConfirmResp 确认删除云端记录响应
type DownloadSyncConfirmResp struct {
	Success      bool   `json:"success"`
	Message      string `json:"message"`
	DeletedCount int64  `json:"deleted_count"`
	FailedCount  int64  `json:"failed_count"`
}

// DownloadSyncCancelReq 取消同步请求
type DownloadSyncCancelReq struct {
	IDs       []int64 `json:"ids"`
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadCompleteReq 确认下载完成请求
type DownloadCompleteReq struct {
	ContentID int64  `json:"content_id"`
	FileSize  int64  `json:"file_size"`
	LocalPath string `json:"local_path"`
}

// DownloadCompleteResp 确认下载完成响应
type DownloadCompleteResp struct {
	Success     bool   `json:"success"`
	Message     string `json:"message"`
	RecordID    int64  `json:"record_id"`
	Status      string `json:"status"`
	CompletedAt string `json:"completed_at"`
}

// ContentLikeResp 点赞/取消点赞响应
type ContentLikeResp struct {
	Success   bool   `json:"success"`
	Message   string `json:"message"`
	Liked     bool   `json:"liked"`
	LikeCount int64  `json:"like_count"`
}

// LikeListItem 点赞列表单条数据
type LikeListItem struct {
	ContentID    int64  `json:"content_id"`
	Title        string `json:"title"`
	Artist       string `json:"artist"`
	CoverURL     string `json:"cover_url"`
	Duration     int    `json:"duration"`
	LikedAt      string `json:"liked_at"`
	VipLevel     int16  `json:"vip_level"`
	IsVipContent bool   `json:"is_vip_content"`
}

// LikeListResp 点赞列表响应
type LikeListResp struct {
	Total    int64          `json:"total"`
	List     []LikeListItem `json:"list"`
	Page     int32          `json:"page"`
	PageSize int32          `json:"page_size"`
}

// PlaylistCreateReq 创建歌单请求
type PlaylistCreateReq struct {
	Name        string `json:"name" form:"name"`               // 歌单名称（必填）
	Description string `json:"description" form:"description"` // 歌单描述（可选）
	CoverURL    string `json:"cover_url" form:"cover_url"`     // 封面图片URL（可选）
}

// PlaylistCreateResp 创建歌单响应
type PlaylistCreateResp struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CoverURL    string `json:"cover_url"`
	SongCount   int    `json:"song_count"`
	CreatedAt   string `json:"created_at"`
}

// PlaylistAddSongReq 添加歌曲到歌单请求
type PlaylistAddSongReq struct {
	ContentID int64 `json:"content_id" form:"content_id"` // 歌曲ID（必填）
}

// PlaylistAddSongResp 添加歌曲到歌单响应
type PlaylistAddSongResp struct {
	Success   bool   `json:"success"`
	Message   string `json:"message"`
	SongCount int    `json:"song_count"`
}

// PlaylistUpdateReq 更新歌单请求
type PlaylistUpdateReq struct {
	Name        string `json:"name" form:"name"`               // 歌单名称（可选）
	Description string `json:"description" form:"description"` // 歌单描述（可选）
	CoverURL    string `json:"cover_url" form:"cover_url"`     // 封面图片URL（可选）
	IsPublic    *int16 `json:"is_public" form:"is_public"`     // 可见性：0-私有 1-公开（可选）
}

// PlaylistUpdateResp 更新歌单响应
type PlaylistUpdateResp struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CoverURL    string `json:"cover_url"`
	SongCount   int    `json:"song_count"`
	IsPublic    int16  `json:"is_public"`
	UpdatedAt   string `json:"updated_at"`
}

// PlaylistDeleteResp 删除歌单响应
type PlaylistDeleteResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// SubscribeReq 订阅请求
type SubscribeReq struct {
	ContentID int64 `json:"content_id" form:"content_id"` // 音频ID（必填）
	Type      int16 `json:"type" form:"type"`             // 订阅类型：1-歌曲 2-歌手 3-专辑（可选，默认1）
}

// SubscribeResp 订阅响应
type SubscribeResp struct {
	Success        bool   `json:"success"`
	Message        string `json:"message"`
	ContentID      int64  `json:"content_id"`
	SubscribeCount int64  `json:"subscribe_count"` // 更新后的订阅数
}

// UnsubscribeReq 取消订阅请求
type UnsubscribeReq struct {
	ContentID int64 `json:"content_id" form:"content_id"` // 音频ID（必填）
	Type      int16 `json:"type" form:"type"`             // 订阅类型：1-歌曲 2-歌手 3-专辑（可选，默认1）
}

// UnsubscribeResp 取消订阅响应
type UnsubscribeResp struct {
	Success        bool   `json:"success"`
	Message        string `json:"message"`
	ContentID      int64  `json:"content_id"`
	SubscribeCount int64  `json:"subscribe_count"` // 更新后的订阅数
}

// SubscribeListItem 订阅列表项
type SubscribeListItem struct {
	ID            int64  `json:"id"`
	ContentID     int64  `json:"content_id"`
	Title         string `json:"title"`
	Artist        string `json:"artist"`
	CoverURL      string `json:"cover_url"`
	Duration      int    `json:"duration"`
	VipLevel      int16  `json:"vip_level"`
	SubscribeType int16  `json:"subscribe_type"` // 1-歌曲 2-歌手 3-专辑
	SubscribedAt  string `json:"subscribed_at"`
}

// SubscribeListResp 订阅列表响应
type SubscribeListResp struct {
	Total    int64               `json:"total"`
	List     []SubscribeListItem `json:"list"`
	Page     int32               `json:"page"`
	PageSize int32               `json:"page_size"`
}

// ArtistDetailResp 歌手详情响应
type ArtistDetailResp struct {
	ID         int64             `json:"id"`
	Name       string            `json:"name"`
	AvatarURL  string            `json:"avatar_url"`
	Bio        string            `json:"bio"`
	FanCount   int64             `json:"fan_count"`
	SongCount  int64             `json:"song_count"`
	AlbumCount int64             `json:"album_count"`
	TotalPlays int64             `json:"total_plays"`
	HotSongs   []ArtistHotSong   `json:"hot_songs"` // 热门歌曲列表
	Albums     []ArtistAlbumItem `json:"albums"`    // 专辑列表
}

// ArtistHotSong 歌手热门歌曲
type ArtistHotSong struct {
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	CoverURL  string `json:"cover_url"`
	Duration  int    `json:"duration"`
	PlayCount int64  `json:"play_count"`
	VipLevel  int16  `json:"vip_level"`
}

// ArtistAlbumItem 歌手专辑项
type ArtistAlbumItem struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	CoverURL    string `json:"cover_url"`
	SongCount   int    `json:"song_count"`
	PublishedAt string `json:"published_at"`
}

// SubscribeNotifyReq 订阅通知请求
type SubscribeNotifyReq struct {
	ContentID  int64  `json:"content_id" form:"content_id"`   // 内容ID（必填）
	Title      string `json:"title" form:"title"`             // 内容标题（必填）
	NotifyType int16  `json:"notify_type" form:"notify_type"` // 通知类型：1-新歌发布 2-专辑更新 3-动态（默认1）
	JumpURL    string `json:"jump_url" form:"jump_url"`       // 跳转链接（可选）
}

// SubscribeNotifyResp 订阅通知响应
type SubscribeNotifyResp struct {
	Success      bool   `json:"success"`
	Message      string `json:"message"`
	TotalSent    int64  `json:"total_sent"`    // 发送总数
	SuccessCount int64  `json:"success_count"` // 成功数
	FailCount    int64  `json:"fail_count"`    // 失败数
	NotifyLogID  int64  `json:"notify_log_id"` // 通知日志ID
}

// NotifyLogItem 通知日志项
type NotifyLogItem struct {
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
	ContentID  int64  `json:"content_id"`
	NotifyType int16  `json:"notify_type"`
	Status     int16  `json:"status"` // 0-待发送 1-已发送 2-发送失败
	SentAt     string `json:"sent_at,omitempty"`
	ErrorMsg   string `json:"error_msg,omitempty"`
	CreatedAt  string `json:"created_at"`
}

// PlayStartReq 播放开始请求
type PlayStartReq struct {
	ContentID  int64  `json:"content_id" form:"content_id"`   // 歌曲ID（必填）
	DeviceInfo string `json:"device_info" form:"device_info"` // 设备信息（可选）
}

// PlayStartResp 播放开始响应
type PlayStartResp struct {
	PlayID    int64  `json:"play_id"`    // 播放记录ID
	PlayURL   string `json:"play_url"`   // 播放地址
	StartedAt string `json:"started_at"` // 开始时间
}

// PlayProgressReq 播放进度请求
type PlayProgressReq struct {
	PlayID   int64 `json:"play_id" form:"play_id"`   // 播放记录ID（必填）
	Progress int   `json:"progress" form:"progress"` // 当前进度（秒）
	Duration int   `json:"duration" form:"duration"` // 总时长（秒，可选）
}

// PlayCompleteReq 播放完成请求
type PlayCompleteReq struct {
	PlayID   int64 `json:"play_id" form:"play_id"`   // 播放记录ID（必填）
	Duration int   `json:"duration" form:"duration"` // 实际播放时长（秒）
}

// PlayCompleteResp 播放完成响应
type PlayCompleteResp struct {
	Success  bool   `json:"success"`
	Message  string `json:"message"`
	Duration int    `json:"duration"`
	PlayedAt string `json:"played_at"`
}

// PlayHistoryListItem 播放记录列表单条数据
type PlayHistoryListItem struct {
	PlayID      int64  `json:"play_id"`
	ContentID   int64  `json:"content_id"`
	Title       string `json:"title"`
	Artist      string `json:"artist"`
	CoverURL    string `json:"cover_url"`
	Status      int16  `json:"status"`
	Progress    int    `json:"progress"`
	Duration    int    `json:"duration"`
	PlayURL     string `json:"play_url"`
	ClientIP    string `json:"client_ip"`
	DeviceInfo  string `json:"device_info"`
	StartedAt   string `json:"started_at"`
	CompletedAt string `json:"completed_at"`
	VipLevel    int16  `json:"vip_level"`
}

// PlayHistoryListResp 播放记录列表响应
type PlayHistoryListResp struct {
	Total    int64                 `json:"total"`
	List     []PlayHistoryListItem `json:"list"`
	Page     int32                 `json:"page"`
	PageSize int32                 `json:"page_size"`
}

// SearchReq 搜索请求
type SearchReq struct {
	Keyword  string `json:"keyword" form:"keyword"`     // 搜索关键词
	Type     string `json:"type" form:"type"`           // 搜索类型: all/title/artist/lyrics
	Page     int32  `json:"page" form:"page"`           // 页码
	PageSize int32  `json:"page_size" form:"page_size"` // 每页数量
}

// SearchItem 搜索结果项
type SearchItem struct {
	ID          int64    `json:"id"`
	Title       string   `json:"title"`
	Artist      string   `json:"artist"`
	CoverURL    string   `json:"cover_url"`
	Duration    int      `json:"duration"`
	VipLevel    int16    `json:"vip_level"`
	MatchFields []string `json:"match_fields"` // 匹配的字段: title/artist/lyrics
	Score       float64  `json:"score"`        // 相关度分数
}

// SearchResp 搜索响应
type SearchResp struct {
	Total    int64        `json:"total"`
	List     []SearchItem `json:"list"`
	Page     int32        `json:"page"`
	PageSize int32        `json:"page_size"`
}

// ContentDeleteReq 删除歌曲请求
type ContentDeleteReq struct {
	ContentID int64  `json:"content_id"` // 歌曲ID（必填）
	Reason    string `json:"reason"`     // 删除原因（可选）
}

// ContentDeleteResp 删除歌曲响应
type ContentDeleteResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}
