// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

// ContentListItem 内容列表单条数据（完整版）
type ContentListItem struct {
	ContentID   int64              `json:"content_id"`   // 内容唯一ID
	Title       string             `json:"title"`        // 标题
	CoverURL    string             `json:"cover_url"`    // 封面图
	Artist      string             `json:"artist"`       // 艺术家
	Duration    int                `json:"duration"`     // 时长（秒）
	Format      string             `json:"format"`       // 文件格式
	FileSize    int64              `json:"file_size"`    // 文件大小（字节）
	Category    string             `json:"category"`     // 分类名称
	Tags        []string           `json:"tags"`         // 标签列表
	ViewCount   int64              `json:"view_count"`   // 播放量
	LikeCount   int64              `json:"like_count"`   // 点赞数
	PublishedAt string             `json:"published_at"` // 发布时间
	Permission  ListItemPermission `json:"permission"`   // 权限信息
}

// ListItemPermission 列表项权限信息
type ListItemPermission struct {
	NeedVIP       bool  `json:"need_vip"`       // 是否需要VIP
	RequiredLevel int16 `json:"required_level"` // 所需会员等级
	CanPlay       bool  `json:"can_play"`       // 是否可播放
}

// ContentListReq 内容列表请求（完整版）
type ContentListReq struct {
	Page       int32  `form:"page"`        // 页码（默认1）
	PageSize   int32  `form:"page_size"`   // 每页数量（默认20，最大100）
	CategoryID int64  `form:"category_id"` // 分类ID过滤
	TagIDs     string `form:"tag_ids"`     // 标签ID过滤（逗号分隔：1,2,3）
	Title      string `form:"title"`       // 标题模糊查询（仅匹配 title）
	Keyword    string `form:"keyword"`     // 关键词搜索（标题或艺术家）
	Sort       int32  `form:"sort"`        // 排序方式（0-综合 1-最新 2-最热 3-推荐）
	IsVip      int32  `form:"is_vip"`      // 仅会员专享（0-全部 1-仅VIP）
}

// ContentListResp 内容列表响应（完整版）
type ContentListResp struct {
	Total      int64             `json:"total"`       // 总记录数
	List       []ContentListItem `json:"list"`        // 当前页数据列表
	Page       int               `json:"page"`        // 当前页码
	PageSize   int               `json:"page_size"`   // 每页数量
	HasMore    bool              `json:"has_more"`    // 是否有更多数据
	TotalPages int               `json:"total_pages"` // 总页数
}

// ContentDetailResp 内容详情响应（完整版）
type ContentDetailResp struct {
	ContentID    int64          `json:"content_id"`    // 内容唯一ID
	Title        string         `json:"title"`         // 标题
	CoverURL     string         `json:"cover_url"`     // 封面图
	Description  string         `json:"description"`   // 描述/简介
	Duration     int            `json:"duration"`      // 时长（秒）
	Format       string         `json:"format"`        // 文件格式
	FileSize     int64          `json:"file_size"`     // 文件大小（字节）
	PlayURL      string         `json:"play_url"`      // 播放地址（有权限才返回）
	Category     string         `json:"category"`      // 分类
	Tags         []string       `json:"tags"`          // 标签
	ViewCount    int64          `json:"view_count"`    // 播放量
	LikeCount    int64          `json:"like_count"`    // 点赞数
	CommentCount int64          `json:"comment_count"` // 评论数
	CreateTime   string         `json:"create_time"`   // 创建时间
	UpdateTime   string         `json:"update_time"`   // 更新时间
	Permission   PermissionInfo `json:"permission"`    // 权限信息（必带）
}

// PermissionInfo 权限信息
type PermissionInfo struct {
	NeedVIP       bool  `json:"need_vip"`       // 是否需要VIP
	RequiredLevel int16 `json:"required_level"` // 所需会员等级
	CanPlay       bool  `json:"can_play"`       // 是否可播放
	CanDownload   bool  `json:"can_download"`   // 是否可下载
}

// RecommendItem 推荐内容单条数据
type RecommendItem struct {
	ID           int64  `json:"id"`
	Title        string `json:"title"`
	CoverURL     string `json:"cover_url"`
	Artist       string `json:"artist"`
	Duration     int    `json:"duration"`
	VipLevel     int16  `json:"vip_level"`
	IsVipContent bool   `json:"is_vip_content"`
	CanPlay      bool   `json:"can_play"`
	CanPlayFull  bool   `json:"can_play_full"`
	Score        int    `json:"score"`
	Reason       string `json:"reason"`
}

// RecommendReq 推荐请求
type RecommendReq struct {
	Limit int32  `form:"limit"`
	Type  string `form:"type"`
}

// RecommendResp 推荐响应
type RecommendResp struct {
	Total  int64            `json:"total"`
	List   []RecommendItem  `json:"list"`
	Reason map[string]int64 `json:"reason,omitempty"`
}

// PopularItem 热门内容单条数据
type PopularItem struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	CoverURL    string `json:"cover_url"`
	Artist      string `json:"artist"`
	Duration    int    `json:"duration"`
	VipLevel    int16  `json:"vip_level"`
	IsVip       bool   `json:"is_vip"`
	CanPlay     bool   `json:"can_play"`
	HotScore    int    `json:"hot_score"`
	PlayCount   int64  `json:"play_count"`
	LikeCount   int64  `json:"like_count"`
	IsNew       bool   `json:"is_new"`
	Rank        int    `json:"rank"`
	PublishedAt string `json:"published_at"`
}

// PopularReq 热门推荐请求
type PopularReq struct {
	Limit    int32  `form:"limit"`
	Period   string `form:"period"`
	Category int64  `form:"category"`
}

// PopularResp 热门推荐响应
type PopularResp struct {
	Total     int64         `json:"total"`
	List      []PopularItem `json:"list"`
	Period    string        `json:"period"`
	UpdatedAt string        `json:"updated_at"`
}

// NewContentItem 最新内容单条数据
type NewContentItem struct {
	ID                   int64  `json:"id"`
	Title                string `json:"title"`
	CoverURL             string `json:"cover_url"`
	Artist               string `json:"artist"`
	Duration             int    `json:"duration"`
	VipLevel             int16  `json:"vip_level"`
	IsVip                bool   `json:"is_vip"`
	CanPlay              bool   `json:"can_play"`
	IsNew                bool   `json:"is_new"`
	NewBadge             string `json:"new_badge,omitempty"`
	Reason               string `json:"reason"`
	DaysAgo              int    `json:"days_ago"`
	PublishedAt          string `json:"published_at"`
	IsSubscriptionArtist bool   `json:"is_subscription_artist"`
	IsSubscriptionSeries bool   `json:"is_subscription_series"`
}

// NewContentReq 最新内容推荐请求
type NewContentReq struct {
	Limit    int32 `form:"limit"`
	Days     int32 `form:"days"`
	Category int64 `form:"category"`
}

// NewContentResp 最新内容推荐响应
type NewContentResp struct {
	Total               int64            `json:"total"`
	List                []NewContentItem `json:"list"`
	Days                int              `json:"days"`
	HasSubscriptionNew  bool             `json:"has_subscription_new"`
	SubscriptionArtists []string         `json:"subscription_artists,omitempty"`
	UpdatedAt           string           `json:"updated_at"`
}

// ForYouItem 猜你喜欢单条数据
type ForYouItem struct {
	ID       int64    `json:"id"`
	Title    string   `json:"title"`
	CoverURL string   `json:"cover_url"`
	Artist   string   `json:"artist"`
	Duration int      `json:"duration"`
	VipLevel int16    `json:"vip_level"`
	IsVip    bool     `json:"is_vip"`
	CanPlay  bool     `json:"can_play"`
	Score    float64  `json:"score"`
	Reason   string   `json:"reason"`
	Tags     []string `json:"tags,omitempty"`
	Source   string   `json:"source"`
}

// ForYouReq 猜你喜欢请求
type ForYouReq struct {
	Limit      int32  `form:"limit"`
	ExcludeIDs string `form:"exclude_ids"`
}

// ForYouResp 猜你喜欢响应
type ForYouResp struct {
	Total     int64        `json:"total"`
	List      []ForYouItem `json:"list"`
	UserTags  []string     `json:"user_tags,omitempty"`
	UpdatedAt string       `json:"updated_at"`
}

// DownloadReq 下载请求
type DownloadReq struct {
	ContentID int64 `form:"content_id"`
}

// DownloadResp 下载响应
type DownloadResp struct {
	ID             int64  `json:"id"`
	DownloadURL    string `json:"download_url"`
	FileName       string `json:"file_name"`
	FileSize       int64  `json:"file_size"`
	ContentType    string `json:"content_type"`
	DownloadTime   string `json:"download_time"`
	IsFirst        bool   `json:"is_first"`
	ExpiresAt      string `json:"expires_at,omitempty"`
	TotalDownloads int64  `json:"total_downloads"`
}

// DownloadListReq 下载列表请求
type DownloadListReq struct {
	Page     int32 `form:"page"`
	PageSize int32 `form:"page_size"`
	Size     int32 `form:"size"`
}

// DownloadItem 下载项（用于列表）
type DownloadItem struct {
	RecordID     int64  `json:"record_id"`
	ContentID    int64  `json:"content_id"`
	ContentName  string `json:"content_name"`
	Title        string `json:"title"`
	CoverURL     string `json:"cover_url"`
	Artist       string `json:"artist"`
	Duration     int    `json:"duration"`
	DownloadAt   string `json:"download_at"`
	DownloadTime string `json:"download_time"`
	FileSize     string `json:"file_size"`
	Status       string `json:"status"`
	IsOffline    bool   `json:"is_offline"`
}

// DownloadListItem 下载列表单条
type DownloadListItem = DownloadItem

// DownloadListResp 下载列表响应
type DownloadListResp struct {
	Total      int64              `json:"total"`
	List       []DownloadListItem `json:"list"`
	Page       int32              `json:"page"`
	PageSize   int32              `json:"page_size"`
	TotalPages int32              `json:"total_pages"`
}

// DownloadDeleteReq 删除下载记录请求
type DownloadDeleteReq struct {
	IDs       []int64 `json:"ids"`
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadSyncAddReq 加入同步队列请求
type DownloadSyncAddReq struct {
	ContentID int64 `json:"content_id"`
}

// DownloadSyncAddResp 加入同步队列响应
type DownloadSyncAddResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// DownloadSyncReq 同步请求
type DownloadSyncReq struct {
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadSyncListReq 同步列表请求
type DownloadSyncListReq struct{}

// DownloadSyncItem 待同步项
type DownloadSyncItem struct {
	RecordID       int64  `json:"record_id"`
	ContentID      int64  `json:"content_id"`
	Title          string `json:"title"`
	ContentName    string `json:"content_name"`
	CoverURL       string `json:"cover_url"`
	Status         string `json:"status"`
	SyncStatus     int16  `json:"sync_status"`
	SyncStatusText string `json:"sync_status_text"`
	DownloadTime   string `json:"download_time"`
	CreatedAt      string `json:"created_at"`
}

// DownloadSyncListResp 同步列表响应
type DownloadSyncListResp struct {
	Total int64              `json:"total"`
	List  []DownloadSyncItem `json:"list"`
}

// DownloadSyncConfirmReq 确认删除云端记录请求
type DownloadSyncConfirmReq struct {
	IDs       []int64 `json:"ids"`
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadSyncConfirmResp 确认删除云端记录响应
type DownloadSyncConfirmResp struct {
	Success      bool   `json:"success"`
	Message      string `json:"message"`
	DeletedCount int64  `json:"deleted_count"`
	FailedCount  int64  `json:"failed_count"`
}

// DownloadSyncCancelReq 取消同步请求
type DownloadSyncCancelReq struct {
	IDs       []int64 `json:"ids"`
	RecordIDs []int64 `json:"record_ids,omitempty"`
}

// DownloadCompleteReq 确认下载完成请求
type DownloadCompleteReq struct {
	ContentID int64  `json:"content_id"`
	FileSize  int64  `json:"file_size"`
	LocalPath string `json:"local_path"`
}

// DownloadCompleteResp 确认下载完成响应
type DownloadCompleteResp struct {
	Success     bool   `json:"success"`
	Message     string `json:"message"`
	RecordID    int64  `json:"record_id"`
	Status      string `json:"status"`
	CompletedAt string `json:"completed_at"`
}

// ContentLikeResp 点赞/取消点赞响应
type ContentLikeResp struct {
	Success   bool   `json:"success"`
	Message   string `json:"message"`
	Liked     bool   `json:"liked"`
	LikeCount int64  `json:"like_count"`
}

// LikeListItem 点赞列表单条数据
type LikeListItem struct {
	ContentID    int64  `json:"content_id"`
	Title        string `json:"title"`
	Artist       string `json:"artist"`
	CoverURL     string `json:"cover_url"`
	Duration     int    `json:"duration"`
	LikedAt      string `json:"liked_at"`
	VipLevel     int16  `json:"vip_level"`
	IsVipContent bool   `json:"is_vip_content"`
}

// LikeListResp 点赞列表响应
type LikeListResp struct {
	Total    int64          `json:"total"`
	List     []LikeListItem `json:"list"`
	Page     int32          `json:"page"`
	PageSize int32          `json:"page_size"`
}

// ========== 用户收藏相关类型 ==========

// ContentFavoriteReq 用户收藏/取消收藏请求
type ContentFavoriteReq struct {
	FavoriteType string `json:"favorite_type" form:"favorite_type"` // 收藏类型：song(默认)/playlist/album
}

// ContentFavoriteResp 用户收藏/取消收藏响应
type ContentFavoriteResp struct {
	Success       bool   `json:"success"`        // 操作是否成功
	Message       string `json:"message"`        // 提示信息（"收藏成功"/"已收藏"/"取消收藏成功"/"未找到收藏记录"）
	Favorited     bool   `json:"favorited"`      // 当前收藏状态（true=已收藏，false=未收藏）
	FavoriteCount int64  `json:"favorite_count"` // 该内容的最新收藏总数
}

// FavoriteListItem 收藏列表单条数据
type FavoriteListItem struct {
	ID           int64  `json:"id"`             // 收藏记录ID
	ContentID    int64  `json:"content_id"`     // 内容ID
	Title        string `json:"title"`          // 歌曲名称
	Artist       string `json:"artist"`         // 歌手名称
	CoverURL     string `json:"cover_url"`      // 封面图地址
	Duration     int    `json:"duration"`       // 时长（秒）
	FavoritedAt  string `json:"favorited_at"`   // 收藏时间
	VipLevel     int16  `json:"vip_level"`      // 所需会员等级
	IsVipContent bool   `json:"is_vip_content"` // 是否VIP内容
	FavoriteType string `json:"favorite_type"`  // 收藏类型
}

// FavoriteListResp 收藏列表响应
type FavoriteListResp struct {
	Total    int64              `json:"total"`
	List     []FavoriteListItem `json:"list"`
	Page     int32              `json:"page"`
	PageSize int32              `json:"page_size"`
}

// PlaylistCreateReq 创建歌单请求
type PlaylistCreateReq struct {
	Name        string `json:"name" form:"name"`               // 歌单名称（必填，1-100字符）
	Description string `json:"description" form:"description"` // 歌单描述（可选，最多500字符）
	CoverURL    string `json:"cover_url" form:"cover_url"`     // 封面图片URL（可选）
	IsPublic    *bool  `json:"is_public" form:"is_public"`     // 权限类型：true=公开(默认), false=私密
}

// PlaylistCreateResp 创建歌单响应
type PlaylistCreateResp struct {
	ID          int64  `json:"id"`          // 歌单ID
	Name        string `json:"name"`        // 歌单名称
	Description string `json:"description"` // 歌单描述
	CoverURL    string `json:"cover_url"`   // 封面图片URL
	SongCount   int    `json:"song_count"`  // 歌曲数量
	IsPublic    bool   `json:"is_public"`   // 是否公开
	UserID      int64  `json:"user_id"`     // 创建人ID
	CreatedAt   string `json:"created_at"`  // 创建时间
	UpdatedAt   string `json:"updated_at"`  // 更新时间
}

// PlaylistAddSongReq 添加歌曲到歌单请求
type PlaylistAddSongReq struct {
	ContentID int64 `json:"content_id" form:"content_id"` // 歌曲ID（必填）
}

// PlaylistAddSongResp 添加歌曲到歌单响应
type PlaylistAddSongResp struct {
	Success   bool   `json:"success"`
	Message   string `json:"message"`
	SongCount int    `json:"song_count"`
}

// PlaylistUpdateReq 更新歌单请求
type PlaylistUpdateReq struct {
	Name        string `json:"name" form:"name"`               // 歌单名称（可选）
	Description string `json:"description" form:"description"` // 歌单描述（可选）
	CoverURL    string `json:"cover_url" form:"cover_url"`     // 封面图片URL（可选）
	IsPublic    *int16 `json:"is_public" form:"is_public"`     // 可见性：0-私有 1-公开（可选）
}

// PlaylistUpdateResp 更新歌单响应
type PlaylistUpdateResp struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CoverURL    string `json:"cover_url"`
	SongCount   int    `json:"song_count"`
	IsPublic    int16  `json:"is_public"`
	UpdatedAt   string `json:"updated_at"`
}

// PlaylistDeleteResp 删除歌单响应
type PlaylistDeleteResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// SubscribeReq 订阅请求
type SubscribeReq struct {
	ContentID int64 `json:"content_id" form:"content_id"` // 音频ID（必填）
	Type      int16 `json:"type" form:"type"`             // 订阅类型：1-歌曲 2-歌手 3-专辑（可选，默认1）
}

// SubscribeResp 订阅响应
type SubscribeResp struct {
	Success        bool   `json:"success"`
	Message        string `json:"message"`
	ContentID      int64  `json:"content_id"`
	SubscribeCount int64  `json:"subscribe_count"` // 更新后的订阅数
}

// UnsubscribeReq 取消订阅请求
type UnsubscribeReq struct {
	ContentID int64 `json:"content_id" form:"content_id"` // 音频ID（必填）
	Type      int16 `json:"type" form:"type"`             // 订阅类型：1-歌曲 2-歌手 3-专辑（可选，默认1）
}

// UnsubscribeResp 取消订阅响应
type UnsubscribeResp struct {
	Success        bool   `json:"success"`
	Message        string `json:"message"`
	ContentID      int64  `json:"content_id"`
	SubscribeCount int64  `json:"subscribe_count"` // 更新后的订阅数
}

// ArtistSubscribeReq 订阅艺术家请求
type ArtistSubscribeReq struct {
	ArtistID int64 `json:"artist_id" form:"artist_id"` // 艺术家 ID（必填）
}

// ArtistSubscribeResp 订阅艺术家响应
type ArtistSubscribeResp struct {
	Success    bool   `json:"success"`
	Message    string `json:"message"`
	ArtistID   int64  `json:"artist_id"`
	ArtistName string `json:"artist_name"`
	FanCount   int64  `json:"fan_count"` // 更新后的粉丝数
}

// ArtistUnsubscribeReq 取消订阅艺术家请求
type ArtistUnsubscribeReq struct {
	ArtistID int64 `json:"artist_id" form:"artist_id"` // 艺术家 ID（必填）
}

// ArtistUnsubscribeResp 取消订阅艺术家响应
type ArtistUnsubscribeResp struct {
	Success    bool   `json:"success"`
	Message    string `json:"message"`
	ArtistID   int64  `json:"artist_id"`
	ArtistName string `json:"artist_name"`
	FanCount   int64  `json:"fan_count"` // 更新后的粉丝数
}

// SubscribeListItem 订阅列表项
type SubscribeListItem struct {
	ID            int64  `json:"id"`
	ContentID     int64  `json:"content_id"`
	Title         string `json:"title"`
	Artist        string `json:"artist"`
	CoverURL      string `json:"cover_url"`
	Duration      int    `json:"duration"`
	VipLevel      int16  `json:"vip_level"`
	SubscribeType int16  `json:"subscribe_type"` // 1-歌曲 2-歌手 3-专辑
	SubscribedAt  string `json:"subscribed_at"`
}

// SubscribeListResp 订阅列表响应
type SubscribeListResp struct {
	Total    int64               `json:"total"`
	List     []SubscribeListItem `json:"list"`
	Page     int32               `json:"page"`
	PageSize int32               `json:"page_size"`
}

// ArtistDetailResp 歌手详情响应
type ArtistDetailResp struct {
	ID         int64             `json:"id"`
	Name       string            `json:"name"`
	AvatarURL  string            `json:"avatar_url"`
	Bio        string            `json:"bio"`
	FanCount   int64             `json:"fan_count"`
	SongCount  int64             `json:"song_count"`
	AlbumCount int64             `json:"album_count"`
	TotalPlays int64             `json:"total_plays"`
	HotSongs   []ArtistHotSong   `json:"hot_songs"` // 热门歌曲列表
	Albums     []ArtistAlbumItem `json:"albums"`    // 专辑列表
}

// ArtistHotSong 歌手热门歌曲
type ArtistHotSong struct {
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	CoverURL  string `json:"cover_url"`
	Duration  int    `json:"duration"`
	PlayCount int64  `json:"play_count"`
	VipLevel  int16  `json:"vip_level"`
}

// ArtistAlbumItem 歌手专辑项
type ArtistAlbumItem struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	CoverURL    string `json:"cover_url"`
	SongCount   int    `json:"song_count"`
	PublishedAt string `json:"published_at"`
}

// SubscribeNotifyReq 订阅通知请求
type SubscribeNotifyReq struct {
	ContentID  int64  `json:"content_id" form:"content_id"`   // 内容ID（必填）
	Title      string `json:"title" form:"title"`             // 内容标题（必填）
	NotifyType int16  `json:"notify_type" form:"notify_type"` // 通知类型：1-新歌发布 2-专辑更新 3-动态（默认1）
	JumpURL    string `json:"jump_url" form:"jump_url"`       // 跳转链接（可选）
}

// SubscribeNotifyResp 订阅通知响应
type SubscribeNotifyResp struct {
	Success      bool   `json:"success"`
	Message      string `json:"message"`
	TotalSent    int64  `json:"total_sent"`    // 发送总数
	SuccessCount int64  `json:"success_count"` // 成功数
	FailCount    int64  `json:"fail_count"`    // 失败数
	NotifyLogID  int64  `json:"notify_log_id"` // 通知日志ID
}

// NotifyLogItem 通知日志项
type NotifyLogItem struct {
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
	ContentID  int64  `json:"content_id"`
	NotifyType int16  `json:"notify_type"`
	Status     int16  `json:"status"` // 0-待发送 1-已发送 2-发送失败
	SentAt     string `json:"sent_at,omitempty"`
	ErrorMsg   string `json:"error_msg,omitempty"`
	CreatedAt  string `json:"created_at"`
}

// PlayStartReq 播放开始请求
type PlayStartReq struct {
	ContentID  int64  `json:"content_id" form:"content_id"`   // 歌曲ID（必填）
	DeviceInfo string `json:"device_info" form:"device_info"` // 设备信息（可选）
}

// PlayStartResp 播放开始响应
type PlayStartResp struct {
	PlayID    int64  `json:"play_id"`    // 播放记录ID
	PlayURL   string `json:"play_url"`   // 播放地址
	StartedAt string `json:"started_at"` // 开始时间
}

// PlayProgressReq 播放进度请求
type PlayProgressReq struct {
	PlayID   int64 `json:"play_id" form:"play_id"`   // 播放记录ID（必填）
	Progress int   `json:"progress" form:"progress"` // 当前进度（秒）
	Duration int   `json:"duration" form:"duration"` // 总时长（秒，可选）
}

// PlayCompleteReq 播放完成请求
type PlayCompleteReq struct {
	PlayID   int64 `json:"play_id" form:"play_id"`   // 播放记录ID（必填）
	Duration int   `json:"duration" form:"duration"` // 实际播放时长（秒）
}

// PlayCompleteResp 播放完成响应
type PlayCompleteResp struct {
	Success  bool   `json:"success"`
	Message  string `json:"message"`
	Duration int    `json:"duration"`
	PlayedAt string `json:"played_at"`
}

// PlayHistoryListItem 播放记录列表单条数据
type PlayHistoryListItem struct {
	PlayID      int64  `json:"play_id"`
	ContentID   int64  `json:"content_id"`
	Title       string `json:"title"`
	Artist      string `json:"artist"`
	CoverURL    string `json:"cover_url"`
	Status      int16  `json:"status"`
	Progress    int    `json:"progress"`
	Duration    int    `json:"duration"`
	PlayURL     string `json:"play_url"`
	ClientIP    string `json:"client_ip"`
	DeviceInfo  string `json:"device_info"`
	StartedAt   string `json:"started_at"`
	CompletedAt string `json:"completed_at"`
	VipLevel    int16  `json:"vip_level"`
}

// PlayHistoryListResp 播放记录列表响应
type PlayHistoryListResp struct {
	Total    int64                 `json:"total"`
	List     []PlayHistoryListItem `json:"list"`
	Page     int32                 `json:"page"`
	PageSize int32                 `json:"page_size"`
}

// SearchReq 搜索请求
type SearchReq struct {
	Keyword  string `json:"keyword" form:"keyword"`     // 搜索关键词
	Type     string `json:"type" form:"type"`           // 搜索类型: all/title/artist/lyrics
	Page     int32  `json:"page" form:"page"`           // 页码
	PageSize int32  `json:"page_size" form:"page_size"` // 每页数量
}

// SearchItem 搜索结果项
type SearchItem struct {
	ID          int64    `json:"id"`
	Title       string   `json:"title"`
	Artist      string   `json:"artist"`
	CoverURL    string   `json:"cover_url"`
	Duration    int      `json:"duration"`
	VipLevel    int16    `json:"vip_level"`
	MatchFields []string `json:"match_fields"` // 匹配的字段: title/artist/lyrics
	Score       float64  `json:"score"`        // 相关度分数
}

// SearchResp 搜索响应
type SearchResp struct {
	Total    int64        `json:"total"`
	List     []SearchItem `json:"list"`
	Page     int32        `json:"page"`
	PageSize int32        `json:"page_size"`
}

// ContentDeleteReq 删除歌曲请求
type ContentDeleteReq struct {
	ContentID int64  `json:"content_id"` // 歌曲ID（必填）
	Reason    string `json:"reason"`     // 删除原因（可选）
}

// ContentDeleteResp 删除歌曲响应
type ContentDeleteResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// SpotifyAuthReq Spotify授权请求（发起授权）
type SpotifyAuthReq struct {
	CallbackURL string `json:"callback_url" form:"callback_url"` // 回调地址（可选）
}

// SpotifyAuthResp Spotify授权响应（返回授权链接）
type SpotifyAuthResp struct {
	AuthURL string `json:"auth_url"` // 授权链接
}

// SpotifyCallbackReq Spotify回调请求
type SpotifyCallbackReq struct {
	Code  string `json:"code" form:"code"`   // 授权码
	State string `json:"state" form:"state"` // 状态参数
}

// SpotifyCallbackResp Spotify回调响应
type SpotifyCallbackResp struct {
	Success       bool   `json:"success"`
	Message       string `json:"message"`
	SpotifyUserID string `json:"spotify_user_id"` // Spotify用户ID
	DisplayName   string `json:"display_name"`    // 用户昵称
	AvatarURL     string `json:"avatar_url"`      // 用户头像
}

// SpotifyBindingInfo 绑定信息
type SpotifyBindingInfo struct {
	ID            int64  `json:"id"`
	UserID        int64  `json:"user_id"`
	SpotifyUserID string `json:"spotify_user_id"`
	DisplayName   string `json:"display_name"`
	AvatarURL     string `json:"avatar_url"`
	IsActive      bool   `json:"is_active"`
	BoundAt       string `json:"bound_at"`
}

// SpotifyBindingStatusResp 绑定状态响应
type SpotifyBindingStatusResp struct {
	IsBound bool                `json:"is_bound"`
	Info    *SpotifyBindingInfo `json:"info,omitempty"`
}

// SpotifyPlaylistTrackReq 获取歌单歌曲请求
type SpotifyPlaylistTrackReq struct {
	PlaylistID string `json:"playlist_id" form:"playlist_id"` // 歌单ID
	Limit      int    `json:"limit" form:"limit"`             // 每页数量
	Offset     int    `json:"offset" form:"offset"`           // 偏移量
}

// SpotifyTrackInfo 歌曲信息
type SpotifyTrackInfo struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Artists     []string `json:"artists"`
	Album       string   `json:"album"`
	AlbumImage  string   `json:"album_image"`
	DurationMs  int      `json:"duration_ms"`
	ExternalURL string   `json:"external_url"`
	PreviewURL  string   `json:"preview_url,omitempty"`
}

// SpotifyPlaylistTrackResp 歌单歌曲响应
type SpotifyPlaylistTrackResp struct {
	Total  int                `json:"total"`
	Limit  int                `json:"limit"`
	Offset int                `json:"offset"`
	Items  []SpotifyTrackInfo `json:"items"`
}

// SpotifyPlaylistInfo 歌单信息
type SpotifyPlaylistInfo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Cover       string `json:"cover"`
	SongCount   int    `json:"song_count"`
	Owner       string `json:"owner"`
	Description string `json:"description,omitempty"`
}

// SpotifyPlaylistListResp 歌单列表响应
type SpotifyPlaylistListResp struct {
	Total int                   `json:"total"`
	Items []SpotifyPlaylistInfo `json:"items"`
}

// QQMusicAuthReq QQ音乐授权请求
type QQMusicAuthReq struct {
	CallbackURL string `json:"callback_url" form:"callback_url"` // 回调地址（可选）
}

// QQMusicAuthResp QQ音乐授权响应
type QQMusicAuthResp struct {
	AuthURL string `json:"auth_url"` // 授权链接
}

// QQMusicCallbackReq QQ音乐回调请求
type QQMusicCallbackReq struct {
	Code  string `json:"code" form:"code"`   // 授权码
	State string `json:"state" form:"state"` // 状态参数
}

// QQMusicCallbackResp QQ音乐回调响应
type QQMusicCallbackResp struct {
	Success          bool                    `json:"success"`
	Message          string                  `json:"message"`
	QQOpenID         string                  `json:"qq_openid"`                    // QQ OpenID
	QQUnionID        string                  `json:"qq_unionid"`                   // QQ UnionID（可选）
	Nickname         string                  `json:"nickname"`                     // 用户昵称
	AvatarURL        string                  `json:"avatar_url"`                   // 用户头像
	MusicLibraryInfo *map[string]interface{} `json:"music_library_info,omitempty"` // 音乐库信息
}

// QQMusicBindingInfo QQ音乐绑定信息
type QQMusicBindingInfo struct {
	ID               int64                   `json:"id"`
	UserID           int64                   `json:"user_id"`
	QQOpenID         string                  `json:"qq_openid"`
	QQUnionID        string                  `json:"qq_unionid"`
	Nickname         string                  `json:"nickname"`
	AvatarURL        string                  `json:"avatar_url"`
	MusicLibraryInfo *map[string]interface{} `json:"music_library_info,omitempty"`
	IsActive         bool                    `json:"is_active"`
	BoundAt          string                  `json:"bound_at"`
}

// QQMusicBindingStatusResp QQ音乐绑定状态响应
type QQMusicBindingStatusResp struct {
	IsBound bool                `json:"is_bound"`
	Info    *QQMusicBindingInfo `json:"info,omitempty"`
}

// QQMusicPlaylistTrackReq 获取歌单歌曲请求
type QQMusicPlaylistTrackReq struct {
	PlaylistID string `json:"playlist_id" form:"playlist_id"` // 歌单ID
	Limit      int    `json:"limit" form:"limit"`             // 每页数量
	Offset     int    `json:"offset" form:"offset"`           // 偏移量
}

// QQMusicTrackInfo 歌曲信息
type QQMusicTrackInfo struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Artists     []string `json:"artists"`
	Album       string   `json:"album"`
	AlbumImage  string   `json:"album_image"`
	DurationMs  int      `json:"duration_ms"`
	ExternalURL string   `json:"external_url"`
	PreviewURL  string   `json:"preview_url,omitempty"`
}

// QQMusicPlaylistTrackResp 歌单歌曲响应
type QQMusicPlaylistTrackResp struct {
	Total  int                `json:"total"`
	Limit  int                `json:"limit"`
	Offset int                `json:"offset"`
	Items  []QQMusicTrackInfo `json:"items"`
}

// QQMusicPlaylistInfo QQ音乐歌单信息
type QQMusicPlaylistInfo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Cover       string `json:"cover"`
	SongCount   int    `json:"song_count"`
	Owner       string `json:"owner"`
	Description string `json:"description,omitempty"`
}

// QQMusicPlaylistListResp QQ音乐歌单列表响应
type QQMusicPlaylistListResp struct {
	Total int                   `json:"total"`
	Items []QQMusicPlaylistInfo `json:"items"`
}

// ImportPlaylistReq 导入歌单请求
type ImportPlaylistReq struct {
	Platform     string `json:"platform"`                // 平台: spotify, qq-music
	PlaylistID   string `json:"playlist_id"`             // 第三方歌单ID
	PlaylistName string `json:"playlist_name,omitempty"` // 歌单名称（可选，如果为空则使用第三方名称）
}

// ImportPlaylistResp 导入歌单响应
type ImportPlaylistResp struct {
	Success       bool   `json:"success"`
	Message       string `json:"message"`
	PlaylistID    int64  `json:"playlist_id"`    // 本地歌单ID
	PlaylistName  string `json:"playlist_name"`  // 本地歌单名称
	ImportedCount int    `json:"imported_count"` // 导入的歌曲数量
	TotalCount    int    `json:"total_count"`    // 歌单总歌曲数量
}

// LocalSongInfo 本地歌曲信息
type LocalSongInfo struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Artist      string `json:"artist"`
	Album       string `json:"album"`
	CoverURL    string `json:"cover_url"`
	Duration    int    `json:"duration"`
	ExternalURL string `json:"external_url,omitempty"`
	Source      string `json:"source"`    // 来源: spotify, qq-music
	SourceID    string `json:"source_id"` // 第三方歌曲ID
	CreatedAt   string `json:"created_at"`
}

// LocalPlaylistInfo 本地歌单信息
type LocalPlaylistInfo struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	CoverURL    string `json:"cover_url"`
	SongCount   int    `json:"song_count"`
	OwnerID     int64  `json:"owner_id"`
	OwnerName   string `json:"owner_name"`
	Description string `json:"description,omitempty"`
	IsPublic    bool   `json:"is_public"`
	Source      string `json:"source"`              // 来源: local, spotify, qq-music
	SourceID    string `json:"source_id,omitempty"` // 第三方歌单ID
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

// PlaylistSongInfo 歌单歌曲关联信息
type PlaylistSongInfo struct {
	PlaylistID int64  `json:"playlist_id"`
	SongID     int64  `json:"song_id"`
	SortOrder  int    `json:"sort_order"`
	AddedAt    string `json:"added_at"`
}

// SpotifyFavoriteTrack Spotify 收藏歌曲信息
type SpotifyFavoriteTrack struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Artists     []string `json:"artists"`
	Album       string   `json:"album"`
	AlbumImage  string   `json:"album_image"`
	DurationMs  int      `json:"duration_ms"`
	ExternalURL string   `json:"external_url"`
	PreviewURL  string   `json:"preview_url,omitempty"`
	AddedAt     string   `json:"added_at"`
}

// SpotifyFavoriteListResp Spotify 收藏列表响应
type SpotifyFavoriteListResp struct {
	Total  int                    `json:"total"`
	Limit  int                    `json:"limit"`
	Offset int                    `json:"offset"`
	Items  []SpotifyFavoriteTrack `json:"items"`
}

// QQMusicFavoriteTrack QQ 音乐收藏歌曲信息
type QQMusicFavoriteTrack struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Artists     []string `json:"artists"`
	Album       string   `json:"album"`
	AlbumImage  string   `json:"album_image"`
	DurationMs  int      `json:"duration_ms"`
	ExternalURL string   `json:"external_url"`
	PreviewURL  string   `json:"preview_url,omitempty"`
	AddedAt     string   `json:"added_at"`
}

// QQMusicFavoriteListResp QQ 音乐收藏列表响应
type QQMusicFavoriteListResp struct {
	Total  int                    `json:"total"`
	Limit  int                    `json:"limit"`
	Offset int                    `json:"offset"`
	Items  []QQMusicFavoriteTrack `json:"items"`
}

// ========== 设备歌曲下载相关类型 ==========

// DeviceSongDownloadReq 设备歌曲下载请求
// 用户通过前端点击下载按钮，将歌曲下载到指定设备
type DeviceSongDownloadReq struct {
	Sn        string `json:"sn" validate:"required"`         // 目标设备序列号（16位）
	ContentID int64  `json:"content_id" validate:"required"` // 内容ID（对应content表）
}

// DeviceSongDownloadResp 设备歌曲下载响应
type DeviceSongDownloadResp struct {
	TaskID    string `json:"task_id"`    // 任务ID（用于追踪）
	ContentID int64  `json:"content_id"` // 内容ID
	DeviceSN  string `json:"device_sn"`  // 设备SN
	Status    string `json:"status"`     // 状态：pending/sent/failed
	Message   string `json:"message"`    // 提示信息
}

// DeviceDownloadCallbackReq 设备下载回调请求（设备微服务→内容微服务）
// 设备下载完成后，设备微服务调用此接口通知结果
type DeviceDownloadCallbackReq struct {
	TaskID     string  `json:"task_id" validate:"required"`    // 任务ID
	DeviceSN   string  `json:"device_sn" validate:"required"`  // 设备SN
	ContentID  int64   `json:"content_id" validate:"required"` // 内容ID
	Status     string  `json:"status" validate:"required"`     // 状态：success/fail
	ErrorMsg   string  `json:"error_msg,omitempty"`            // 错误原因（失败时必填）
	LocalPath  string  `json:"local_path,omitempty"`           // 本地存储路径（成功时返回）
	FileSize   int64   `json:"file_size,omitempty"`            // 文件大小（字节）
	DurationMs int64   `json:"duration_ms,omitempty"`          // 下载耗时（毫秒）
	Progress   float64 `json:"progress,omitempty"`             // 进度百分比（0-100，可选）
}

// DeviceDownloadCallbackResp 设备下载回调响应
type DeviceDownloadCallbackResp struct {
	Success bool   `json:"success"` // 是否成功
	Message string `json:"message"` // 消息
}

// DeviceDownloadStatusQueryReq 查询设备下载状态请求
type DeviceDownloadStatusQueryReq struct {
	TaskID string `form:"task_id" validate:"required"` // 任务ID
}

// DeviceDownloadStatusQueryResp 查询设备下载状态响应
type DeviceDownloadStatusQueryResp struct {
	TaskID     string  `json:"task_id"`               // 任务ID
	ContentID  int64   `json:"content_id"`            // 内容ID
	SongName   string  `json:"song_name"`             // 歌曲名称
	DeviceSN   string  `json:"device_sn"`             // 设备SN
	Status     string  `json:"status"`                // pending/downloading/success/failed/cancelled
	Progress   float64 `json:"progress"`              // 进度百分比（0-100）
	Message    string  `json:"message"`               // 状态描述
	CreatedAt  string  `json:"created_at"`            // 创建时间
	UpdatedAt  string  `json:"updated_at"`            // 最后更新时间
	FinishedAt string  `json:"finished_at,omitempty"` // 完成时间
}

// DeviceDownloadListReq 设备下载历史列表请求
type DeviceDownloadListReq struct {
	Page     int32  `form:"page"`                // 页码（默认1）
	PageSize int32  `form:"page_size"`           // 每页数量（默认20，最大50）
	DeviceSN string `form:"sn,omitempty"`        // 设备SN过滤（可选）
	Status   string `form:"status,omitempty"`    // 状态过滤（可选：pending/downloading/success/failed）
	SongName string `form:"song_name,omitempty"` // 歌曲名称模糊查询（可选）
	Artist   string `form:"artist,omitempty"`    // 艺术家模糊查询（可选）
}

// DeviceDownloadListItem 设备下载列表（device_song_downloads ∪ user_downloads + content / 统计）
type DeviceDownloadListItem struct {
	DownloadID   int64  `json:"download_id"`             // 下载记录ID（主键）
	ContentID    int64  `json:"content_id"`              // 歌曲ID
	SongName     string `json:"song_name"`               // 歌曲名
	Artist       string `json:"artist"`                  // 歌手名称
	CoverURL     string `json:"cover_url,omitempty"`     // 封面图地址
	DurationSec  int    `json:"duration"`                // 时长（秒）
	Status       string `json:"status"`                  // 下载状态（success/failed/downloading）
	LocalPath    string `json:"local_path,omitempty"`    // 设备本地存储路径
	FileSize     int64  `json:"file_size"`               // 文件大小（字节）
	ErrorMsg     string `json:"error_msg,omitempty"`     // 错误信息
	DownloadTime string `json:"download_time,omitempty"` // 最后下载时间
}

// DeviceDownloadListResp 设备下载列表响应
type DeviceDownloadListResp struct {
	Total      int64                    `json:"total"`       // 总记录数
	List       []DeviceDownloadListItem `json:"list"`        // 当前页数据
	Page       int32                    `json:"page"`        // 当前页码
	PageSize   int32                    `json:"page_size"`   // 每页数量
	TotalPages int32                    `json:"total_pages"` // 总页数
}
